#-------------------------------------------------------------------------------
# File: clienteWS3ConsultaRobustaIMSS.4gl
# GENERATED BY fglwsdl 202306221452
#-------------------------------------------------------------------------------
# THIS FILE WAS GENERATED. DO NOT MODIFY.
#-------------------------------------------------------------------------------


IMPORT FGL WSHelper
IMPORT com
IMPORT xml

#
#-------------------------------------------------------------------------------
# XML Type definitions 
#-------------------------------------------------------------------------------
#

#
# TYPE : tgetPeriodosAsegurado
#
PUBLIC TYPE tgetPeriodosAsegurado RECORD ATTRIBUTE(XMLSequence,XSTypeName="getPeriodosAsegurado",XSTypeNamespace="http://ws.soap.semanascotizadas.cit.imss.gob.mx/")
  institutoReceptor STRING ATTRIBUTE(XMLNamespace="",XMLOptional),
  nss STRING ATTRIBUTE(XMLNamespace="",XMLOptional),
  curp STRING ATTRIBUTE(XMLNamespace="",XMLOptional),
  fechaTramite STRING ATTRIBUTE(XMLNamespace="",XMLOptional),
  correo STRING ATTRIBUTE(XMLNamespace="",XMLOptional),
  folioTramiteReceptor STRING ATTRIBUTE(XMLNamespace="",XMLOptional)
END RECORD
#-------------------------------------------------------------------------------

#
# TYPE : tRespuestaPeriodo
#
PUBLIC TYPE tRespuestaPeriodo RECORD ATTRIBUTE(XMLSequence,XSTypeName="RespuestaPeriodo",XSTypeNamespace="http://ws.soap.semanascotizadas.cit.imss.gob.mx/")
  fechaInicio STRING ATTRIBUTE(XMLNamespace="",XMLOptional),
  fechaTermino STRING ATTRIBUTE(XMLNamespace="",XMLOptional),
  nombreDependenciaOPatron STRING ATTRIBUTE(XMLNamespace="",XMLOptional),
  RP STRING ATTRIBUTE(XMLNamespace="",XMLOptional),
  entidadFederativaPatron STRING ATTRIBUTE(XMLNamespace="",XMLOptional),
  sueldoRegistradoPorPeriodo FLOAT ATTRIBUTE(XMLNamespace="",XMLOptional),
  tipoMovimiento STRING ATTRIBUTE(XMLNamespace="",XMLOptional)
END RECORD
#-------------------------------------------------------------------------------

#
# TYPE : tRespuestaConsultaPeriodos
#
PUBLIC TYPE tRespuestaConsultaPeriodos RECORD ATTRIBUTE(XMLSequence,XSTypeName="RespuestaConsultaPeriodos",XSTypeNamespace="http://ws.soap.semanascotizadas.cit.imss.gob.mx/")
  claveError INTEGER ATTRIBUTE(XMLNamespace="",XMLOptional),
  mensajeError STRING ATTRIBUTE(XMLNamespace="",XMLOptional),
  codigoResultado STRING ATTRIBUTE(XMLNamespace="",XMLOptional,XMLNillable),
  motivoRechazo STRING ATTRIBUTE(XMLNamespace="",XMLOptional),
  curp STRING ATTRIBUTE(XMLNamespace="",XMLOptional),
  primerApellido STRING ATTRIBUTE(XMLNamespace="",XMLOptional),
  segundoApellido STRING ATTRIBUTE(XMLNamespace="",XMLOptional),
  nombre STRING ATTRIBUTE(XMLNamespace="",XMLOptional),
  nss STRING ATTRIBUTE(XMLNamespace="",XMLOptional),
  fechaDeBaja STRING ATTRIBUTE(XMLNamespace="",XMLOptional),
  observaciones STRING ATTRIBUTE(XMLNamespace="",XMLOptional),
  fechaDeEnvio STRING ATTRIBUTE(XMLNamespace="",XMLOptional),
  periodosPortados INTEGER ATTRIBUTE(XMLNamespace="",XMLOptional),
  eventosDeduccion INTEGER ATTRIBUTE(XMLNamespace="",XMLOptional),
  diasCotizados INTEGER ATTRIBUTE(XMLNamespace="",XMLOptional),
  diasDescontados INTEGER ATTRIBUTE(XMLNamespace="",XMLOptional),
  diasReintegrados INTEGER ATTRIBUTE(XMLNamespace="",XMLOptional),
  totalDeDias INTEGER ATTRIBUTE(XMLNamespace="",XMLOptional),
  listaPeriodos DYNAMIC ARRAY ATTRIBUTE(XMLList) OF tRespuestaPeriodo ATTRIBUTE(XMLNamespace="")
END RECORD
#-------------------------------------------------------------------------------

#
# TYPE : tgetPeriodosAseguradoResponse
#
PUBLIC TYPE tgetPeriodosAseguradoResponse RECORD ATTRIBUTE(XMLSequence,XSTypeName="getPeriodosAseguradoResponse",XSTypeNamespace="http://ws.soap.semanascotizadas.cit.imss.gob.mx/")
  resultado tRespuestaConsultaPeriodos ATTRIBUTE(XMLNamespace="",XMLOptional)
END RECORD
#-------------------------------------------------------------------------------



#-------------------------------------------------------------------------------
# Service: WSConsultaPeriodos
# Port:    WSConsultaPeriodosPort
# Server:  http://api.dev.issste.gob.mx:80/semanascotizadas-rest/WSConsultaPeriodos
#-------------------------------------------------------------------------------
#
# Location of the SOAP endpoint.
# You can reassign this value at run-time.
#
PUBLIC DEFINE WSConsultaPeriodos_WSConsultaPeriodosPortEndpoint WSHelper.tGlobalEndpointType


#-------------------------------------------------------------------------------

# VARIABLE : getPeriodosAsegurado
PUBLIC DEFINE getPeriodosAsegurado tgetPeriodosAsegurado ATTRIBUTE(XMLName="getPeriodosAsegurado",XMLNamespace="http://ws.soap.semanascotizadas.cit.imss.gob.mx/")


#-------------------------------------------------------------------------------

# VARIABLE : getPeriodosAseguradoResponse
PUBLIC DEFINE getPeriodosAseguradoResponse tgetPeriodosAseguradoResponse ATTRIBUTE(XMLName="getPeriodosAseguradoResponse",XMLNamespace="http://ws.soap.semanascotizadas.cit.imss.gob.mx/")



# end of service types
#-------------------------------------------------------------------------------

# Start service implementation
#-------------------------------------------------------------------------------
# Service: WSConsultaPeriodos
# Port:    WSConsultaPeriodosPort
# Server:  http://api.dev.issste.gob.mx:80/semanascotizadas-rest/WSConsultaPeriodos
#-------------------------------------------------------------------------------

PRIVATE DEFINE getPeriodosAseguradoHTTPReq     com.HttpRequest
PRIVATE DEFINE getPeriodosAseguradoHTTPResp    com.HttpResponse

#-------------------------------------------------------------------------------

#
# Operation: getPeriodosAsegurado
#
#
# FUNCTION: getPeriodosAsegurado_g
#   RETURNING: soapStatus
#   INPUT:  getPeriodosAsegurado
#   OUTPUT:  getPeriodosAseguradoResponse
#
FUNCTION getPeriodosAsegurado_g()
  DEFINE wsstatus   INTEGER
  DEFINE retryAuth  INTEGER
  DEFINE retryProxy INTEGER
  DEFINE retry      INTEGER
  DEFINE fault      BOOLEAN
  DEFINE nb         INTEGER
  DEFINE uri        STRING
  DEFINE setcookie  STRING
  DEFINE mustUnderstand INTEGER
  DEFINE request    com.HttpRequest
  DEFINE response   com.HttpResponse
  DEFINE writer     xml.StaxWriter
  DEFINE reader     xml.StaxReader

  #
  # INIT VARIABLES
  #
  LET wsstatus = -1
  LET retryAuth = FALSE
  LET retryProxy = FALSE
  LET retry = TRUE
  LET fault = FALSE
  LET uri = com.WebServiceEngine.GetOption("SoapModuleURI")

  #IF WSConsultaPeriodos_WSConsultaPeriodosPortEndpoint.Address.Uri IS NULL THEN
  #  LET WSConsultaPeriodos_WSConsultaPeriodosPortEndpoint.Address.Uri = "http://api.dev.issste.gob.mx:80/semanascotizadas-rest/WSConsultaPeriodos"
  #END IF

  #
  # CREATE REQUEST
  #
  TRY
    LET request = com.HttpRequest.Create(WSConsultaPeriodos_WSConsultaPeriodosPortEndpoint.Address.Uri)
    CALL request.setMethod("POST")
    CALL request.setCharset("UTF-8")
    CALL request.setHeader("SOAPAction","\"\"")
    CALL WSHelper.WSHelper_SetRequestHeaders(request, WSConsultaPeriodos_WSConsultaPeriodosPortEndpoint.Binding.Request.Headers)
    IF WSConsultaPeriodos_WSConsultaPeriodosPortEndpoint.Binding.Version IS NOT NULL THEN
      CALL request.setVersion(WSConsultaPeriodos_WSConsultaPeriodosPortEndpoint.Binding.Version)
    END IF
    IF WSConsultaPeriodos_WSConsultaPeriodosPortEndpoint.Binding.Cookie IS NOT NULL THEN
      CALL request.setHeader("Cookie",WSConsultaPeriodos_WSConsultaPeriodosPortEndpoint.Binding.Cookie)
    END IF
    IF WSConsultaPeriodos_WSConsultaPeriodosPortEndpoint.Binding.ConnectionTimeout <> 0 THEN
      CALL request.setConnectionTimeOut(WSConsultaPeriodos_WSConsultaPeriodosPortEndpoint.Binding.ConnectionTimeout)
    END IF
    IF WSConsultaPeriodos_WSConsultaPeriodosPortEndpoint.Binding.ReadWriteTimeout <> 0 THEN
      CALL request.setTimeOut(WSConsultaPeriodos_WSConsultaPeriodosPortEndpoint.Binding.ReadWriteTimeout)
    END IF
    IF WSConsultaPeriodos_WSConsultaPeriodosPortEndpoint.Binding.CompressRequest IS NOT NULL THEN
      CALL request.setHeader("Content-Encoding",WSConsultaPeriodos_WSConsultaPeriodosPortEndpoint.Binding.CompressRequest)
    END IF
    CALL request.setHeader("Accept-Encoding","gzip, deflate")
  CATCH
    LET wsstatus = status
    CALL WSHelper.WSHelper_FillSOAP11WSError("Client","Cannot create HTTPRequest")
    RETURN wsstatus
  END TRY

  # START LOOP
  WHILE retry
    LET retry = FALSE

    #
    # Stax request
    #
    TRY
      LET writer = request.beginXmlRequest()
      CALL WSHelper.WSHelper_WriteStaxSOAP11StartEnvelope(writer)
      CALL WSHelper.WSHelper_WriteStaxSOAP11StartBody(writer)
      #
      # STAX SOAP REQUEST SERIALIZE
      #
      CALL xml.Serializer.VariableToStax(getPeriodosAsegurado,writer)
      CALL WSHelper.WSHelper_WriteStaxSOAP11EndBody(writer)
      CALL WSHelper.WSHelper_WriteStaxSOAP11EndEnvelope(writer)
      CALL request.endXmlRequest(writer)
    CATCH
      LET wsstatus = status
      CALL WSHelper.WSHelper_FillSOAP11WSError("Client",sqlca.sqlerrm)
      RETURN wsstatus
    END TRY

    #
    # PROCESS RESPONSE
    #
    TRY
      LET response = request.getResponse()

      #
      # RETRIEVE SERVICE SESSION COOKIE
      #
      LET setcookie = response.getHeader("Set-Cookie")
      IF setcookie IS NOT NULL THEN
        LET WSConsultaPeriodos_WSConsultaPeriodosPortEndpoint.Binding.Cookie = WSHelper.WSHelper_ExtractServerCookie(setcookie,WSConsultaPeriodos_WSConsultaPeriodosPortEndpoint.Address.Uri)
      END IF

      #
      # RETRIEVE HTTP RESPONSE Headers
      #
      CALL WSHelper.WSHelper_SetResponseHeaders(response, WSConsultaPeriodos_WSConsultaPeriodosPortEndpoint.Binding.Response.Headers)

      CASE
        WHEN response.getStatusCode()==200 OR response.getStatusCode()==500
          #
          # STAX SOAP RESPONSE OR FAULT
          #
          LET reader = response.beginXmlResponse() # Begin Streaming Response
          IF NOT WSHelper.WSHelper_ReadStaxSOAP11StartEnvelope(reader) THEN
            EXIT CASE
          END IF
          # Process SOAP headers 
          LET nb = 0
          IF WSHelper.WSHelper_CheckStaxSOAP11Header(reader) AND NOT reader.isEmptyElement() THEN
            CALL reader.nextTag()
            WHILE (reader.getEventType()=="START_ELEMENT")
              IF WSHelper.WSHelper_CheckStaxSOAP11HeaderActor(reader,uri) THEN
                LET mustUnderstand = WSHelper.WSHelper_GetStaxSOAP11HeaderMustUnderstand(reader)
                IF mustUnderstand = -1 THEN
                  CALL WSHelper.WSHelper_FillSOAP11WSError("Client","Invalid mustUnderstand value")
                  EXIT CASE
                END IF
                #
                # STAX SOAP RESPONSE HEADER DESERIALIZE
                #
                IF mustUnderstand THEN
                  CALL WSHelper.WSHelper_FillSOAP11WSError("MustUnderstand","Mandatory header block not understood")
                  EXIT CASE
                ELSE
                  CALL reader.nextSibling() # Skip header, not necessary
                END IF
              ELSE
                CALL reader.nextSibling() # Skip header, not intended to us
              END IF
            END WHILE
            IF NOT WSHelper.WSHelper_CheckStaxSOAP11Header(reader) THEN
              CALL WSHelper.WSHelper_FillSOAP11WSError("Client","No ending header tag found")
              EXIT CASE
            ELSE
              CALL reader.nextTag()
            END IF
          ELSE
            IF reader.isEmptyElement() THEN
              CALL reader.nextTag()
            END IF
          END IF
          IF NOT WSHelper.WSHelper_ReadStaxSOAP11StartBody(reader) THEN
            EXIT CASE
          END IF
          IF WSHelper.WSHelper_CheckStaxSOAP11StartFault(reader) THEN # Handle SOAP Fault
            LET fault = TRUE
            CALL reader.nextTag()
            IF NOT WSHelper.WSHelper_ReadStaxSOAP11FaultUntilDetail(reader) THEN
              EXIT CASE
            END IF
            IF WSHelper.WSHelper_CheckStaxSOAP11FaultDetail(reader) THEN
              #
              # STAX SOAP FAULT DESERIALIZE
              #
              CALL reader.nextSibling() # Skip SOAP detail
            END IF
            IF NOT WSHelper.WSHelper_ReadStaxSOAP11EndFault(reader) THEN
              EXIT CASE
            END IF
          ELSE # Handle SOAP Response
            IF nb != 0 THEN # Check mandatory headers
              CALL WSHelper.WSHelper_FillSOAP11WSError("Client","Headers are missing")
              EXIT CASE
            END IF
            IF NOT WSHelper.WSHelper_RetrieveStaxSOAP11Message(reader) THEN
              EXIT CASE
            END IF
            #
            # STAX SOAP RESPONSE DESERIALIZE
            #
            CALL xml.Serializer.StaxToVariable(reader,getPeriodosAseguradoResponse)
          END IF
          IF NOT WSHelper.WSHelper_ReadStaxSOAP11EndBody(reader) THEN
            EXIT CASE
          END IF
          IF NOT WSHelper.WSHelper_ReadStaxSOAP11EndEnvelope(reader) THEN
            EXIT CASE
          END IF
          # End Streaming Response
          CALL response.endXmlResponse(reader)
          IF NOT fault THEN
            LET wsstatus = 0
          END IF

        WHEN response.getStatusCode()==401 # HTTP Authentication
          IF retryAuth THEN
            CALL WSHelper.WSHelper_FillSOAP11WSError("Server","HTTP Error 401 ("||response.getStatusDescription()||")")
          ELSE
            LET retryAuth = TRUE
            LET retry = TRUE
          END IF

        WHEN response.getStatusCode()==407 # Proxy Authentication
          IF retryProxy THEN
            CALL WSHelper.WSHelper_FillSOAP11WSError("Server","HTTP Error 407 ("||response.getStatusDescription()||")")
          ELSE
            LET retryProxy = TRUE
            LET retry = TRUE
          END IF

        OTHERWISE
          CALL WSHelper.WSHelper_FillSOAP11WSError("Server","HTTP Error "||response.getStatusCode()||" ("||response.getStatusDescription()||")")

      END CASE
    CATCH
      LET wsstatus = status
      CALL WSHelper.WSHelper_FillSOAP11WSError("Server",sqlca.sqlerrm)
      RETURN wsstatus
    END TRY

  # END LOOP
  END WHILE

  RETURN wsstatus

END FUNCTION


FUNCTION getPeriodosAseguradoRequest_g()
  DEFINE wsstatus   INTEGER
  DEFINE writer     xml.StaxWriter

  #
  # CHECK PREVIOUS CALL  
  #
  IF getPeriodosAseguradoHTTPReq IS NOT NULL AND getPeriodosAseguradoHTTPResp IS NULL THEN
    # Request was sent but there was no response yet
    CALL WSHelper.WSHelper_FillSOAP11WSError("Client","Cannot issue a new request until previous response was received")
    RETURN -2 # waiting for the response
  ELSE
    #IF WSConsultaPeriodos_WSConsultaPeriodosPortEndpoint.Address.Uri IS NULL THEN
    #  LET WSConsultaPeriodos_WSConsultaPeriodosPortEndpoint.Address.Uri = "http://api.dev.issste.gob.mx:80/semanascotizadas-rest/WSConsultaPeriodos"
    #END IF
  END IF

  #
  # CREATE REQUEST
  #
  TRY
    LET getPeriodosAseguradoHTTPReq = com.HttpRequest.Create(WSConsultaPeriodos_WSConsultaPeriodosPortEndpoint.Address.Uri)
    CALL getPeriodosAseguradoHTTPReq.setMethod("POST")
    CALL getPeriodosAseguradoHTTPReq.setCharset("UTF-8")
    CALL getPeriodosAseguradoHTTPReq.setHeader("SOAPAction","\"\"")
    CALL WSHelper.WSHelper_SetRequestHeaders(getPeriodosAseguradoHTTPReq, WSConsultaPeriodos_WSConsultaPeriodosPortEndpoint.Binding.Request.Headers)
    IF WSConsultaPeriodos_WSConsultaPeriodosPortEndpoint.Binding.Version IS NOT NULL THEN
      CALL getPeriodosAseguradoHTTPReq.setVersion(WSConsultaPeriodos_WSConsultaPeriodosPortEndpoint.Binding.Version)
    END IF
    IF WSConsultaPeriodos_WSConsultaPeriodosPortEndpoint.Binding.Cookie IS NOT NULL THEN
      CALL getPeriodosAseguradoHTTPReq.setHeader("Cookie",WSConsultaPeriodos_WSConsultaPeriodosPortEndpoint.Binding.Cookie)
    END IF
    IF WSConsultaPeriodos_WSConsultaPeriodosPortEndpoint.Binding.ConnectionTimeout <> 0 THEN
      CALL getPeriodosAseguradoHTTPReq.setConnectionTimeOut(WSConsultaPeriodos_WSConsultaPeriodosPortEndpoint.Binding.ConnectionTimeout)
    END IF
    IF WSConsultaPeriodos_WSConsultaPeriodosPortEndpoint.Binding.ReadWriteTimeout <> 0 THEN
      CALL getPeriodosAseguradoHTTPReq.setTimeOut(WSConsultaPeriodos_WSConsultaPeriodosPortEndpoint.Binding.ReadWriteTimeout)
    END IF
    IF WSConsultaPeriodos_WSConsultaPeriodosPortEndpoint.Binding.CompressRequest IS NOT NULL THEN
      CALL getPeriodosAseguradoHTTPReq.setHeader("Content-Encoding",WSConsultaPeriodos_WSConsultaPeriodosPortEndpoint.Binding.CompressRequest)
    END IF
    CALL getPeriodosAseguradoHTTPReq.setHeader("Accept-Encoding","gzip, deflate")
  CATCH
    LET wsstatus = status
    CALL WSHelper.WSHelper_FillSOAP11WSError("Client","Cannot create HTTPRequest")
    LET getPeriodosAseguradoHTTPReq = NULL
    RETURN wsstatus
  END TRY

    #
    # Stax request
    #
    TRY
      LET writer = getPeriodosAseguradoHTTPReq.beginXmlRequest()
      CALL WSHelper.WSHelper_WriteStaxSOAP11StartEnvelope(writer)
      CALL WSHelper.WSHelper_WriteStaxSOAP11StartBody(writer)
      #
      # STAX SOAP REQUEST SERIALIZE
      #
      CALL xml.Serializer.VariableToStax(getPeriodosAsegurado,writer)
      CALL WSHelper.WSHelper_WriteStaxSOAP11EndBody(writer)
      CALL WSHelper.WSHelper_WriteStaxSOAP11EndEnvelope(writer)
      CALL getPeriodosAseguradoHTTPReq.endXmlRequest(writer)
    CATCH
      LET wsstatus = status
      CALL WSHelper.WSHelper_FillSOAP11WSError("Client",sqlca.sqlerrm)
      LET getPeriodosAseguradoHTTPReq = NULL
      RETURN wsstatus
    END TRY

  #
  # PROCESS RESPONSE
  #
  TRY
    LET getPeriodosAseguradoHTTPResp = getPeriodosAseguradoHTTPReq.getAsyncResponse()
    RETURN 0 # SUCCESS
  CATCH
    LET wsstatus = status
    CALL WSHelper.WSHelper_FillSOAP11WSError("Server",sqlca.sqlerrm)
    LET getPeriodosAseguradoHTTPReq = NULL
    RETURN wsstatus
  END TRY
END FUNCTION


FUNCTION getPeriodosAseguradoResponse_g()
  DEFINE wsstatus        INTEGER
  DEFINE fault           BOOLEAN
  DEFINE nb              INTEGER
  DEFINE uri             STRING
  DEFINE setcookie       STRING
  DEFINE mustUnderstand  INTEGER
  DEFINE reader          xml.StaxReader

  LET fault = FALSE
  LET wsstatus = -1

  LET uri = com.WebServiceEngine.GetOption("SoapModuleURI")
  #
  # CHECK PREVIOUS CALL  
  #
  IF getPeriodosAseguradoHTTPReq IS NULL THEN
    # No request was sent
    CALL WSHelper.WSHelper_FillSOAP11WSError("Client","No request has been sent")
    RETURN -1
  END IF

  TRY
    #
    # PROCESS RESPONSE
    #
    IF getPeriodosAseguradoHTTPResp IS NULL THEN
      # Still no response, try again
      LET getPeriodosAseguradoHTTPResp = getPeriodosAseguradoHTTPReq.getAsyncResponse()
    END IF

    IF getPeriodosAseguradoHTTPResp IS NULL THEN
      # We got no response, still waiting for
      CALL WSHelper.WSHelper_FillSOAP11WSError("Client","Response was not yet received")
      RETURN -2
    END IF

      #
      # RETRIEVE SERVICE SESSION COOKIE
      #
      LET setcookie = getPeriodosAseguradoHTTPResp.getHeader("Set-Cookie")
      IF setcookie IS NOT NULL THEN
        LET WSConsultaPeriodos_WSConsultaPeriodosPortEndpoint.Binding.Cookie = WSHelper.WSHelper_ExtractServerCookie(setcookie,WSConsultaPeriodos_WSConsultaPeriodosPortEndpoint.Address.Uri)
      END IF

      #
      # RETRIEVE HTTP RESPONSE Headers
      #
      CALL WSHelper.WSHelper_SetResponseHeaders(getPeriodosAseguradoHTTPResp, WSConsultaPeriodos_WSConsultaPeriodosPortEndpoint.Binding.Response.Headers)
      CASE
        WHEN getPeriodosAseguradoHTTPResp.getStatusCode()==200 OR getPeriodosAseguradoHTTPResp.getStatusCode()==500
          #
          # STAX SOAP RESPONSE OR FAULT
          #
          LET reader = getPeriodosAseguradoHTTPResp.beginXmlResponse() # Begin Streaming Response
          IF NOT WSHelper.WSHelper_ReadStaxSOAP11StartEnvelope(reader) THEN
            EXIT CASE
          END IF
          # Process SOAP headers 
          LET nb = 0
          IF WSHelper.WSHelper_CheckStaxSOAP11Header(reader) AND NOT reader.isEmptyElement() THEN
            CALL reader.nextTag()
            WHILE (reader.getEventType()=="START_ELEMENT")
              IF WSHelper.WSHelper_CheckStaxSOAP11HeaderActor(reader,uri) THEN
                LET mustUnderstand = WSHelper.WSHelper_GetStaxSOAP11HeaderMustUnderstand(reader)
                IF mustUnderstand = -1 THEN
                  CALL WSHelper.WSHelper_FillSOAP11WSError("Client","Invalid mustUnderstand value")
                  EXIT CASE
                END IF
                #
                # STAX SOAP RESPONSE HEADER DESERIALIZE
                #
                IF mustUnderstand THEN
                  CALL WSHelper.WSHelper_FillSOAP11WSError("MustUnderstand","Mandatory header block not understood")
                  EXIT CASE
                ELSE
                  CALL reader.nextSibling() # Skip header, not necessary
                END IF
              ELSE
                CALL reader.nextSibling() # Skip header, not intended to us
              END IF
            END WHILE
            IF NOT WSHelper.WSHelper_CheckStaxSOAP11Header(reader) THEN
              CALL WSHelper.WSHelper_FillSOAP11WSError("Client","No ending header tag found")
              EXIT CASE
            ELSE
              CALL reader.nextTag()
            END IF
          ELSE
            IF reader.isEmptyElement() THEN
              CALL reader.nextTag()
            END IF
          END IF
          IF NOT WSHelper.WSHelper_ReadStaxSOAP11StartBody(reader) THEN
            EXIT CASE
          END IF
          IF WSHelper.WSHelper_CheckStaxSOAP11StartFault(reader) THEN # Handle SOAP Fault
            LET fault = TRUE
            CALL reader.nextTag()
            IF NOT WSHelper.WSHelper_ReadStaxSOAP11FaultUntilDetail(reader) THEN
              EXIT CASE
            END IF
            IF WSHelper.WSHelper_CheckStaxSOAP11FaultDetail(reader) THEN
              #
              # STAX SOAP FAULT DESERIALIZE
              #
              CALL reader.nextSibling() # Skip SOAP detail
            END IF
            IF NOT WSHelper.WSHelper_ReadStaxSOAP11EndFault(reader) THEN
              EXIT CASE
            END IF
          ELSE # Handle SOAP Response
            IF nb != 0 THEN # Check mandatory headers
              CALL WSHelper.WSHelper_FillSOAP11WSError("Client","Headers are missing")
              EXIT CASE
            END IF
            IF NOT WSHelper.WSHelper_RetrieveStaxSOAP11Message(reader) THEN
              EXIT CASE
            END IF
            #
            # STAX SOAP RESPONSE DESERIALIZE
            #
            CALL xml.Serializer.StaxToVariable(reader,getPeriodosAseguradoResponse)
          END IF
          IF NOT WSHelper.WSHelper_ReadStaxSOAP11EndBody(reader) THEN
            EXIT CASE
          END IF
          IF NOT WSHelper.WSHelper_ReadStaxSOAP11EndEnvelope(reader) THEN
            EXIT CASE
          END IF
          # End Streaming Response
          CALL getPeriodosAseguradoHTTPResp.endXmlResponse(reader)
          IF NOT fault THEN
            LET wsstatus = 0
          END IF

        OTHERWISE
          CALL WSHelper.WSHelper_FillSOAP11WSError("Server","HTTP Error "||getPeriodosAseguradoHTTPResp.getStatusCode()||" ("||getPeriodosAseguradoHTTPResp.getStatusDescription()||")")

      END CASE
    CATCH
      LET wsstatus = status
      CALL WSHelper.WSHelper_FillSOAP11WSError("Server",sqlca.sqlerrm)
    END TRY

  #
  # RESET VARIABLES
  #
  LET getPeriodosAseguradoHTTPReq = NULL
  LET getPeriodosAseguradoHTTPResp = NULL
  RETURN wsstatus

END FUNCTION


