#-------------------------------------------------------------------------------
# File: clienteWS6AvisoEstatusTransferenciaIMSS.4gl
# GENERATED BY fglwsdl 202306221452
#-------------------------------------------------------------------------------
# THIS FILE WAS GENERATED. DO NOT MODIFY.
#-------------------------------------------------------------------------------


IMPORT FGL WSHelper
IMPORT com
IMPORT xml

#
#-------------------------------------------------------------------------------
# XML Type definitions 
#-------------------------------------------------------------------------------
#

#
# TYPE : tconcluirPortabilidad
#
PUBLIC TYPE tconcluirPortabilidad RECORD ATTRIBUTE(XMLSequence,XSTypeName="concluirPortabilidad",XSTypeNamespace="http://ws.soap.semanascotizadas.cit.imss.gob.mx/")
  institutoReceptor STRING ATTRIBUTE(XMLNamespace="",XMLOptional),
  nss STRING ATTRIBUTE(XMLNamespace="",XMLOptional),
  curp STRING ATTRIBUTE(XMLNamespace="",XMLOptional),
  folioTramiteReceptor STRING ATTRIBUTE(XMLNamespace="",XMLOptional),
  resultadoIntegracionPortabilidad INTEGER ATTRIBUTE(XMLNamespace="")
END RECORD
#-------------------------------------------------------------------------------

#
# TYPE : trespuestaWS
#
PUBLIC TYPE trespuestaWS RECORD ATTRIBUTE(XMLSequence,XSTypeName="respuestaWS",XSTypeNamespace="http://ws.soap.semanascotizadas.cit.imss.gob.mx/")
  claveError INTEGER ATTRIBUTE(XMLNamespace="",XMLOptional),
  mensajeError STRING ATTRIBUTE(XMLNamespace="",XMLOptional),
  codigoResultado STRING ATTRIBUTE(XMLNamespace="",XMLOptional,XMLNillable),
  motivoRechazo STRING ATTRIBUTE(XMLNamespace="",XMLOptional)
END RECORD
#-------------------------------------------------------------------------------

#
# TYPE : tconcluirPortabilidadResponse
#
PUBLIC TYPE tconcluirPortabilidadResponse RECORD ATTRIBUTE(XMLSequence,XSTypeName="concluirPortabilidadResponse",XSTypeNamespace="http://ws.soap.semanascotizadas.cit.imss.gob.mx/")
  resultado trespuestaWS ATTRIBUTE(XMLNamespace="",XMLOptional)
END RECORD
#-------------------------------------------------------------------------------



#-------------------------------------------------------------------------------
# Service: WSConclusionPortabilidad
# Port:    WSConclusionPortabilidadPort
# Server:  http://api.dev.issste.gob.mx:80/semanascotizadas-rest/WSConclusionPortabilidad
#-------------------------------------------------------------------------------
#
# Location of the SOAP endpoint.
# You can reassign this value at run-time.
#
PUBLIC DEFINE WSConclusionPortabilidad_WSConclusionPortabilidadPortEndpoint WSHelper.tGlobalEndpointType


#-------------------------------------------------------------------------------

# VARIABLE : concluirPortabilidad
PUBLIC DEFINE concluirPortabilidad tconcluirPortabilidad ATTRIBUTE(XMLName="concluirPortabilidad",XMLNamespace="http://ws.soap.semanascotizadas.cit.imss.gob.mx/")


#-------------------------------------------------------------------------------

# VARIABLE : concluirPortabilidadResponse
PUBLIC DEFINE concluirPortabilidadResponse tconcluirPortabilidadResponse ATTRIBUTE(XMLName="concluirPortabilidadResponse",XMLNamespace="http://ws.soap.semanascotizadas.cit.imss.gob.mx/")



# end of service types
#-------------------------------------------------------------------------------

# Start service implementation
#-------------------------------------------------------------------------------
# Service: WSConclusionPortabilidad
# Port:    WSConclusionPortabilidadPort
# Server:  http://api.dev.issste.gob.mx:80/semanascotizadas-rest/WSConclusionPortabilidad
#-------------------------------------------------------------------------------

PRIVATE DEFINE concluirPortabilidadHTTPReq     com.HttpRequest
PRIVATE DEFINE concluirPortabilidadHTTPResp    com.HttpResponse

#-------------------------------------------------------------------------------

#
# Operation: concluirPortabilidad
#
#
# FUNCTION: concluirPortabilidad_g
#   RETURNING: soapStatus
#   INPUT:  concluirPortabilidad
#   OUTPUT:  concluirPortabilidadResponse
#
FUNCTION concluirPortabilidad_g()
  DEFINE wsstatus   INTEGER
  DEFINE retryAuth  INTEGER
  DEFINE retryProxy INTEGER
  DEFINE retry      INTEGER
  DEFINE fault      BOOLEAN
  DEFINE nb         INTEGER
  DEFINE uri        STRING
  DEFINE setcookie  STRING
  DEFINE mustUnderstand INTEGER
  DEFINE request    com.HttpRequest
  DEFINE response   com.HttpResponse
  DEFINE writer     xml.StaxWriter
  DEFINE reader     xml.StaxReader

  #
  # INIT VARIABLES
  #
  LET wsstatus = -1
  LET retryAuth = FALSE
  LET retryProxy = FALSE
  LET retry = TRUE
  LET fault = FALSE
  LET uri = com.WebServiceEngine.GetOption("SoapModuleURI")

  #IF WSConclusionPortabilidad_WSConclusionPortabilidadPortEndpoint.Address.Uri IS NULL THEN
  #  LET WSConclusionPortabilidad_WSConclusionPortabilidadPortEndpoint.Address.Uri = "http://api.dev.issste.gob.mx:80/semanascotizadas-rest/WSConclusionPortabilidad"
  #END IF

  #
  # CREATE REQUEST
  #
  TRY
    LET request = com.HttpRequest.Create(WSConclusionPortabilidad_WSConclusionPortabilidadPortEndpoint.Address.Uri)
    CALL request.setMethod("POST")
    CALL request.setCharset("UTF-8")
    CALL request.setHeader("SOAPAction","\"\"")
    CALL WSHelper.WSHelper_SetRequestHeaders(request, WSConclusionPortabilidad_WSConclusionPortabilidadPortEndpoint.Binding.Request.Headers)
    IF WSConclusionPortabilidad_WSConclusionPortabilidadPortEndpoint.Binding.Version IS NOT NULL THEN
      CALL request.setVersion(WSConclusionPortabilidad_WSConclusionPortabilidadPortEndpoint.Binding.Version)
    END IF
    IF WSConclusionPortabilidad_WSConclusionPortabilidadPortEndpoint.Binding.Cookie IS NOT NULL THEN
      CALL request.setHeader("Cookie",WSConclusionPortabilidad_WSConclusionPortabilidadPortEndpoint.Binding.Cookie)
    END IF
    IF WSConclusionPortabilidad_WSConclusionPortabilidadPortEndpoint.Binding.ConnectionTimeout <> 0 THEN
      CALL request.setConnectionTimeOut(WSConclusionPortabilidad_WSConclusionPortabilidadPortEndpoint.Binding.ConnectionTimeout)
    END IF
    IF WSConclusionPortabilidad_WSConclusionPortabilidadPortEndpoint.Binding.ReadWriteTimeout <> 0 THEN
      CALL request.setTimeOut(WSConclusionPortabilidad_WSConclusionPortabilidadPortEndpoint.Binding.ReadWriteTimeout)
    END IF
    IF WSConclusionPortabilidad_WSConclusionPortabilidadPortEndpoint.Binding.CompressRequest IS NOT NULL THEN
      CALL request.setHeader("Content-Encoding",WSConclusionPortabilidad_WSConclusionPortabilidadPortEndpoint.Binding.CompressRequest)
    END IF
    CALL request.setHeader("Accept-Encoding","gzip, deflate")
  CATCH
    LET wsstatus = status
    CALL WSHelper.WSHelper_FillSOAP11WSError("Client","Cannot create HTTPRequest")
    RETURN wsstatus
  END TRY

  # START LOOP
  WHILE retry
    LET retry = FALSE

    #
    # Stax request
    #
    TRY
      LET writer = request.beginXmlRequest()
      CALL WSHelper.WSHelper_WriteStaxSOAP11StartEnvelope(writer)
      CALL WSHelper.WSHelper_WriteStaxSOAP11StartBody(writer)
      #
      # STAX SOAP REQUEST SERIALIZE
      #
      CALL xml.Serializer.VariableToStax(concluirPortabilidad,writer)
      CALL WSHelper.WSHelper_WriteStaxSOAP11EndBody(writer)
      CALL WSHelper.WSHelper_WriteStaxSOAP11EndEnvelope(writer)
      CALL request.endXmlRequest(writer)
    CATCH
      LET wsstatus = status
      CALL WSHelper.WSHelper_FillSOAP11WSError("Client",sqlca.sqlerrm)
      RETURN wsstatus
    END TRY

    #
    # PROCESS RESPONSE
    #
    TRY
      LET response = request.getResponse()

      #
      # RETRIEVE SERVICE SESSION COOKIE
      #
      LET setcookie = response.getHeader("Set-Cookie")
      IF setcookie IS NOT NULL THEN
        LET WSConclusionPortabilidad_WSConclusionPortabilidadPortEndpoint.Binding.Cookie = WSHelper.WSHelper_ExtractServerCookie(setcookie,WSConclusionPortabilidad_WSConclusionPortabilidadPortEndpoint.Address.Uri)
      END IF

      #
      # RETRIEVE HTTP RESPONSE Headers
      #
      CALL WSHelper.WSHelper_SetResponseHeaders(response, WSConclusionPortabilidad_WSConclusionPortabilidadPortEndpoint.Binding.Response.Headers)

      CASE
        WHEN response.getStatusCode()==200 OR response.getStatusCode()==500
          #
          # STAX SOAP RESPONSE OR FAULT
          #
          LET reader = response.beginXmlResponse() # Begin Streaming Response
          IF NOT WSHelper.WSHelper_ReadStaxSOAP11StartEnvelope(reader) THEN
            EXIT CASE
          END IF
          # Process SOAP headers 
          LET nb = 0
          IF WSHelper.WSHelper_CheckStaxSOAP11Header(reader) AND NOT reader.isEmptyElement() THEN
            CALL reader.nextTag()
            WHILE (reader.getEventType()=="START_ELEMENT")
              IF WSHelper.WSHelper_CheckStaxSOAP11HeaderActor(reader,uri) THEN
                LET mustUnderstand = WSHelper.WSHelper_GetStaxSOAP11HeaderMustUnderstand(reader)
                IF mustUnderstand = -1 THEN
                  CALL WSHelper.WSHelper_FillSOAP11WSError("Client","Invalid mustUnderstand value")
                  EXIT CASE
                END IF
                #
                # STAX SOAP RESPONSE HEADER DESERIALIZE
                #
                IF mustUnderstand THEN
                  CALL WSHelper.WSHelper_FillSOAP11WSError("MustUnderstand","Mandatory header block not understood")
                  EXIT CASE
                ELSE
                  CALL reader.nextSibling() # Skip header, not necessary
                END IF
              ELSE
                CALL reader.nextSibling() # Skip header, not intended to us
              END IF
            END WHILE
            IF NOT WSHelper.WSHelper_CheckStaxSOAP11Header(reader) THEN
              CALL WSHelper.WSHelper_FillSOAP11WSError("Client","No ending header tag found")
              EXIT CASE
            ELSE
              CALL reader.nextTag()
            END IF
          ELSE
            IF reader.isEmptyElement() THEN
              CALL reader.nextTag()
            END IF
          END IF
          IF NOT WSHelper.WSHelper_ReadStaxSOAP11StartBody(reader) THEN
            EXIT CASE
          END IF
          IF WSHelper.WSHelper_CheckStaxSOAP11StartFault(reader) THEN # Handle SOAP Fault
            LET fault = TRUE
            CALL reader.nextTag()
            IF NOT WSHelper.WSHelper_ReadStaxSOAP11FaultUntilDetail(reader) THEN
              EXIT CASE
            END IF
            IF WSHelper.WSHelper_CheckStaxSOAP11FaultDetail(reader) THEN
              #
              # STAX SOAP FAULT DESERIALIZE
              #
              CALL reader.nextSibling() # Skip SOAP detail
            END IF
            IF NOT WSHelper.WSHelper_ReadStaxSOAP11EndFault(reader) THEN
              EXIT CASE
            END IF
          ELSE # Handle SOAP Response
            IF nb != 0 THEN # Check mandatory headers
              CALL WSHelper.WSHelper_FillSOAP11WSError("Client","Headers are missing")
              EXIT CASE
            END IF
            IF NOT WSHelper.WSHelper_RetrieveStaxSOAP11Message(reader) THEN
              EXIT CASE
            END IF
            #
            # STAX SOAP RESPONSE DESERIALIZE
            #
            CALL xml.Serializer.StaxToVariable(reader,concluirPortabilidadResponse)
          END IF
          IF NOT WSHelper.WSHelper_ReadStaxSOAP11EndBody(reader) THEN
            EXIT CASE
          END IF
          IF NOT WSHelper.WSHelper_ReadStaxSOAP11EndEnvelope(reader) THEN
            EXIT CASE
          END IF
          # End Streaming Response
          CALL response.endXmlResponse(reader)
          IF NOT fault THEN
            LET wsstatus = 0
          END IF

        WHEN response.getStatusCode()==401 # HTTP Authentication
          IF retryAuth THEN
            CALL WSHelper.WSHelper_FillSOAP11WSError("Server","HTTP Error 401 ("||response.getStatusDescription()||")")
          ELSE
            LET retryAuth = TRUE
            LET retry = TRUE
          END IF

        WHEN response.getStatusCode()==407 # Proxy Authentication
          IF retryProxy THEN
            CALL WSHelper.WSHelper_FillSOAP11WSError("Server","HTTP Error 407 ("||response.getStatusDescription()||")")
          ELSE
            LET retryProxy = TRUE
            LET retry = TRUE
          END IF

        OTHERWISE
          CALL WSHelper.WSHelper_FillSOAP11WSError("Server","HTTP Error "||response.getStatusCode()||" ("||response.getStatusDescription()||")")

      END CASE
    CATCH
      LET wsstatus = status
      CALL WSHelper.WSHelper_FillSOAP11WSError("Server",sqlca.sqlerrm)
      RETURN wsstatus
    END TRY

  # END LOOP
  END WHILE

  RETURN wsstatus

END FUNCTION


FUNCTION concluirPortabilidadRequest_g()
  DEFINE wsstatus   INTEGER
  DEFINE writer     xml.StaxWriter

  #
  # CHECK PREVIOUS CALL  
  #
  IF concluirPortabilidadHTTPReq IS NOT NULL AND concluirPortabilidadHTTPResp IS NULL THEN
    # Request was sent but there was no response yet
    CALL WSHelper.WSHelper_FillSOAP11WSError("Client","Cannot issue a new request until previous response was received")
    RETURN -2 # waiting for the response
  ELSE
    #IF WSConclusionPortabilidad_WSConclusionPortabilidadPortEndpoint.Address.Uri IS NULL THEN
    #  LET WSConclusionPortabilidad_WSConclusionPortabilidadPortEndpoint.Address.Uri = "http://api.dev.issste.gob.mx:80/semanascotizadas-rest/WSConclusionPortabilidad"
    #END IF
  END IF

  #
  # CREATE REQUEST
  #
  TRY
    LET concluirPortabilidadHTTPReq = com.HttpRequest.Create(WSConclusionPortabilidad_WSConclusionPortabilidadPortEndpoint.Address.Uri)
    CALL concluirPortabilidadHTTPReq.setMethod("POST")
    CALL concluirPortabilidadHTTPReq.setCharset("UTF-8")
    CALL concluirPortabilidadHTTPReq.setHeader("SOAPAction","\"\"")
    CALL WSHelper.WSHelper_SetRequestHeaders(concluirPortabilidadHTTPReq, WSConclusionPortabilidad_WSConclusionPortabilidadPortEndpoint.Binding.Request.Headers)
    IF WSConclusionPortabilidad_WSConclusionPortabilidadPortEndpoint.Binding.Version IS NOT NULL THEN
      CALL concluirPortabilidadHTTPReq.setVersion(WSConclusionPortabilidad_WSConclusionPortabilidadPortEndpoint.Binding.Version)
    END IF
    IF WSConclusionPortabilidad_WSConclusionPortabilidadPortEndpoint.Binding.Cookie IS NOT NULL THEN
      CALL concluirPortabilidadHTTPReq.setHeader("Cookie",WSConclusionPortabilidad_WSConclusionPortabilidadPortEndpoint.Binding.Cookie)
    END IF
    IF WSConclusionPortabilidad_WSConclusionPortabilidadPortEndpoint.Binding.ConnectionTimeout <> 0 THEN
      CALL concluirPortabilidadHTTPReq.setConnectionTimeOut(WSConclusionPortabilidad_WSConclusionPortabilidadPortEndpoint.Binding.ConnectionTimeout)
    END IF
    IF WSConclusionPortabilidad_WSConclusionPortabilidadPortEndpoint.Binding.ReadWriteTimeout <> 0 THEN
      CALL concluirPortabilidadHTTPReq.setTimeOut(WSConclusionPortabilidad_WSConclusionPortabilidadPortEndpoint.Binding.ReadWriteTimeout)
    END IF
    IF WSConclusionPortabilidad_WSConclusionPortabilidadPortEndpoint.Binding.CompressRequest IS NOT NULL THEN
      CALL concluirPortabilidadHTTPReq.setHeader("Content-Encoding",WSConclusionPortabilidad_WSConclusionPortabilidadPortEndpoint.Binding.CompressRequest)
    END IF
    CALL concluirPortabilidadHTTPReq.setHeader("Accept-Encoding","gzip, deflate")
  CATCH
    LET wsstatus = status
    CALL WSHelper.WSHelper_FillSOAP11WSError("Client","Cannot create HTTPRequest")
    LET concluirPortabilidadHTTPReq = NULL
    RETURN wsstatus
  END TRY

    #
    # Stax request
    #
    TRY
      LET writer = concluirPortabilidadHTTPReq.beginXmlRequest()
      CALL WSHelper.WSHelper_WriteStaxSOAP11StartEnvelope(writer)
      CALL WSHelper.WSHelper_WriteStaxSOAP11StartBody(writer)
      #
      # STAX SOAP REQUEST SERIALIZE
      #
      CALL xml.Serializer.VariableToStax(concluirPortabilidad,writer)
      CALL WSHelper.WSHelper_WriteStaxSOAP11EndBody(writer)
      CALL WSHelper.WSHelper_WriteStaxSOAP11EndEnvelope(writer)
      CALL concluirPortabilidadHTTPReq.endXmlRequest(writer)
    CATCH
      LET wsstatus = status
      CALL WSHelper.WSHelper_FillSOAP11WSError("Client",sqlca.sqlerrm)
      LET concluirPortabilidadHTTPReq = NULL
      RETURN wsstatus
    END TRY

  #
  # PROCESS RESPONSE
  #
  TRY
    LET concluirPortabilidadHTTPResp = concluirPortabilidadHTTPReq.getAsyncResponse()
    RETURN 0 # SUCCESS
  CATCH
    LET wsstatus = status
    CALL WSHelper.WSHelper_FillSOAP11WSError("Server",sqlca.sqlerrm)
    LET concluirPortabilidadHTTPReq = NULL
    RETURN wsstatus
  END TRY
END FUNCTION


FUNCTION concluirPortabilidadResponse_g()
  DEFINE wsstatus        INTEGER
  DEFINE fault           BOOLEAN
  DEFINE nb              INTEGER
  DEFINE uri             STRING
  DEFINE setcookie       STRING
  DEFINE mustUnderstand  INTEGER
  DEFINE reader          xml.StaxReader

  LET fault = FALSE
  LET wsstatus = -1

  LET uri = com.WebServiceEngine.GetOption("SoapModuleURI")
  #
  # CHECK PREVIOUS CALL  
  #
  IF concluirPortabilidadHTTPReq IS NULL THEN
    # No request was sent
    CALL WSHelper.WSHelper_FillSOAP11WSError("Client","No request has been sent")
    RETURN -1
  END IF

  TRY
    #
    # PROCESS RESPONSE
    #
    IF concluirPortabilidadHTTPResp IS NULL THEN
      # Still no response, try again
      LET concluirPortabilidadHTTPResp = concluirPortabilidadHTTPReq.getAsyncResponse()
    END IF

    IF concluirPortabilidadHTTPResp IS NULL THEN
      # We got no response, still waiting for
      CALL WSHelper.WSHelper_FillSOAP11WSError("Client","Response was not yet received")
      RETURN -2
    END IF

      #
      # RETRIEVE SERVICE SESSION COOKIE
      #
      LET setcookie = concluirPortabilidadHTTPResp.getHeader("Set-Cookie")
      IF setcookie IS NOT NULL THEN
        LET WSConclusionPortabilidad_WSConclusionPortabilidadPortEndpoint.Binding.Cookie = WSHelper.WSHelper_ExtractServerCookie(setcookie,WSConclusionPortabilidad_WSConclusionPortabilidadPortEndpoint.Address.Uri)
      END IF

      #
      # RETRIEVE HTTP RESPONSE Headers
      #
      CALL WSHelper.WSHelper_SetResponseHeaders(concluirPortabilidadHTTPResp, WSConclusionPortabilidad_WSConclusionPortabilidadPortEndpoint.Binding.Response.Headers)
      CASE
        WHEN concluirPortabilidadHTTPResp.getStatusCode()==200 OR concluirPortabilidadHTTPResp.getStatusCode()==500
          #
          # STAX SOAP RESPONSE OR FAULT
          #
          LET reader = concluirPortabilidadHTTPResp.beginXmlResponse() # Begin Streaming Response
          IF NOT WSHelper.WSHelper_ReadStaxSOAP11StartEnvelope(reader) THEN
            EXIT CASE
          END IF
          # Process SOAP headers 
          LET nb = 0
          IF WSHelper.WSHelper_CheckStaxSOAP11Header(reader) AND NOT reader.isEmptyElement() THEN
            CALL reader.nextTag()
            WHILE (reader.getEventType()=="START_ELEMENT")
              IF WSHelper.WSHelper_CheckStaxSOAP11HeaderActor(reader,uri) THEN
                LET mustUnderstand = WSHelper.WSHelper_GetStaxSOAP11HeaderMustUnderstand(reader)
                IF mustUnderstand = -1 THEN
                  CALL WSHelper.WSHelper_FillSOAP11WSError("Client","Invalid mustUnderstand value")
                  EXIT CASE
                END IF
                #
                # STAX SOAP RESPONSE HEADER DESERIALIZE
                #
                IF mustUnderstand THEN
                  CALL WSHelper.WSHelper_FillSOAP11WSError("MustUnderstand","Mandatory header block not understood")
                  EXIT CASE
                ELSE
                  CALL reader.nextSibling() # Skip header, not necessary
                END IF
              ELSE
                CALL reader.nextSibling() # Skip header, not intended to us
              END IF
            END WHILE
            IF NOT WSHelper.WSHelper_CheckStaxSOAP11Header(reader) THEN
              CALL WSHelper.WSHelper_FillSOAP11WSError("Client","No ending header tag found")
              EXIT CASE
            ELSE
              CALL reader.nextTag()
            END IF
          ELSE
            IF reader.isEmptyElement() THEN
              CALL reader.nextTag()
            END IF
          END IF
          IF NOT WSHelper.WSHelper_ReadStaxSOAP11StartBody(reader) THEN
            EXIT CASE
          END IF
          IF WSHelper.WSHelper_CheckStaxSOAP11StartFault(reader) THEN # Handle SOAP Fault
            LET fault = TRUE
            CALL reader.nextTag()
            IF NOT WSHelper.WSHelper_ReadStaxSOAP11FaultUntilDetail(reader) THEN
              EXIT CASE
            END IF
            IF WSHelper.WSHelper_CheckStaxSOAP11FaultDetail(reader) THEN
              #
              # STAX SOAP FAULT DESERIALIZE
              #
              CALL reader.nextSibling() # Skip SOAP detail
            END IF
            IF NOT WSHelper.WSHelper_ReadStaxSOAP11EndFault(reader) THEN
              EXIT CASE
            END IF
          ELSE # Handle SOAP Response
            IF nb != 0 THEN # Check mandatory headers
              CALL WSHelper.WSHelper_FillSOAP11WSError("Client","Headers are missing")
              EXIT CASE
            END IF
            IF NOT WSHelper.WSHelper_RetrieveStaxSOAP11Message(reader) THEN
              EXIT CASE
            END IF
            #
            # STAX SOAP RESPONSE DESERIALIZE
            #
            CALL xml.Serializer.StaxToVariable(reader,concluirPortabilidadResponse)
          END IF
          IF NOT WSHelper.WSHelper_ReadStaxSOAP11EndBody(reader) THEN
            EXIT CASE
          END IF
          IF NOT WSHelper.WSHelper_ReadStaxSOAP11EndEnvelope(reader) THEN
            EXIT CASE
          END IF
          # End Streaming Response
          CALL concluirPortabilidadHTTPResp.endXmlResponse(reader)
          IF NOT fault THEN
            LET wsstatus = 0
          END IF

        OTHERWISE
          CALL WSHelper.WSHelper_FillSOAP11WSError("Server","HTTP Error "||concluirPortabilidadHTTPResp.getStatusCode()||" ("||concluirPortabilidadHTTPResp.getStatusDescription()||")")

      END CASE
    CATCH
      LET wsstatus = status
      CALL WSHelper.WSHelper_FillSOAP11WSError("Server",sqlca.sqlerrm)
    END TRY

  #
  # RESET VARIABLES
  #
  LET concluirPortabilidadHTTPReq = NULL
  LET concluirPortabilidadHTTPResp = NULL
  RETURN wsstatus

END FUNCTION


