#-------------------------------------------------------------------------------
# File: clienteWS1ConsultaBasicaIMSS.4gl
# GENERATED BY fglwsdl 202306221452
#-------------------------------------------------------------------------------
# THIS FILE WAS GENERATED. DO NOT MODIFY.
#-------------------------------------------------------------------------------


IMPORT FGL WSHelper
IMPORT com
IMPORT xml

#
#-------------------------------------------------------------------------------
# XML Type definitions 
#-------------------------------------------------------------------------------
#

#
# TYPE : tgetEstatusAsegurado
#
PUBLIC TYPE tgetEstatusAsegurado RECORD ATTRIBUTE(XMLSequence,XSTypeName="getEstatusAsegurado",XSTypeNamespace="http://ws.soap.semanascotizadas.cit.imss.gob.mx/")
  institutoReceptor STRING ATTRIBUTE(XMLNamespace="",XMLOptional),
  nss STRING ATTRIBUTE(XMLNamespace="",XMLOptional),
  curp STRING ATTRIBUTE(XMLNamespace="",XMLOptional),
  fechaTramite STRING ATTRIBUTE(XMLNamespace="",XMLOptional),
  correo STRING ATTRIBUTE(XMLNamespace="",XMLOptional)
END RECORD
#-------------------------------------------------------------------------------

#
# TYPE : tRespuestaEstatusAsegurado
#
PUBLIC TYPE tRespuestaEstatusAsegurado RECORD ATTRIBUTE(XMLSequence,XSTypeName="RespuestaEstatusAsegurado",XSTypeNamespace="http://ws.soap.semanascotizadas.cit.imss.gob.mx/")
  claveError INTEGER ATTRIBUTE(XMLNamespace="",XMLOptional),
  mensajeError STRING ATTRIBUTE(XMLNamespace="",XMLOptional),
  codigoResultado STRING ATTRIBUTE(XMLNamespace="",XMLOptional,XMLNillable),
  motivoRechazo STRING ATTRIBUTE(XMLNamespace="",XMLOptional),
  curp STRING ATTRIBUTE(XMLNamespace="",XMLOptional),
  primerApellido STRING ATTRIBUTE(XMLNamespace="",XMLOptional),
  segundoApellido STRING ATTRIBUTE(XMLNamespace="",XMLOptional),
  nombre STRING ATTRIBUTE(XMLNamespace="",XMLOptional),
  nss STRING ATTRIBUTE(XMLNamespace="",XMLOptional),
  fechaDeBaja STRING ATTRIBUTE(XMLNamespace="",XMLOptional),
  observaciones STRING ATTRIBUTE(XMLNamespace="",XMLOptional)
END RECORD
#-------------------------------------------------------------------------------

#
# TYPE : tgetEstatusAseguradoResponse
#
PUBLIC TYPE tgetEstatusAseguradoResponse RECORD ATTRIBUTE(XMLSequence,XSTypeName="getEstatusAseguradoResponse",XSTypeNamespace="http://ws.soap.semanascotizadas.cit.imss.gob.mx/")
  return tRespuestaEstatusAsegurado ATTRIBUTE(XMLNamespace="",XMLOptional)
END RECORD
#-------------------------------------------------------------------------------



#-------------------------------------------------------------------------------
# Service: WSEstatusAsegurado
# Port:    WSEstatusAseguradoPort
# Server:  http://api.dev.issste.gob.mx:80/semanascotizadas-rest/WSEstatusAsegurado
#-------------------------------------------------------------------------------
#
# Location of the SOAP endpoint.
# You can reassign this value at run-time.
#
PUBLIC DEFINE WSEstatusAsegurado_WSEstatusAseguradoPortEndpoint WSHelper.tGlobalEndpointType


#-------------------------------------------------------------------------------

# VARIABLE : getEstatusAsegurado
PUBLIC DEFINE getEstatusAsegurado tgetEstatusAsegurado ATTRIBUTE(XMLName="getEstatusAsegurado",XMLNamespace="http://ws.soap.semanascotizadas.cit.imss.gob.mx/")


#-------------------------------------------------------------------------------

# VARIABLE : getEstatusAseguradoResponse
PUBLIC DEFINE getEstatusAseguradoResponse tgetEstatusAseguradoResponse ATTRIBUTE(XMLName="getEstatusAseguradoResponse",XMLNamespace="http://ws.soap.semanascotizadas.cit.imss.gob.mx/")



# end of service types
#-------------------------------------------------------------------------------

# Start service implementation
#-------------------------------------------------------------------------------
# Service: WSEstatusAsegurado
# Port:    WSEstatusAseguradoPort
# Server:  http://api.dev.issste.gob.mx:80/semanascotizadas-rest/WSEstatusAsegurado
#-------------------------------------------------------------------------------

PRIVATE DEFINE getEstatusAseguradoHTTPReq     com.HttpRequest
PRIVATE DEFINE getEstatusAseguradoHTTPResp    com.HttpResponse

#-------------------------------------------------------------------------------

#
# Operation: getEstatusAsegurado
#
#
# FUNCTION: getEstatusAsegurado_g
#   RETURNING: soapStatus
#   INPUT:  getEstatusAsegurado
#   OUTPUT:  getEstatusAseguradoResponse
#
FUNCTION getEstatusAsegurado_g()
  DEFINE wsstatus   INTEGER
  DEFINE retryAuth  INTEGER
  DEFINE retryProxy INTEGER
  DEFINE retry      INTEGER
  DEFINE fault      BOOLEAN
  DEFINE nb         INTEGER
  DEFINE uri        STRING
  DEFINE setcookie  STRING
  DEFINE mustUnderstand INTEGER
  DEFINE request    com.HttpRequest
  DEFINE response   com.HttpResponse
  DEFINE writer     xml.StaxWriter
  DEFINE reader     xml.StaxReader

  #
  # INIT VARIABLES
  #
  LET wsstatus = -1
  LET retryAuth = FALSE
  LET retryProxy = FALSE
  LET retry = TRUE
  LET fault = FALSE
  LET uri = com.WebServiceEngine.GetOption("SoapModuleURI")

  #IF WSEstatusAsegurado_WSEstatusAseguradoPortEndpoint.Address.Uri IS NULL THEN
  #  LET WSEstatusAsegurado_WSEstatusAseguradoPortEndpoint.Address.Uri = "http://api.dev.issste.gob.mx:80/semanascotizadas-rest/WSEstatusAsegurado"
  #END IF

  #
  # CREATE REQUEST
  #
  TRY
    LET request = com.HttpRequest.Create(WSEstatusAsegurado_WSEstatusAseguradoPortEndpoint.Address.Uri)
    CALL request.setMethod("POST")
    CALL request.setCharset("UTF-8")
    CALL request.setHeader("SOAPAction","\"\"")
    CALL WSHelper.WSHelper_SetRequestHeaders(request, WSEstatusAsegurado_WSEstatusAseguradoPortEndpoint.Binding.Request.Headers)
    IF WSEstatusAsegurado_WSEstatusAseguradoPortEndpoint.Binding.Version IS NOT NULL THEN
      CALL request.setVersion(WSEstatusAsegurado_WSEstatusAseguradoPortEndpoint.Binding.Version)
    END IF
    IF WSEstatusAsegurado_WSEstatusAseguradoPortEndpoint.Binding.Cookie IS NOT NULL THEN
      CALL request.setHeader("Cookie",WSEstatusAsegurado_WSEstatusAseguradoPortEndpoint.Binding.Cookie)
    END IF
    IF WSEstatusAsegurado_WSEstatusAseguradoPortEndpoint.Binding.ConnectionTimeout <> 0 THEN
      CALL request.setConnectionTimeOut(WSEstatusAsegurado_WSEstatusAseguradoPortEndpoint.Binding.ConnectionTimeout)
    END IF
    IF WSEstatusAsegurado_WSEstatusAseguradoPortEndpoint.Binding.ReadWriteTimeout <> 0 THEN
      CALL request.setTimeOut(WSEstatusAsegurado_WSEstatusAseguradoPortEndpoint.Binding.ReadWriteTimeout)
    END IF
    IF WSEstatusAsegurado_WSEstatusAseguradoPortEndpoint.Binding.CompressRequest IS NOT NULL THEN
      CALL request.setHeader("Content-Encoding",WSEstatusAsegurado_WSEstatusAseguradoPortEndpoint.Binding.CompressRequest)
    END IF
    CALL request.setHeader("Accept-Encoding","gzip, deflate")
  CATCH
    LET wsstatus = status
    CALL WSHelper.WSHelper_FillSOAP11WSError("Client","Cannot create HTTPRequest")
    RETURN wsstatus
  END TRY

  # START LOOP
  WHILE retry
    LET retry = FALSE

    #
    # Stax request
    #
    TRY
      LET writer = request.beginXmlRequest()
      CALL WSHelper.WSHelper_WriteStaxSOAP11StartEnvelope(writer)
      CALL WSHelper.WSHelper_WriteStaxSOAP11StartBody(writer)
      #
      # STAX SOAP REQUEST SERIALIZE
      #
      CALL xml.Serializer.VariableToStax(getEstatusAsegurado,writer)
      CALL WSHelper.WSHelper_WriteStaxSOAP11EndBody(writer)
      CALL WSHelper.WSHelper_WriteStaxSOAP11EndEnvelope(writer)
      CALL request.endXmlRequest(writer)
    CATCH
      LET wsstatus = status
      CALL WSHelper.WSHelper_FillSOAP11WSError("Client",sqlca.sqlerrm)
      RETURN wsstatus
    END TRY

    #
    # PROCESS RESPONSE
    #
    TRY
      LET response = request.getResponse()

      #
      # RETRIEVE SERVICE SESSION COOKIE
      #
      LET setcookie = response.getHeader("Set-Cookie")
      IF setcookie IS NOT NULL THEN
        LET WSEstatusAsegurado_WSEstatusAseguradoPortEndpoint.Binding.Cookie = WSHelper.WSHelper_ExtractServerCookie(setcookie,WSEstatusAsegurado_WSEstatusAseguradoPortEndpoint.Address.Uri)
      END IF

      #
      # RETRIEVE HTTP RESPONSE Headers
      #
      CALL WSHelper.WSHelper_SetResponseHeaders(response, WSEstatusAsegurado_WSEstatusAseguradoPortEndpoint.Binding.Response.Headers)

      CASE
        WHEN response.getStatusCode()==200 OR response.getStatusCode()==500
          #
          # STAX SOAP RESPONSE OR FAULT
          #
          LET reader = response.beginXmlResponse() # Begin Streaming Response
          IF NOT WSHelper.WSHelper_ReadStaxSOAP11StartEnvelope(reader) THEN
            EXIT CASE
          END IF
          # Process SOAP headers 
          LET nb = 0
          IF WSHelper.WSHelper_CheckStaxSOAP11Header(reader) AND NOT reader.isEmptyElement() THEN
            CALL reader.nextTag()
            WHILE (reader.getEventType()=="START_ELEMENT")
              IF WSHelper.WSHelper_CheckStaxSOAP11HeaderActor(reader,uri) THEN
                LET mustUnderstand = WSHelper.WSHelper_GetStaxSOAP11HeaderMustUnderstand(reader)
                IF mustUnderstand = -1 THEN
                  CALL WSHelper.WSHelper_FillSOAP11WSError("Client","Invalid mustUnderstand value")
                  EXIT CASE
                END IF
                #
                # STAX SOAP RESPONSE HEADER DESERIALIZE
                #
                IF mustUnderstand THEN
                  CALL WSHelper.WSHelper_FillSOAP11WSError("MustUnderstand","Mandatory header block not understood")
                  EXIT CASE
                ELSE
                  CALL reader.nextSibling() # Skip header, not necessary
                END IF
              ELSE
                CALL reader.nextSibling() # Skip header, not intended to us
              END IF
            END WHILE
            IF NOT WSHelper.WSHelper_CheckStaxSOAP11Header(reader) THEN
              CALL WSHelper.WSHelper_FillSOAP11WSError("Client","No ending header tag found")
              EXIT CASE
            ELSE
              CALL reader.nextTag()
            END IF
          ELSE
            IF reader.isEmptyElement() THEN
              CALL reader.nextTag()
            END IF
          END IF
          IF NOT WSHelper.WSHelper_ReadStaxSOAP11StartBody(reader) THEN
            EXIT CASE
          END IF
          IF WSHelper.WSHelper_CheckStaxSOAP11StartFault(reader) THEN # Handle SOAP Fault
            LET fault = TRUE
            CALL reader.nextTag()
            IF NOT WSHelper.WSHelper_ReadStaxSOAP11FaultUntilDetail(reader) THEN
              EXIT CASE
            END IF
            IF WSHelper.WSHelper_CheckStaxSOAP11FaultDetail(reader) THEN
              #
              # STAX SOAP FAULT DESERIALIZE
              #
              CALL reader.nextSibling() # Skip SOAP detail
            END IF
            IF NOT WSHelper.WSHelper_ReadStaxSOAP11EndFault(reader) THEN
              EXIT CASE
            END IF
          ELSE # Handle SOAP Response
            IF nb != 0 THEN # Check mandatory headers
              CALL WSHelper.WSHelper_FillSOAP11WSError("Client","Headers are missing")
              EXIT CASE
            END IF
            IF NOT WSHelper.WSHelper_RetrieveStaxSOAP11Message(reader) THEN
              EXIT CASE
            END IF
            #
            # STAX SOAP RESPONSE DESERIALIZE
            #
            CALL xml.Serializer.StaxToVariable(reader,getEstatusAseguradoResponse)
          END IF
          IF NOT WSHelper.WSHelper_ReadStaxSOAP11EndBody(reader) THEN
            EXIT CASE
          END IF
          IF NOT WSHelper.WSHelper_ReadStaxSOAP11EndEnvelope(reader) THEN
            EXIT CASE
          END IF
          # End Streaming Response
          CALL response.endXmlResponse(reader)
          IF NOT fault THEN
            LET wsstatus = 0
          END IF

        WHEN response.getStatusCode()==401 # HTTP Authentication
          IF retryAuth THEN
            CALL WSHelper.WSHelper_FillSOAP11WSError("Server","HTTP Error 401 ("||response.getStatusDescription()||")")
          ELSE
            LET retryAuth = TRUE
            LET retry = TRUE
          END IF

        WHEN response.getStatusCode()==407 # Proxy Authentication
          IF retryProxy THEN
            CALL WSHelper.WSHelper_FillSOAP11WSError("Server","HTTP Error 407 ("||response.getStatusDescription()||")")
          ELSE
            LET retryProxy = TRUE
            LET retry = TRUE
          END IF

        OTHERWISE
          CALL WSHelper.WSHelper_FillSOAP11WSError("Server","HTTP Error "||response.getStatusCode()||" ("||response.getStatusDescription()||")")

      END CASE
    CATCH
      LET wsstatus = status
      CALL WSHelper.WSHelper_FillSOAP11WSError("Server",sqlca.sqlerrm)
      RETURN wsstatus
    END TRY

  # END LOOP
  END WHILE

  RETURN wsstatus

END FUNCTION


FUNCTION getEstatusAseguradoRequest_g()
  DEFINE wsstatus   INTEGER
  DEFINE writer     xml.StaxWriter

  #
  # CHECK PREVIOUS CALL  
  #
  IF getEstatusAseguradoHTTPReq IS NOT NULL AND getEstatusAseguradoHTTPResp IS NULL THEN
    # Request was sent but there was no response yet
    CALL WSHelper.WSHelper_FillSOAP11WSError("Client","Cannot issue a new request until previous response was received")
    RETURN -2 # waiting for the response
  ELSE
    #IF WSEstatusAsegurado_WSEstatusAseguradoPortEndpoint.Address.Uri IS NULL THEN
    #  LET WSEstatusAsegurado_WSEstatusAseguradoPortEndpoint.Address.Uri = "http://api.dev.issste.gob.mx:80/semanascotizadas-rest/WSEstatusAsegurado"
    #END IF
  END IF

  #
  # CREATE REQUEST
  #
  TRY
    LET getEstatusAseguradoHTTPReq = com.HttpRequest.Create(WSEstatusAsegurado_WSEstatusAseguradoPortEndpoint.Address.Uri)
    CALL getEstatusAseguradoHTTPReq.setMethod("POST")
    CALL getEstatusAseguradoHTTPReq.setCharset("UTF-8")
    CALL getEstatusAseguradoHTTPReq.setHeader("SOAPAction","\"\"")
    CALL WSHelper.WSHelper_SetRequestHeaders(getEstatusAseguradoHTTPReq, WSEstatusAsegurado_WSEstatusAseguradoPortEndpoint.Binding.Request.Headers)
    IF WSEstatusAsegurado_WSEstatusAseguradoPortEndpoint.Binding.Version IS NOT NULL THEN
      CALL getEstatusAseguradoHTTPReq.setVersion(WSEstatusAsegurado_WSEstatusAseguradoPortEndpoint.Binding.Version)
    END IF
    IF WSEstatusAsegurado_WSEstatusAseguradoPortEndpoint.Binding.Cookie IS NOT NULL THEN
      CALL getEstatusAseguradoHTTPReq.setHeader("Cookie",WSEstatusAsegurado_WSEstatusAseguradoPortEndpoint.Binding.Cookie)
    END IF
    IF WSEstatusAsegurado_WSEstatusAseguradoPortEndpoint.Binding.ConnectionTimeout <> 0 THEN
      CALL getEstatusAseguradoHTTPReq.setConnectionTimeOut(WSEstatusAsegurado_WSEstatusAseguradoPortEndpoint.Binding.ConnectionTimeout)
    END IF
    IF WSEstatusAsegurado_WSEstatusAseguradoPortEndpoint.Binding.ReadWriteTimeout <> 0 THEN
      CALL getEstatusAseguradoHTTPReq.setTimeOut(WSEstatusAsegurado_WSEstatusAseguradoPortEndpoint.Binding.ReadWriteTimeout)
    END IF
    IF WSEstatusAsegurado_WSEstatusAseguradoPortEndpoint.Binding.CompressRequest IS NOT NULL THEN
      CALL getEstatusAseguradoHTTPReq.setHeader("Content-Encoding",WSEstatusAsegurado_WSEstatusAseguradoPortEndpoint.Binding.CompressRequest)
    END IF
    CALL getEstatusAseguradoHTTPReq.setHeader("Accept-Encoding","gzip, deflate")
  CATCH
    LET wsstatus = status
    CALL WSHelper.WSHelper_FillSOAP11WSError("Client","Cannot create HTTPRequest")
    LET getEstatusAseguradoHTTPReq = NULL
    RETURN wsstatus
  END TRY

    #
    # Stax request
    #
    TRY
      LET writer = getEstatusAseguradoHTTPReq.beginXmlRequest()
      CALL WSHelper.WSHelper_WriteStaxSOAP11StartEnvelope(writer)
      CALL WSHelper.WSHelper_WriteStaxSOAP11StartBody(writer)
      #
      # STAX SOAP REQUEST SERIALIZE
      #
      CALL xml.Serializer.VariableToStax(getEstatusAsegurado,writer)
      CALL WSHelper.WSHelper_WriteStaxSOAP11EndBody(writer)
      CALL WSHelper.WSHelper_WriteStaxSOAP11EndEnvelope(writer)
      CALL getEstatusAseguradoHTTPReq.endXmlRequest(writer)
    CATCH
      LET wsstatus = status
      CALL WSHelper.WSHelper_FillSOAP11WSError("Client",sqlca.sqlerrm)
      LET getEstatusAseguradoHTTPReq = NULL
      RETURN wsstatus
    END TRY

  #
  # PROCESS RESPONSE
  #
  TRY
    LET getEstatusAseguradoHTTPResp = getEstatusAseguradoHTTPReq.getAsyncResponse()
    RETURN 0 # SUCCESS
  CATCH
    LET wsstatus = status
    CALL WSHelper.WSHelper_FillSOAP11WSError("Server",sqlca.sqlerrm)
    LET getEstatusAseguradoHTTPReq = NULL
    RETURN wsstatus
  END TRY
END FUNCTION


FUNCTION getEstatusAseguradoResponse_g()
  DEFINE wsstatus        INTEGER
  DEFINE fault           BOOLEAN
  DEFINE nb              INTEGER
  DEFINE uri             STRING
  DEFINE setcookie       STRING
  DEFINE mustUnderstand  INTEGER
  DEFINE reader          xml.StaxReader

  LET fault = FALSE
  LET wsstatus = -1

  LET uri = com.WebServiceEngine.GetOption("SoapModuleURI")
  #
  # CHECK PREVIOUS CALL  
  #
  IF getEstatusAseguradoHTTPReq IS NULL THEN
    # No request was sent
    CALL WSHelper.WSHelper_FillSOAP11WSError("Client","No request has been sent")
    RETURN -1
  END IF

  TRY
    #
    # PROCESS RESPONSE
    #
    IF getEstatusAseguradoHTTPResp IS NULL THEN
      # Still no response, try again
      LET getEstatusAseguradoHTTPResp = getEstatusAseguradoHTTPReq.getAsyncResponse()
    END IF

    IF getEstatusAseguradoHTTPResp IS NULL THEN
      # We got no response, still waiting for
      CALL WSHelper.WSHelper_FillSOAP11WSError("Client","Response was not yet received")
      RETURN -2
    END IF

      #
      # RETRIEVE SERVICE SESSION COOKIE
      #
      LET setcookie = getEstatusAseguradoHTTPResp.getHeader("Set-Cookie")
      IF setcookie IS NOT NULL THEN
        LET WSEstatusAsegurado_WSEstatusAseguradoPortEndpoint.Binding.Cookie = WSHelper.WSHelper_ExtractServerCookie(setcookie,WSEstatusAsegurado_WSEstatusAseguradoPortEndpoint.Address.Uri)
      END IF

      #
      # RETRIEVE HTTP RESPONSE Headers
      #
      CALL WSHelper.WSHelper_SetResponseHeaders(getEstatusAseguradoHTTPResp, WSEstatusAsegurado_WSEstatusAseguradoPortEndpoint.Binding.Response.Headers)
      CASE
        WHEN getEstatusAseguradoHTTPResp.getStatusCode()==200 OR getEstatusAseguradoHTTPResp.getStatusCode()==500
          #
          # STAX SOAP RESPONSE OR FAULT
          #
          LET reader = getEstatusAseguradoHTTPResp.beginXmlResponse() # Begin Streaming Response
          IF NOT WSHelper.WSHelper_ReadStaxSOAP11StartEnvelope(reader) THEN
            EXIT CASE
          END IF
          # Process SOAP headers 
          LET nb = 0
          IF WSHelper.WSHelper_CheckStaxSOAP11Header(reader) AND NOT reader.isEmptyElement() THEN
            CALL reader.nextTag()
            WHILE (reader.getEventType()=="START_ELEMENT")
              IF WSHelper.WSHelper_CheckStaxSOAP11HeaderActor(reader,uri) THEN
                LET mustUnderstand = WSHelper.WSHelper_GetStaxSOAP11HeaderMustUnderstand(reader)
                IF mustUnderstand = -1 THEN
                  CALL WSHelper.WSHelper_FillSOAP11WSError("Client","Invalid mustUnderstand value")
                  EXIT CASE
                END IF
                #
                # STAX SOAP RESPONSE HEADER DESERIALIZE
                #
                IF mustUnderstand THEN
                  CALL WSHelper.WSHelper_FillSOAP11WSError("MustUnderstand","Mandatory header block not understood")
                  EXIT CASE
                ELSE
                  CALL reader.nextSibling() # Skip header, not necessary
                END IF
              ELSE
                CALL reader.nextSibling() # Skip header, not intended to us
              END IF
            END WHILE
            IF NOT WSHelper.WSHelper_CheckStaxSOAP11Header(reader) THEN
              CALL WSHelper.WSHelper_FillSOAP11WSError("Client","No ending header tag found")
              EXIT CASE
            ELSE
              CALL reader.nextTag()
            END IF
          ELSE
            IF reader.isEmptyElement() THEN
              CALL reader.nextTag()
            END IF
          END IF
          IF NOT WSHelper.WSHelper_ReadStaxSOAP11StartBody(reader) THEN
            EXIT CASE
          END IF
          IF WSHelper.WSHelper_CheckStaxSOAP11StartFault(reader) THEN # Handle SOAP Fault
            LET fault = TRUE
            CALL reader.nextTag()
            IF NOT WSHelper.WSHelper_ReadStaxSOAP11FaultUntilDetail(reader) THEN
              EXIT CASE
            END IF
            IF WSHelper.WSHelper_CheckStaxSOAP11FaultDetail(reader) THEN
              #
              # STAX SOAP FAULT DESERIALIZE
              #
              CALL reader.nextSibling() # Skip SOAP detail
            END IF
            IF NOT WSHelper.WSHelper_ReadStaxSOAP11EndFault(reader) THEN
              EXIT CASE
            END IF
          ELSE # Handle SOAP Response
            IF nb != 0 THEN # Check mandatory headers
              CALL WSHelper.WSHelper_FillSOAP11WSError("Client","Headers are missing")
              EXIT CASE
            END IF
            IF NOT WSHelper.WSHelper_RetrieveStaxSOAP11Message(reader) THEN
              EXIT CASE
            END IF
            #
            # STAX SOAP RESPONSE DESERIALIZE
            #
            CALL xml.Serializer.StaxToVariable(reader,getEstatusAseguradoResponse)
          END IF
          IF NOT WSHelper.WSHelper_ReadStaxSOAP11EndBody(reader) THEN
            EXIT CASE
          END IF
          IF NOT WSHelper.WSHelper_ReadStaxSOAP11EndEnvelope(reader) THEN
            EXIT CASE
          END IF
          # End Streaming Response
          CALL getEstatusAseguradoHTTPResp.endXmlResponse(reader)
          IF NOT fault THEN
            LET wsstatus = 0
          END IF

        OTHERWISE
          CALL WSHelper.WSHelper_FillSOAP11WSError("Server","HTTP Error "||getEstatusAseguradoHTTPResp.getStatusCode()||" ("||getEstatusAseguradoHTTPResp.getStatusDescription()||")")

      END CASE
    CATCH
      LET wsstatus = status
      CALL WSHelper.WSHelper_FillSOAP11WSError("Server",sqlca.sqlerrm)
    END TRY

  #
  # RESET VARIABLES
  #
  LET getEstatusAseguradoHTTPReq = NULL
  LET getEstatusAseguradoHTTPResp = NULL
  RETURN wsstatus

END FUNCTION


