#-------------------------------------------------------------------------------
# File: clienteSaldosPreliminar.4gl
# GENERATED BY fglwsdl 202210171337
#-------------------------------------------------------------------------------
# THIS FILE WAS GENERATED. DO NOT MODIFY.
#-------------------------------------------------------------------------------


IMPORT FGL WSHelper
IMPORT com
IMPORT xml

#
#-------------------------------------------------------------------------------
# XML Type definitions 
#-------------------------------------------------------------------------------
#

#
# TYPE : tns2IDSSN
#
PUBLIC TYPE tns2IDSSN RECORD ATTRIBUTE(XMLSequence,XSTypeName="IDSSN",XSTypeNamespace="http://www.procesar.com.mx/ArquitecturaSW/DataTypes/tiposComunesProcesar/")
  idSistema DECIMAL(32,0) ATTRIBUTE(XSDinteger,XSDPattern="(0|([1-9][0-9]*))",XSDMinInclusive="0",XSDMaxInclusive="2147483647",XMLNamespace=""),
  idEbusiness DECIMAL(32,0) ATTRIBUTE(XSDinteger,XSDPattern="(0|([1-9][0-9]*))",XSDMinInclusive="0",XSDMaxInclusive="2147483647",XMLNamespace=""),
  idPortafolio DECIMAL(32,0) ATTRIBUTE(XSDinteger,XSDPattern="(0|([1-9][0-9]*))",XSDMinInclusive="0",XSDMaxInclusive="2147483647",XMLNamespace=""),
  idServicio DECIMAL(32,0) ATTRIBUTE(XSDinteger,XSDPattern="(0|([1-9][0-9]*))",XSDMinInclusive="0",XSDMaxInclusive="2147483647",XMLNamespace=""),
  idCliente DECIMAL(32,0) ATTRIBUTE(XSDinteger,XSDPattern="(0|([1-9][0-9]*))",XSDMinInclusive="0",XSDMaxInclusive="2147483647",XMLNamespace=""),
  idCanal DECIMAL(32,0) ATTRIBUTE(XSDinteger,XSDPattern="(0|([1-9][0-9]*))",XSDMinInclusive="0",XSDMaxInclusive="2147483647",XMLNamespace=""),
  codoperCliente STRING ATTRIBUTE(XSDMinLength="1",XSDMaxLength="50",XSDPattern="[a-zA-Z0-9\\|\\-@\\.\\\\_]*",XMLNamespace=""),
  fecha DATETIME YEAR TO FRACTION(5) ATTRIBUTE(XMLNamespace="")
END RECORD
#-------------------------------------------------------------------------------

#
# TYPE : tns2alfaNumerico_11
#
PUBLIC TYPE tns2alfaNumerico_11 STRING ATTRIBUTE(XSDMinLength="0",XSDMaxLength="11",XSTypeName="alfaNumerico_11",XSTypeNamespace="http://www.procesar.com.mx/ArquitecturaSW/DataTypes/tiposComunesProcesar/")
#-------------------------------------------------------------------------------

#
# TYPE : tns2alfaNumerico_18
#
PUBLIC TYPE tns2alfaNumerico_18 STRING ATTRIBUTE(XSDMinLength="1",XSDMaxLength="18",XSTypeName="alfaNumerico_18",XSTypeNamespace="http://www.procesar.com.mx/ArquitecturaSW/DataTypes/tiposComunesProcesar/")
#-------------------------------------------------------------------------------

#
# TYPE : tns2alfaNumerico_1
#
PUBLIC TYPE tns2alfaNumerico_1 STRING ATTRIBUTE(XSDMinLength="0",XSDMaxLength="1",XSTypeName="alfaNumerico_1",XSTypeNamespace="http://www.procesar.com.mx/ArquitecturaSW/DataTypes/tiposComunesProcesar/")
#-------------------------------------------------------------------------------

#
# TYPE : tns1consultarSaldoPreliminarEntrada
#
PUBLIC TYPE tns1consultarSaldoPreliminarEntrada RECORD ATTRIBUTE(XMLSequence,XSTypeName="consultarSaldoPreliminarEntrada",XSTypeNamespace="http://www.procesar.com.mx/Retiros/SaldoPreliminarIssste/consultarSaldoPreliminar/")
  nss tns2alfaNumerico_11 ATTRIBUTE(XMLNamespace="",XMLOptional),
  curp tns2alfaNumerico_18 ATTRIBUTE(XMLNamespace=""),
  cveInstitutoOrigen tns2alfaNumerico_1 ATTRIBUTE(XMLNamespace="")
END RECORD
#-------------------------------------------------------------------------------

#
# TYPE : tns1consultarSaldoPreliminarContrato
#
PUBLIC TYPE tns1consultarSaldoPreliminarContrato RECORD ATTRIBUTE(XMLSequence,XSTypeName="consultarSaldoPreliminarContrato",XSTypeNamespace="http://www.procesar.com.mx/Retiros/SaldoPreliminarIssste/consultarSaldoPreliminar/")
  idssn tns2IDSSN ATTRIBUTE(XMLNamespace=""),
  cuerpo tns1consultarSaldoPreliminarEntrada ATTRIBUTE(XMLNamespace="")
END RECORD
#-------------------------------------------------------------------------------

#
# TYPE : tns2cveAfore
#
PUBLIC TYPE tns2cveAfore STRING ATTRIBUTE(XSDPattern="[0-9][0-9][0-9]",XSTypeName="cveAfore",XSTypeNamespace="http://www.procesar.com.mx/ArquitecturaSW/DataTypes/tiposComunesProcesar/")
#-------------------------------------------------------------------------------

#
# TYPE : tns2alfaNumerico_40
#
PUBLIC TYPE tns2alfaNumerico_40 STRING ATTRIBUTE(XSDMinLength="0",XSDMaxLength="40",XSTypeName="alfaNumerico_40",XSTypeNamespace="http://www.procesar.com.mx/ArquitecturaSW/DataTypes/tiposComunesProcesar/")
#-------------------------------------------------------------------------------

#
# TYPE : tns2alfaNumerico_13
#
PUBLIC TYPE tns2alfaNumerico_13 STRING ATTRIBUTE(XSDMinLength="1",XSDMaxLength="13",XSTypeName="alfaNumerico_13",XSTypeNamespace="http://www.procesar.com.mx/ArquitecturaSW/DataTypes/tiposComunesProcesar/")
#-------------------------------------------------------------------------------

#
# TYPE : tns2numerico_13_2
#
PUBLIC TYPE tns2numerico_13_2 DECIMAL(15,2) ATTRIBUTE(XSDTotalDigits="15",XSDFractionDigits="2",XSTypeName="numerico_13_2",XSTypeNamespace="http://www.procesar.com.mx/ArquitecturaSW/DataTypes/tiposComunesProcesar/")
#-------------------------------------------------------------------------------

#
# TYPE : tns2alfaNumerico_4
#
PUBLIC TYPE tns2alfaNumerico_4 STRING ATTRIBUTE(XSDMinLength="0",XSDMaxLength="4",XSTypeName="alfaNumerico_4",XSTypeNamespace="http://www.procesar.com.mx/ArquitecturaSW/DataTypes/tiposComunesProcesar/")
#-------------------------------------------------------------------------------

#
# TYPE : tns2alfaNumerico_3
#
PUBLIC TYPE tns2alfaNumerico_3 STRING ATTRIBUTE(XSDMinLength="0",XSDMaxLength="3",XSTypeName="alfaNumerico_3",XSTypeNamespace="http://www.procesar.com.mx/ArquitecturaSW/DataTypes/tiposComunesProcesar/")
#-------------------------------------------------------------------------------

#
# TYPE : tns2alfaNumerico_30
#
PUBLIC TYPE tns2alfaNumerico_30 STRING ATTRIBUTE(XSDMinLength="1",XSDMaxLength="30",XSTypeName="alfaNumerico_30",XSTypeNamespace="http://www.procesar.com.mx/ArquitecturaSW/DataTypes/tiposComunesProcesar/")
#-------------------------------------------------------------------------------

#
# TYPE : tns2resultadoOp
#
PUBLIC TYPE tns2resultadoOp STRING ATTRIBUTE(XSDEnumeration="01|02",XSTypeName="resultadoOp",XSTypeNamespace="http://www.procesar.com.mx/ArquitecturaSW/DataTypes/tiposComunesProcesar/")
#-------------------------------------------------------------------------------

#
# TYPE : tns2alfaNumerico_20
#
PUBLIC TYPE tns2alfaNumerico_20 STRING ATTRIBUTE(XSDMinLength="0",XSDMaxLength="20",XSTypeName="alfaNumerico_20",XSTypeNamespace="http://www.procesar.com.mx/ArquitecturaSW/DataTypes/tiposComunesProcesar/")
#-------------------------------------------------------------------------------

#
# TYPE : tns1consultarSaldoPreliminarSalida
#
PUBLIC TYPE tns1consultarSaldoPreliminarSalida RECORD ATTRIBUTE(XMLSequence,XSTypeName="consultarSaldoPreliminarSalida",XSTypeNamespace="http://www.procesar.com.mx/Retiros/SaldoPreliminarIssste/consultarSaldoPreliminar/")
  nss tns2alfaNumerico_11 ATTRIBUTE(XMLNamespace="",XMLOptional),
  curp tns2alfaNumerico_18 ATTRIBUTE(XMLNamespace=""),
  cveInstitutoOrigen tns2alfaNumerico_1 ATTRIBUTE(XMLNamespace=""),
  cveAfore tns2cveAfore ATTRIBUTE(XMLNamespace="",XMLOptional),
  nombre tns2alfaNumerico_40 ATTRIBUTE(XMLNamespace="",XMLOptional),
  apellidoPaterno tns2alfaNumerico_40 ATTRIBUTE(XMLNamespace="",XMLOptional),
  apellidoMaterno tns2alfaNumerico_40 ATTRIBUTE(XMLNamespace="",XMLOptional),
  rfc tns2alfaNumerico_13 ATTRIBUTE(XMLNamespace="",XMLOptional),
  curpRegistrada tns2alfaNumerico_18 ATTRIBUTE(XMLNamespace="",XMLOptional),
  saldoSar92 tns2numerico_13_2 ATTRIBUTE(XMLNamespace="",XMLOptional),
  saldoRetiro97 tns2numerico_13_2 ATTRIBUTE(XMLNamespace="",XMLOptional),
  saldoCuotaSocial tns2numerico_13_2 ATTRIBUTE(XMLNamespace="",XMLOptional),
  saldoCesantiaVejez tns2numerico_13_2 ATTRIBUTE(XMLNamespace="",XMLOptional),
  saldoVivienda97 tns2numerico_13_2 ATTRIBUTE(XMLNamespace="",XMLOptional),
  saldoVivienda97AIVS tns2numerico_13_2 ATTRIBUTE(XMLNamespace="",XMLOptional),
  saldoVivienda92 tns2numerico_13_2 ATTRIBUTE(XMLNamespace="",XMLOptional),
  saldoVivienda92AIVS tns2numerico_13_2 ATTRIBUTE(XMLNamespace="",XMLOptional),
  saldoAhorroRetiroIB tns2numerico_13_2 ATTRIBUTE(XMLNamespace="",XMLOptional),
  saldoAportacionesVoluntarias tns2numerico_13_2 ATTRIBUTE(XMLNamespace="",XMLOptional),
  saldoRetiro92I tns2numerico_13_2 ATTRIBUTE(XMLNamespace="",XMLOptional),
  saldoAportaCompRetiro tns2numerico_13_2 ATTRIBUTE(XMLNamespace="",XMLOptional),
  saldoViviendaFI92 tns2numerico_13_2 ATTRIBUTE(XMLNamespace="",XMLOptional),
  saldoViviendaFI92AIVS tns2numerico_13_2 ATTRIBUTE(XMLNamespace="",XMLOptional),
  saldoAportaLargoPlazo tns2numerico_13_2 ATTRIBUTE(XMLNamespace="",XMLOptional),
  saldoFI08 tns2numerico_13_2 ATTRIBUTE(XMLNamespace="",XMLOptional),
  saldoFI08AIVS tns2numerico_13_2 ATTRIBUTE(XMLNamespace="",XMLOptional),
  saldoRetiroI08 tns2numerico_13_2 ATTRIBUTE(XMLNamespace="",XMLOptional),
  saldoCVI tns2numerico_13_2 ATTRIBUTE(XMLNamespace="",XMLOptional),
  saldoAhorroSolidario tns2numerico_13_2 ATTRIBUTE(XMLNamespace="",XMLOptional),
  saldoCuotaSocialI tns2numerico_13_2 ATTRIBUTE(XMLNamespace="",XMLOptional),
  saldoBonoMonto tns2numerico_13_2 ATTRIBUTE(XMLNamespace="",XMLOptional),
  anhoVencimiento tns2alfaNumerico_4 ATTRIBUTE(XMLNamespace="",XMLOptional),
  estatusCuentaIndividual tns2alfaNumerico_3 ATTRIBUTE(XMLNamespace="",XMLOptional),
  estatusViviendaI tns2alfaNumerico_1 ATTRIBUTE(XMLNamespace="",XMLOptional),
  estatusViviendaF tns2alfaNumerico_1 ATTRIBUTE(XMLNamespace="",XMLOptional),
  diagnostico tns2alfaNumerico_3 ATTRIBUTE(XMLNamespace=""),
  descripcionDiagnostico tns2alfaNumerico_40 ATTRIBUTE(XMLNamespace=""),
  folioSolicitud tns2alfaNumerico_30 ATTRIBUTE(XMLNamespace="",XMLOptional),
  resultado tns2resultadoOp ATTRIBUTE(XMLNamespace=""),
  descripcion tns2alfaNumerico_20 ATTRIBUTE(XMLNamespace="")
END RECORD
#-------------------------------------------------------------------------------

#
# TYPE : tns1consultarSaldoPreliminarRespuesta
#
PUBLIC TYPE tns1consultarSaldoPreliminarRespuesta RECORD ATTRIBUTE(XMLSequence,XSTypeName="consultarSaldoPreliminarRespuesta",XSTypeNamespace="http://www.procesar.com.mx/Retiros/SaldoPreliminarIssste/consultarSaldoPreliminar/")
  objetoRespuesta tns1consultarSaldoPreliminarSalida ATTRIBUTE(XMLNamespace="")
END RECORD
#-------------------------------------------------------------------------------



#-------------------------------------------------------------------------------
# Service: SaldoPreliminarIssste
# Port:    SaldoPreliminarIssstePort
# Server:  http://wsprocesar.com.mx:80/Retiros/SaldoPreliminarIssste
#-------------------------------------------------------------------------------
#
# Location of the SOAP endpoint.
# You can reassign this value at run-time.
#
PUBLIC DEFINE SaldoPreliminarIssste_SaldoPreliminarIssstePortEndpoint WSHelper.tGlobalEndpointType


#-------------------------------------------------------------------------------

# VARIABLE : ns1consultarSaldoPreliminarRequest
PUBLIC DEFINE ns1consultarSaldoPreliminarRequest tns1consultarSaldoPreliminarContrato ATTRIBUTE(XMLName="consultarSaldoPreliminarRequest",XMLNamespace="http://www.procesar.com.mx/Retiros/SaldoPreliminarIssste/consultarSaldoPreliminar/")


#-------------------------------------------------------------------------------

# VARIABLE : ns1consultarSaldoPreliminarResponse
PUBLIC DEFINE ns1consultarSaldoPreliminarResponse tns1consultarSaldoPreliminarRespuesta ATTRIBUTE(XMLName="consultarSaldoPreliminarResponse",XMLNamespace="http://www.procesar.com.mx/Retiros/SaldoPreliminarIssste/consultarSaldoPreliminar/")



# end of service types
#-------------------------------------------------------------------------------

# Start service implementation
#-------------------------------------------------------------------------------
# Service: SaldoPreliminarIssste
# Port:    SaldoPreliminarIssstePort
# Server:  http://wsprocesar.com.mx:80/Retiros/SaldoPreliminarIssste
#-------------------------------------------------------------------------------

PRIVATE DEFINE consultarSaldoPreliminarHTTPReq     com.HttpRequest
PRIVATE DEFINE consultarSaldoPreliminarHTTPResp    com.HttpResponse

#-------------------------------------------------------------------------------

#
# Operation: consultarSaldoPreliminar
#
#
# FUNCTION: consultarSaldoPreliminar_g
#   RETURNING: soapStatus
#   INPUT:  ns1consultarSaldoPreliminarRequest
#   OUTPUT:  ns1consultarSaldoPreliminarResponse
#
FUNCTION consultarSaldoPreliminar_g()
  DEFINE wsstatus   INTEGER
  DEFINE retryAuth  INTEGER
  DEFINE retryProxy INTEGER
  DEFINE retry      INTEGER
  DEFINE fault      BOOLEAN
  DEFINE nb         INTEGER
  DEFINE uri        STRING
  DEFINE setcookie  STRING
  DEFINE mustUnderstand INTEGER
  DEFINE request    com.HttpRequest
  DEFINE response   com.HttpResponse
  DEFINE writer     xml.StaxWriter
  DEFINE reader     xml.StaxReader

  #
  # INIT VARIABLES
  #
  LET wsstatus = -1
  LET retryAuth = FALSE
  LET retryProxy = FALSE
  LET retry = TRUE
  LET fault = FALSE
  LET uri = com.WebServiceEngine.GetOption("SoapModuleURI")

#  IF SaldoPreliminarIssste_SaldoPreliminarIssstePortEndpoint.Address.Uri IS NULL THEN
#    LET SaldoPreliminarIssste_SaldoPreliminarIssstePortEndpoint.Address.Uri = "http://wsprocesar.com.mx:80/Retiros/SaldoPreliminarIssste"
#  END IF

  #
  # CREATE REQUEST
  #
  TRY
    LET request = com.HttpRequest.Create(SaldoPreliminarIssste_SaldoPreliminarIssstePortEndpoint.Address.Uri)
    CALL request.setMethod("POST")
    CALL request.setCharset("UTF-8")
    CALL request.setHeader("SOAPAction","\"http://www.procesar.com.mx/Retiros/SaldoPreliminarIssste/consultarSaldoPreliminar/\"")
    CALL WSHelper.WSHelper_SetRequestHeaders(request, SaldoPreliminarIssste_SaldoPreliminarIssstePortEndpoint.Binding.Request.Headers)
    IF SaldoPreliminarIssste_SaldoPreliminarIssstePortEndpoint.Binding.Version IS NOT NULL THEN
      CALL request.setVersion(SaldoPreliminarIssste_SaldoPreliminarIssstePortEndpoint.Binding.Version)
    END IF
    IF SaldoPreliminarIssste_SaldoPreliminarIssstePortEndpoint.Binding.Cookie IS NOT NULL THEN
      CALL request.setHeader("Cookie",SaldoPreliminarIssste_SaldoPreliminarIssstePortEndpoint.Binding.Cookie)
    END IF
    IF SaldoPreliminarIssste_SaldoPreliminarIssstePortEndpoint.Binding.ConnectionTimeout <> 0 THEN
      CALL request.setConnectionTimeOut(SaldoPreliminarIssste_SaldoPreliminarIssstePortEndpoint.Binding.ConnectionTimeout)
    END IF
    IF SaldoPreliminarIssste_SaldoPreliminarIssstePortEndpoint.Binding.ReadWriteTimeout <> 0 THEN
      CALL request.setTimeOut(SaldoPreliminarIssste_SaldoPreliminarIssstePortEndpoint.Binding.ReadWriteTimeout)
    END IF
    IF SaldoPreliminarIssste_SaldoPreliminarIssstePortEndpoint.Binding.CompressRequest IS NOT NULL THEN
      CALL request.setHeader("Content-Encoding",SaldoPreliminarIssste_SaldoPreliminarIssstePortEndpoint.Binding.CompressRequest)
    END IF
    CALL request.setHeader("Accept-Encoding","gzip, deflate")
  CATCH
    LET wsstatus = status
    CALL WSHelper.WSHelper_FillSOAP11WSError("Client","Cannot create HTTPRequest")
    RETURN wsstatus
  END TRY

  # START LOOP
  WHILE retry
    LET retry = FALSE

    #
    # Stax request
    #
    TRY
      LET writer = request.beginXmlRequest()
      CALL WSHelper.WSHelper_WriteStaxSOAP11StartEnvelope(writer)
      CALL WSHelper.WSHelper_WriteStaxSOAP11StartBody(writer)
      #
      # STAX SOAP REQUEST SERIALIZE
      #
      CALL xml.Serializer.VariableToStax(ns1consultarSaldoPreliminarRequest,writer)
      CALL WSHelper.WSHelper_WriteStaxSOAP11EndBody(writer)
      CALL WSHelper.WSHelper_WriteStaxSOAP11EndEnvelope(writer)
      CALL request.endXmlRequest(writer)
    CATCH
      LET wsstatus = status
      CALL WSHelper.WSHelper_FillSOAP11WSError("Client",sqlca.sqlerrm)
      RETURN wsstatus
    END TRY

    #
    # PROCESS RESPONSE
    #
    TRY
      LET response = request.getResponse()

      #
      # RETRIEVE SERVICE SESSION COOKIE
      #
      LET setcookie = response.getHeader("Set-Cookie")
      IF setcookie IS NOT NULL THEN
        LET SaldoPreliminarIssste_SaldoPreliminarIssstePortEndpoint.Binding.Cookie = WSHelper.WSHelper_ExtractServerCookie(setcookie,SaldoPreliminarIssste_SaldoPreliminarIssstePortEndpoint.Address.Uri)
      END IF

      #
      # RETRIEVE HTTP RESPONSE Headers
      #
      CALL WSHelper.WSHelper_SetResponseHeaders(response, SaldoPreliminarIssste_SaldoPreliminarIssstePortEndpoint.Binding.Response.Headers)

      CASE
        WHEN response.getStatusCode()==200 OR response.getStatusCode()==500
          #
          # STAX SOAP RESPONSE OR FAULT
          #
          LET reader = response.beginXmlResponse() # Begin Streaming Response
          IF NOT WSHelper.WSHelper_ReadStaxSOAP11StartEnvelope(reader) THEN
            EXIT CASE
          END IF
          # Process SOAP headers 
          LET nb = 0
          IF WSHelper.WSHelper_CheckStaxSOAP11Header(reader) AND NOT reader.isEmptyElement() THEN
            CALL reader.nextTag()
            WHILE (reader.getEventType()=="START_ELEMENT")
              IF WSHelper.WSHelper_CheckStaxSOAP11HeaderActor(reader,uri) THEN
                LET mustUnderstand = WSHelper.WSHelper_GetStaxSOAP11HeaderMustUnderstand(reader)
                IF mustUnderstand = -1 THEN
                  CALL WSHelper.WSHelper_FillSOAP11WSError("Client","Invalid mustUnderstand value")
                  EXIT CASE
                END IF
                #
                # STAX SOAP RESPONSE HEADER DESERIALIZE
                #
                IF mustUnderstand THEN
                  CALL WSHelper.WSHelper_FillSOAP11WSError("MustUnderstand","Mandatory header block not understood")
                  EXIT CASE
                ELSE
                  CALL reader.nextSibling() # Skip header, not necessary
                END IF
              ELSE
                CALL reader.nextSibling() # Skip header, not intended to us
              END IF
            END WHILE
            IF NOT WSHelper.WSHelper_CheckStaxSOAP11Header(reader) THEN
              CALL WSHelper.WSHelper_FillSOAP11WSError("Client","No ending header tag found")
              EXIT CASE
            ELSE
              CALL reader.nextTag()
            END IF
          ELSE
            IF reader.isEmptyElement() THEN
              CALL reader.nextTag()
            END IF
          END IF
          IF NOT WSHelper.WSHelper_ReadStaxSOAP11StartBody(reader) THEN
            EXIT CASE
          END IF
          IF WSHelper.WSHelper_CheckStaxSOAP11StartFault(reader) THEN # Handle SOAP Fault
            LET fault = TRUE
            CALL reader.nextTag()
            IF NOT WSHelper.WSHelper_ReadStaxSOAP11FaultUntilDetail(reader) THEN
              EXIT CASE
            END IF
            IF WSHelper.WSHelper_CheckStaxSOAP11FaultDetail(reader) THEN
              #
              # STAX SOAP FAULT DESERIALIZE
              #
              CALL reader.nextSibling() # Skip SOAP detail
            END IF
            IF NOT WSHelper.WSHelper_ReadStaxSOAP11EndFault(reader) THEN
              EXIT CASE
            END IF
          ELSE # Handle SOAP Response
            IF nb != 0 THEN # Check mandatory headers
              CALL WSHelper.WSHelper_FillSOAP11WSError("Client","Headers are missing")
              EXIT CASE
            END IF
            IF NOT WSHelper.WSHelper_RetrieveStaxSOAP11Message(reader) THEN
              EXIT CASE
            END IF
            #
            # STAX SOAP RESPONSE DESERIALIZE
            #
            CALL xml.Serializer.StaxToVariable(reader,ns1consultarSaldoPreliminarResponse)
          END IF
          IF NOT WSHelper.WSHelper_ReadStaxSOAP11EndBody(reader) THEN
            EXIT CASE
          END IF
          IF NOT WSHelper.WSHelper_ReadStaxSOAP11EndEnvelope(reader) THEN
            EXIT CASE
          END IF
          # End Streaming Response
          CALL response.endXmlResponse(reader)
          IF NOT fault THEN
            LET wsstatus = 0
          END IF

        WHEN response.getStatusCode()==401 # HTTP Authentication
          IF retryAuth THEN
            CALL WSHelper.WSHelper_FillSOAP11WSError("Server","HTTP Error 401 ("||response.getStatusDescription()||")")
          ELSE
            LET retryAuth = TRUE
            LET retry = TRUE
          END IF

        WHEN response.getStatusCode()==407 # Proxy Authentication
          IF retryProxy THEN
            CALL WSHelper.WSHelper_FillSOAP11WSError("Server","HTTP Error 407 ("||response.getStatusDescription()||")")
          ELSE
            LET retryProxy = TRUE
            LET retry = TRUE
          END IF

        OTHERWISE
          CALL WSHelper.WSHelper_FillSOAP11WSError("Server","HTTP Error "||response.getStatusCode()||" ("||response.getStatusDescription()||")")

      END CASE
    CATCH
      LET wsstatus = status
      CALL WSHelper.WSHelper_FillSOAP11WSError("Server",sqlca.sqlerrm)
      RETURN wsstatus
    END TRY

  # END LOOP
  END WHILE

  RETURN wsstatus

END FUNCTION


FUNCTION consultarSaldoPreliminarRequest_g()
  DEFINE wsstatus   INTEGER
  DEFINE writer     xml.StaxWriter

  #
  # CHECK PREVIOUS CALL  
  #
  IF consultarSaldoPreliminarHTTPReq IS NOT NULL AND consultarSaldoPreliminarHTTPResp IS NULL THEN
    # Request was sent but there was no response yet
    CALL WSHelper.WSHelper_FillSOAP11WSError("Client","Cannot issue a new request until previous response was received")
    RETURN -2 # waiting for the response
  ELSE
#    IF SaldoPreliminarIssste_SaldoPreliminarIssstePortEndpoint.Address.Uri IS NULL THEN
#      LET SaldoPreliminarIssste_SaldoPreliminarIssstePortEndpoint.Address.Uri = "http://wsprocesar.com.mx:80/Retiros/SaldoPreliminarIssste"
#    END IF
  END IF

  #
  # CREATE REQUEST
  #
  TRY
    LET consultarSaldoPreliminarHTTPReq = com.HttpRequest.Create(SaldoPreliminarIssste_SaldoPreliminarIssstePortEndpoint.Address.Uri)
    CALL consultarSaldoPreliminarHTTPReq.setMethod("POST")
    CALL consultarSaldoPreliminarHTTPReq.setCharset("UTF-8")
    CALL consultarSaldoPreliminarHTTPReq.setHeader("SOAPAction","\"http://www.procesar.com.mx/Retiros/SaldoPreliminarIssste/consultarSaldoPreliminar/\"")
    CALL WSHelper.WSHelper_SetRequestHeaders(consultarSaldoPreliminarHTTPReq, SaldoPreliminarIssste_SaldoPreliminarIssstePortEndpoint.Binding.Request.Headers)
    IF SaldoPreliminarIssste_SaldoPreliminarIssstePortEndpoint.Binding.Version IS NOT NULL THEN
      CALL consultarSaldoPreliminarHTTPReq.setVersion(SaldoPreliminarIssste_SaldoPreliminarIssstePortEndpoint.Binding.Version)
    END IF
    IF SaldoPreliminarIssste_SaldoPreliminarIssstePortEndpoint.Binding.Cookie IS NOT NULL THEN
      CALL consultarSaldoPreliminarHTTPReq.setHeader("Cookie",SaldoPreliminarIssste_SaldoPreliminarIssstePortEndpoint.Binding.Cookie)
    END IF
    IF SaldoPreliminarIssste_SaldoPreliminarIssstePortEndpoint.Binding.ConnectionTimeout <> 0 THEN
      CALL consultarSaldoPreliminarHTTPReq.setConnectionTimeOut(SaldoPreliminarIssste_SaldoPreliminarIssstePortEndpoint.Binding.ConnectionTimeout)
    END IF
    IF SaldoPreliminarIssste_SaldoPreliminarIssstePortEndpoint.Binding.ReadWriteTimeout <> 0 THEN
      CALL consultarSaldoPreliminarHTTPReq.setTimeOut(SaldoPreliminarIssste_SaldoPreliminarIssstePortEndpoint.Binding.ReadWriteTimeout)
    END IF
    IF SaldoPreliminarIssste_SaldoPreliminarIssstePortEndpoint.Binding.CompressRequest IS NOT NULL THEN
      CALL consultarSaldoPreliminarHTTPReq.setHeader("Content-Encoding",SaldoPreliminarIssste_SaldoPreliminarIssstePortEndpoint.Binding.CompressRequest)
    END IF
    CALL consultarSaldoPreliminarHTTPReq.setHeader("Accept-Encoding","gzip, deflate")
  CATCH
    LET wsstatus = status
    CALL WSHelper.WSHelper_FillSOAP11WSError("Client","Cannot create HTTPRequest")
    LET consultarSaldoPreliminarHTTPReq = NULL
    RETURN wsstatus
  END TRY

    #
    # Stax request
    #
    TRY
      LET writer = consultarSaldoPreliminarHTTPReq.beginXmlRequest()
      CALL WSHelper.WSHelper_WriteStaxSOAP11StartEnvelope(writer)
      CALL WSHelper.WSHelper_WriteStaxSOAP11StartBody(writer)
      #
      # STAX SOAP REQUEST SERIALIZE
      #
      CALL xml.Serializer.VariableToStax(ns1consultarSaldoPreliminarRequest,writer)
      CALL WSHelper.WSHelper_WriteStaxSOAP11EndBody(writer)
      CALL WSHelper.WSHelper_WriteStaxSOAP11EndEnvelope(writer)
      CALL consultarSaldoPreliminarHTTPReq.endXmlRequest(writer)
    CATCH
      LET wsstatus = status
      CALL WSHelper.WSHelper_FillSOAP11WSError("Client",sqlca.sqlerrm)
      LET consultarSaldoPreliminarHTTPReq = NULL
      RETURN wsstatus
    END TRY

  #
  # PROCESS RESPONSE
  #
  TRY
    LET consultarSaldoPreliminarHTTPResp = consultarSaldoPreliminarHTTPReq.getAsyncResponse()
    RETURN 0 # SUCCESS
  CATCH
    LET wsstatus = status
    CALL WSHelper.WSHelper_FillSOAP11WSError("Server",sqlca.sqlerrm)
    LET consultarSaldoPreliminarHTTPReq = NULL
    RETURN wsstatus
  END TRY
END FUNCTION


FUNCTION consultarSaldoPreliminarResponse_g()
  DEFINE wsstatus        INTEGER
  DEFINE fault           BOOLEAN
  DEFINE nb              INTEGER
  DEFINE uri             STRING
  DEFINE setcookie       STRING
  DEFINE mustUnderstand  INTEGER
  DEFINE reader          xml.StaxReader

  LET fault = FALSE
  LET wsstatus = -1

  LET uri = com.WebServiceEngine.GetOption("SoapModuleURI")
  #
  # CHECK PREVIOUS CALL  
  #
  IF consultarSaldoPreliminarHTTPReq IS NULL THEN
    # No request was sent
    CALL WSHelper.WSHelper_FillSOAP11WSError("Client","No request has been sent")
    RETURN -1
  END IF

  TRY
    #
    # PROCESS RESPONSE
    #
    IF consultarSaldoPreliminarHTTPResp IS NULL THEN
      # Still no response, try again
      LET consultarSaldoPreliminarHTTPResp = consultarSaldoPreliminarHTTPReq.getAsyncResponse()
    END IF

    IF consultarSaldoPreliminarHTTPResp IS NULL THEN
      # We got no response, still waiting for
      CALL WSHelper.WSHelper_FillSOAP11WSError("Client","Response was not yet received")
      RETURN -2
    END IF

      #
      # RETRIEVE SERVICE SESSION COOKIE
      #
      LET setcookie = consultarSaldoPreliminarHTTPResp.getHeader("Set-Cookie")
      IF setcookie IS NOT NULL THEN
        LET SaldoPreliminarIssste_SaldoPreliminarIssstePortEndpoint.Binding.Cookie = WSHelper.WSHelper_ExtractServerCookie(setcookie,SaldoPreliminarIssste_SaldoPreliminarIssstePortEndpoint.Address.Uri)
      END IF

      #
      # RETRIEVE HTTP RESPONSE Headers
      #
      CALL WSHelper.WSHelper_SetResponseHeaders(consultarSaldoPreliminarHTTPResp, SaldoPreliminarIssste_SaldoPreliminarIssstePortEndpoint.Binding.Response.Headers)
      CASE
        WHEN consultarSaldoPreliminarHTTPResp.getStatusCode()==200 OR consultarSaldoPreliminarHTTPResp.getStatusCode()==500
          #
          # STAX SOAP RESPONSE OR FAULT
          #
          LET reader = consultarSaldoPreliminarHTTPResp.beginXmlResponse() # Begin Streaming Response
          IF NOT WSHelper.WSHelper_ReadStaxSOAP11StartEnvelope(reader) THEN
            EXIT CASE
          END IF
          # Process SOAP headers 
          LET nb = 0
          IF WSHelper.WSHelper_CheckStaxSOAP11Header(reader) AND NOT reader.isEmptyElement() THEN
            CALL reader.nextTag()
            WHILE (reader.getEventType()=="START_ELEMENT")
              IF WSHelper.WSHelper_CheckStaxSOAP11HeaderActor(reader,uri) THEN
                LET mustUnderstand = WSHelper.WSHelper_GetStaxSOAP11HeaderMustUnderstand(reader)
                IF mustUnderstand = -1 THEN
                  CALL WSHelper.WSHelper_FillSOAP11WSError("Client","Invalid mustUnderstand value")
                  EXIT CASE
                END IF
                #
                # STAX SOAP RESPONSE HEADER DESERIALIZE
                #
                IF mustUnderstand THEN
                  CALL WSHelper.WSHelper_FillSOAP11WSError("MustUnderstand","Mandatory header block not understood")
                  EXIT CASE
                ELSE
                  CALL reader.nextSibling() # Skip header, not necessary
                END IF
              ELSE
                CALL reader.nextSibling() # Skip header, not intended to us
              END IF
            END WHILE
            IF NOT WSHelper.WSHelper_CheckStaxSOAP11Header(reader) THEN
              CALL WSHelper.WSHelper_FillSOAP11WSError("Client","No ending header tag found")
              EXIT CASE
            ELSE
              CALL reader.nextTag()
            END IF
          ELSE
            IF reader.isEmptyElement() THEN
              CALL reader.nextTag()
            END IF
          END IF
          IF NOT WSHelper.WSHelper_ReadStaxSOAP11StartBody(reader) THEN
            EXIT CASE
          END IF
          IF WSHelper.WSHelper_CheckStaxSOAP11StartFault(reader) THEN # Handle SOAP Fault
            LET fault = TRUE
            CALL reader.nextTag()
            IF NOT WSHelper.WSHelper_ReadStaxSOAP11FaultUntilDetail(reader) THEN
              EXIT CASE
            END IF
            IF WSHelper.WSHelper_CheckStaxSOAP11FaultDetail(reader) THEN
              #
              # STAX SOAP FAULT DESERIALIZE
              #
              CALL reader.nextSibling() # Skip SOAP detail
            END IF
            IF NOT WSHelper.WSHelper_ReadStaxSOAP11EndFault(reader) THEN
              EXIT CASE
            END IF
          ELSE # Handle SOAP Response
            IF nb != 0 THEN # Check mandatory headers
              CALL WSHelper.WSHelper_FillSOAP11WSError("Client","Headers are missing")
              EXIT CASE
            END IF
            IF NOT WSHelper.WSHelper_RetrieveStaxSOAP11Message(reader) THEN
              EXIT CASE
            END IF
            #
            # STAX SOAP RESPONSE DESERIALIZE
            #
            CALL xml.Serializer.StaxToVariable(reader,ns1consultarSaldoPreliminarResponse)
          END IF
          IF NOT WSHelper.WSHelper_ReadStaxSOAP11EndBody(reader) THEN
            EXIT CASE
          END IF
          IF NOT WSHelper.WSHelper_ReadStaxSOAP11EndEnvelope(reader) THEN
            EXIT CASE
          END IF
          # End Streaming Response
          CALL consultarSaldoPreliminarHTTPResp.endXmlResponse(reader)
          IF NOT fault THEN
            LET wsstatus = 0
          END IF

        OTHERWISE
          CALL WSHelper.WSHelper_FillSOAP11WSError("Server","HTTP Error "||consultarSaldoPreliminarHTTPResp.getStatusCode()||" ("||consultarSaldoPreliminarHTTPResp.getStatusDescription()||")")

      END CASE
    CATCH
      LET wsstatus = status
      CALL WSHelper.WSHelper_FillSOAP11WSError("Server",sqlca.sqlerrm)
    END TRY

  #
  # RESET VARIABLES
  #
  LET consultarSaldoPreliminarHTTPReq = NULL
  LET consultarSaldoPreliminarHTTPResp = NULL
  RETURN wsstatus

END FUNCTION


