#-------------------------------------------------------------------------------
# File: clienteCNSF.4gl
# GENERATED BY fglwsdl 202210171337
#-------------------------------------------------------------------------------
# THIS FILE WAS GENERATED. DO NOT MODIFY.
#-------------------------------------------------------------------------------


IMPORT FGL WSHelper
IMPORT com
IMPORT xml
#-------------------------------------------------------------------------------
# Service: ISucWebSWISservice
# Port:    ISucWebSWISPort
# Server:  http://172.16.5.196:10110/SucWebSWIS.dll/soap/ISucWebSWIS
#-------------------------------------------------------------------------------
#
# Location of the SOAP endpoint.
# You can reassign this value at run-time.
#
PUBLIC DEFINE ISucWebSWISservice_ISucWebSWISPortEndpoint WSHelper.tGlobalEndpointType


#-------------------------------------------------------------------------------

# VARIABLE : WS_SAOR_ISSSTE
PUBLIC DEFINE WS_SAOR_ISSSTE RECORD ATTRIBUTE(XMLSequence,XMLName="WS_SAOR_ISSSTE",XMLNamespace="urn:SucWebSWISIntf-ISucWebSWIS",XMLNillable)
         usuario STRING ATTRIBUTE(XMLNamespace="",XMLNillable),
         password STRING ATTRIBUTE(XMLNamespace="",XMLNillable),
         proceso INTEGER ATTRIBUTE(XMLNamespace="",XMLNillable),
         Prospecto STRING ATTRIBUTE(XMLNamespace="",XMLNillable),
         Beneficiarios STRING ATTRIBUTE(XMLNamespace="",XMLNillable)
       END RECORD


#-------------------------------------------------------------------------------

# VARIABLE : WS_SAOR_ISSSTEResponse
PUBLIC DEFINE WS_SAOR_ISSSTEResponse RECORD ATTRIBUTE(XMLSequence,XMLName="WS_SAOR_ISSSTEResponse",XMLNamespace="urn:SucWebSWISIntf-ISucWebSWIS",XMLNillable)
         Respuesta STRING ATTRIBUTE(XMLNamespace="",XMLNillable)
       END RECORD



# end of service types
#-------------------------------------------------------------------------------

# Start service implementation
#-------------------------------------------------------------------------------
# Service: ISucWebSWISservice
# Port:    ISucWebSWISPort
# Server:  http://172.16.5.196:10110/SucWebSWIS.dll/soap/ISucWebSWIS
#-------------------------------------------------------------------------------

PRIVATE DEFINE WS_SAOR_ISSSTEHTTPReq     com.HttpRequest
PRIVATE DEFINE WS_SAOR_ISSSTEHTTPResp    com.HttpResponse

#-------------------------------------------------------------------------------

#
# Operation: WS_SAOR_ISSSTE
#

#
# FUNCTION: WS_SAOR_ISSSTE
#
FUNCTION WS_SAOR_ISSSTE(p_usuario, p_password, p_proceso, p_Prospecto, p_Beneficiarios)
  DEFINE	p_usuario		STRING
  DEFINE	p_password		STRING
  DEFINE	p_proceso		INTEGER
  DEFINE	p_Prospecto		STRING
  DEFINE	p_Beneficiarios		STRING
  DEFINE	soapStatus		INTEGER


  LET WS_SAOR_ISSSTE.usuario = p_usuario
  LET WS_SAOR_ISSSTE.password = p_password
  LET WS_SAOR_ISSSTE.proceso = p_proceso
  LET WS_SAOR_ISSSTE.Prospecto = p_Prospecto
  LET WS_SAOR_ISSSTE.Beneficiarios = p_Beneficiarios

  LET soapStatus = WS_SAOR_ISSSTE_g()

  RETURN soapStatus, WS_SAOR_ISSSTEResponse.Respuesta
END FUNCTION

#
# FUNCTION: WS_SAOR_ISSSTE_g
#   RETURNING: soapStatus
#   INPUT:  WS_SAOR_ISSSTE
#   OUTPUT:  WS_SAOR_ISSSTEResponse
#
FUNCTION WS_SAOR_ISSSTE_g()
  DEFINE wsstatus   INTEGER
  DEFINE retryAuth  INTEGER
  DEFINE retryProxy INTEGER
  DEFINE retry      INTEGER
  DEFINE nb         INTEGER
  DEFINE uri        STRING
  DEFINE setcookie  STRING
  DEFINE mustUnderstand INTEGER
  DEFINE request    com.HttpRequest
  DEFINE response   com.HttpResponse
  DEFINE writer     xml.DomDocument
  DEFINE reader     xml.DomDocument
  DEFINE envelope   xml.DomNode
  DEFINE header     xml.DomNode
  DEFINE body       xml.DomNode
  DEFINE node       xml.DomNode

  #
  # INIT VARIABLES
  #
  LET wsstatus = -1
  LET retryAuth = FALSE
  LET retryProxy = FALSE
  LET retry = TRUE
  LET uri = com.WebServiceEngine.GetOption("SoapModuleURI")

  #IF ISucWebSWISservice_ISucWebSWISPortEndpoint.Address.Uri IS NULL THEN
  #  LET ISucWebSWISservice_ISucWebSWISPortEndpoint.Address.Uri = "http://172.16.5.196:10110/SucWebSWIS.dll/soap/ISucWebSWIS"
  #END IF

  #
  # CREATE REQUEST
  #
  TRY
    LET request = com.HttpRequest.Create(ISucWebSWISservice_ISucWebSWISPortEndpoint.Address.Uri)
    CALL request.setMethod("POST")
    CALL request.setCharset("UTF-8")
    CALL request.setHeader("SOAPAction","\"urn:SucWebSWISIntf-ISucWebSWIS#WS_SAOR_ISSSTE\"")
    CALL WSHelper.WSHelper_SetRequestHeaders(request, ISucWebSWISservice_ISucWebSWISPortEndpoint.Binding.Request.Headers)
    IF ISucWebSWISservice_ISucWebSWISPortEndpoint.Binding.Version IS NOT NULL THEN
      CALL request.setVersion(ISucWebSWISservice_ISucWebSWISPortEndpoint.Binding.Version)
    END IF
    IF ISucWebSWISservice_ISucWebSWISPortEndpoint.Binding.Cookie IS NOT NULL THEN
      CALL request.setHeader("Cookie",ISucWebSWISservice_ISucWebSWISPortEndpoint.Binding.Cookie)
    END IF
    IF ISucWebSWISservice_ISucWebSWISPortEndpoint.Binding.ConnectionTimeout <> 0 THEN
      CALL request.setConnectionTimeOut(ISucWebSWISservice_ISucWebSWISPortEndpoint.Binding.ConnectionTimeout)
    END IF
    IF ISucWebSWISservice_ISucWebSWISPortEndpoint.Binding.ReadWriteTimeout <> 0 THEN
      CALL request.setTimeOut(ISucWebSWISservice_ISucWebSWISPortEndpoint.Binding.ReadWriteTimeout)
    END IF
    IF ISucWebSWISservice_ISucWebSWISPortEndpoint.Binding.CompressRequest IS NOT NULL THEN
      CALL request.setHeader("Content-Encoding",ISucWebSWISservice_ISucWebSWISPortEndpoint.Binding.CompressRequest)
    END IF
    CALL request.setHeader("Accept-Encoding","gzip, deflate")
  CATCH
    LET wsstatus = status
    CALL WSHelper.WSHelper_FillSOAP11WSError("Client","Cannot create HTTPRequest")
    RETURN wsstatus
  END TRY

  # START LOOP
  WHILE retry
    LET retry = FALSE

    #
    # DOM Request
    #

    TRY
      # Building SOAP11 envelope
      LET writer = xml.DomDocument.Create()
      LET envelope = WSHelper.WSHelper_BuildSOAP11Envelope(writer)
      CALL writer.appendDocumentNode(envelope)
      LET body = WSHelper.WSHelper_BuildSOAP11Body(writer)
      CALL envelope.appendChild(body)
      #
      # DOM SOAP REQUEST SERIALIZE
      #
      CALL xml.Serializer.VariableToSoapSection5(WS_SAOR_ISSSTE,body)

      # Send SOAP envelope
      CALL request.doXmlRequest(writer)
    CATCH
      LET wsstatus = status
      CALL WSHelper.WSHelper_FillSOAP11WSError("Client",sqlca.sqlerrm)
      RETURN wsstatus
    END TRY

    #
    # PROCESS RESPONSE
    #
    TRY
      LET response = request.getResponse()

      #
      # RETRIEVE SERVICE SESSION COOKIE
      #
      LET setcookie = response.getHeader("Set-Cookie")
      IF setcookie IS NOT NULL THEN
        LET ISucWebSWISservice_ISucWebSWISPortEndpoint.Binding.Cookie = WSHelper.WSHelper_ExtractServerCookie(setcookie,ISucWebSWISservice_ISucWebSWISPortEndpoint.Address.Uri)
      END IF

      #
      # RETRIEVE HTTP RESPONSE Headers
      #
      CALL WSHelper.WSHelper_SetResponseHeaders(response, ISucWebSWISservice_ISucWebSWISPortEndpoint.Binding.Response.Headers)

      CASE
        WHEN response.getStatusCode()==200 OR response.getStatusCode()==500
          #
          # DOM SOAP RESPONSE OR FAULT
          #
          LET reader = response.getXmlResponse()
          LET envelope = WSHelper.WSHelper_RetrieveSOAP11Envelope(reader)
          IF envelope IS NULL THEN
            EXIT CASE
          END IF
          LET header = WSHelper.WSHelper_CheckSOAP11Header(envelope)
          LET body = WSHelper.WSHelper_RetrieveSOAP11Body(envelope,header)
          IF body IS NULL THEN
            EXIT CASE
          END IF
          IF WSHelper.WSHelper_IsSOAP11Fault(body.getFirstChildElement()) THEN
            #
            # DOM SOAP FAULT
            #
            # Handle SOAP headers
            IF header IS NOT NULL THEN
              LET node = header.getFirstChildElement()
              WHILE (node IS NOT NULL)
                IF WSHelper.WSHelper_CheckSOAP11HeaderActor(node,uri) THEN
                  LET mustUnderstand = WSHelper.WSHelper_GetSOAP11HeaderMustUnderstand(node)
                  IF mustUnderstand = -1 THEN
                    CALL WSHelper.WSHelper_FillSOAP11WSError("Client","Invalid mustUnderstand value")
                    EXIT CASE
                  END IF
                  IF mustUnderstand THEN
                    CALL WSHelper.WSHelper_FillSOAP11WSError("MustUnderstand","Mandatory header block not understood")
                    EXIT CASE
                  ELSE
                    LET node = node.getNextSiblingElement() # Skip header, not mandatory
                  END IF
                ELSE
                  LET node = node.getNextSiblingElement() # Skip header, not intended to us
                END IF
              END WHILE
            END IF
            CALL WSHelper.WSHelper_CheckSOAP11Fault(body.getFirstChildElement())
          ELSE
            #
            # DOM SOAP RESPONSE
            #
            # Handle SOAP headers
            IF header IS NOT NULL THEN
              LET node = header.getFirstChildElement()
              LET nb = 0
              WHILE (node IS NOT NULL)
                IF WSHelper.WSHelper_CheckSOAP11HeaderActor(node,uri) THEN
                  LET mustUnderstand = WSHelper.WSHelper_GetSOAP11HeaderMustUnderstand(node)
                  IF mustUnderstand = -1 THEN
                    CALL WSHelper.WSHelper_FillSOAP11WSError("Client","Invalid mustUnderstand value")
                    EXIT CASE
                  END IF
                  #
                  # DOM SOAP RESPONSE HEADER DESERIALIZE
                  #
                  IF mustUnderstand THEN
                    CALL WSHelper.WSHelper_FillSOAP11WSError("MustUnderstand","Mandatory header block not understood")
                    EXIT CASE
                  ELSE
                    LET node = node.getNextSiblingElement() # Skip header, not mandatory
                  END IF
                ELSE
                  LET node = node.getNextSiblingElement() # Skip header, not intended to us
                END IF
              END WHILE
              IF nb != 0 THEN
                CALL WSHelper.WSHelper_FillSOAP11WSError("Client","One or more headers are missing")
                EXIT CASE
              END IF
            END IF
            IF body IS NOT NULL THEN
              # Check message
              LET node = WSHelper.WSHelper_RetrieveSOAP11Message(body)
              IF node IS NOT NULL THEN
                #
                # DOM SOAP RESPONSE DESERIALIZE
                #
                CALL xml.Serializer.SoapSection5ToVariable(node,WS_SAOR_ISSSTEResponse)
                LET wsstatus = 0
              END IF
            END IF
          END IF

        WHEN response.getStatusCode()==401 # HTTP Authentication
          IF retryAuth THEN
            CALL WSHelper.WSHelper_FillSOAP11WSError("Server","HTTP Error 401 ("||response.getStatusDescription()||")")
          ELSE
            LET retryAuth = TRUE
            LET retry = TRUE
          END IF

        WHEN response.getStatusCode()==407 # Proxy Authentication
          IF retryProxy THEN
            CALL WSHelper.WSHelper_FillSOAP11WSError("Server","HTTP Error 407 ("||response.getStatusDescription()||")")
          ELSE
            LET retryProxy = TRUE
            LET retry = TRUE
          END IF

        OTHERWISE
          CALL WSHelper.WSHelper_FillSOAP11WSError("Server","HTTP Error "||response.getStatusCode()||" ("||response.getStatusDescription()||")")

      END CASE
    CATCH
      LET wsstatus = status
      CALL WSHelper.WSHelper_FillSOAP11WSError("Server",sqlca.sqlerrm)
      RETURN wsstatus
    END TRY

  # END LOOP
  END WHILE

  RETURN wsstatus

END FUNCTION


FUNCTION WS_SAOR_ISSSTERequest_g()
  DEFINE wsstatus   INTEGER
  DEFINE writer     xml.DomDocument
  DEFINE envelope   xml.DomNode
  DEFINE header     xml.DomNode
  DEFINE body       xml.DomNode

  #
  # CHECK PREVIOUS CALL  
  #
  IF WS_SAOR_ISSSTEHTTPReq IS NOT NULL AND WS_SAOR_ISSSTEHTTPResp IS NULL THEN
    # Request was sent but there was no response yet
    CALL WSHelper.WSHelper_FillSOAP11WSError("Client","Cannot issue a new request until previous response was received")
    RETURN -2 # waiting for the response
  ELSE
    #IF ISucWebSWISservice_ISucWebSWISPortEndpoint.Address.Uri IS NULL THEN
    #  LET ISucWebSWISservice_ISucWebSWISPortEndpoint.Address.Uri = "http://172.16.5.196:10110/SucWebSWIS.dll/soap/ISucWebSWIS"
    #END IF
  END IF

  #
  # CREATE REQUEST
  #
  TRY
    LET WS_SAOR_ISSSTEHTTPReq = com.HttpRequest.Create(ISucWebSWISservice_ISucWebSWISPortEndpoint.Address.Uri)
    CALL WS_SAOR_ISSSTEHTTPReq.setMethod("POST")
    CALL WS_SAOR_ISSSTEHTTPReq.setCharset("UTF-8")
    CALL WS_SAOR_ISSSTEHTTPReq.setHeader("SOAPAction","\"urn:SucWebSWISIntf-ISucWebSWIS#WS_SAOR_ISSSTE\"")
    CALL WSHelper.WSHelper_SetRequestHeaders(WS_SAOR_ISSSTEHTTPReq, ISucWebSWISservice_ISucWebSWISPortEndpoint.Binding.Request.Headers)
    IF ISucWebSWISservice_ISucWebSWISPortEndpoint.Binding.Version IS NOT NULL THEN
      CALL WS_SAOR_ISSSTEHTTPReq.setVersion(ISucWebSWISservice_ISucWebSWISPortEndpoint.Binding.Version)
    END IF
    IF ISucWebSWISservice_ISucWebSWISPortEndpoint.Binding.Cookie IS NOT NULL THEN
      CALL WS_SAOR_ISSSTEHTTPReq.setHeader("Cookie",ISucWebSWISservice_ISucWebSWISPortEndpoint.Binding.Cookie)
    END IF
    IF ISucWebSWISservice_ISucWebSWISPortEndpoint.Binding.ConnectionTimeout <> 0 THEN
      CALL WS_SAOR_ISSSTEHTTPReq.setConnectionTimeOut(ISucWebSWISservice_ISucWebSWISPortEndpoint.Binding.ConnectionTimeout)
    END IF
    IF ISucWebSWISservice_ISucWebSWISPortEndpoint.Binding.ReadWriteTimeout <> 0 THEN
      CALL WS_SAOR_ISSSTEHTTPReq.setTimeOut(ISucWebSWISservice_ISucWebSWISPortEndpoint.Binding.ReadWriteTimeout)
    END IF
    IF ISucWebSWISservice_ISucWebSWISPortEndpoint.Binding.CompressRequest IS NOT NULL THEN
      CALL WS_SAOR_ISSSTEHTTPReq.setHeader("Content-Encoding",ISucWebSWISservice_ISucWebSWISPortEndpoint.Binding.CompressRequest)
    END IF
    CALL WS_SAOR_ISSSTEHTTPReq.setHeader("Accept-Encoding","gzip, deflate")
  CATCH
    LET wsstatus = status
    CALL WSHelper.WSHelper_FillSOAP11WSError("Client","Cannot create HTTPRequest")
    LET WS_SAOR_ISSSTEHTTPReq = NULL
    RETURN wsstatus
  END TRY

    #
    # DOM Request
    #

    TRY
      # Building SOAP11 envelope
      LET writer = xml.DomDocument.Create()
      LET envelope = WSHelper.WSHelper_BuildSOAP11Envelope(writer)
      CALL writer.appendDocumentNode(envelope)
      LET body = WSHelper.WSHelper_BuildSOAP11Body(writer)
      CALL envelope.appendChild(body)
      #
      # DOM SOAP REQUEST SERIALIZE
      #
      CALL xml.Serializer.VariableToSoapSection5(WS_SAOR_ISSSTE,body)

      # Send SOAP envelope
      CALL WS_SAOR_ISSSTEHTTPReq.doXmlRequest(writer)
    CATCH
      LET wsstatus = status
      CALL WSHelper.WSHelper_FillSOAP11WSError("Client",sqlca.sqlerrm)
      LET WS_SAOR_ISSSTEHTTPReq = NULL
      RETURN wsstatus
    END TRY

  #
  # PROCESS RESPONSE
  #
  TRY
    LET WS_SAOR_ISSSTEHTTPResp = WS_SAOR_ISSSTEHTTPReq.getAsyncResponse()
    RETURN 0 # SUCCESS
  CATCH
    LET wsstatus = status
    CALL WSHelper.WSHelper_FillSOAP11WSError("Server",sqlca.sqlerrm)
    LET WS_SAOR_ISSSTEHTTPReq = NULL
    RETURN wsstatus
  END TRY
END FUNCTION


FUNCTION WS_SAOR_ISSSTEResponse_g()
  DEFINE wsstatus        INTEGER
  DEFINE nb              INTEGER
  DEFINE uri             STRING
  DEFINE setcookie       STRING
  DEFINE mustUnderstand  INTEGER
  DEFINE reader          xml.DomDocument
  DEFINE envelope        xml.DomNode
  DEFINE header          xml.DomNode
  DEFINE body            xml.DomNode
  DEFINE node            xml.DomNode

  LET wsstatus = -1

  LET uri = com.WebServiceEngine.GetOption("SoapModuleURI")
  #
  # CHECK PREVIOUS CALL  
  #
  IF WS_SAOR_ISSSTEHTTPReq IS NULL THEN
    # No request was sent
    CALL WSHelper.WSHelper_FillSOAP11WSError("Client","No request has been sent")
    RETURN -1
  END IF

  TRY
    #
    # PROCESS RESPONSE
    #
    IF WS_SAOR_ISSSTEHTTPResp IS NULL THEN
      # Still no response, try again
      LET WS_SAOR_ISSSTEHTTPResp = WS_SAOR_ISSSTEHTTPReq.getAsyncResponse()
    END IF

    IF WS_SAOR_ISSSTEHTTPResp IS NULL THEN
      # We got no response, still waiting for
      CALL WSHelper.WSHelper_FillSOAP11WSError("Client","Response was not yet received")
      RETURN -2
    END IF

      #
      # RETRIEVE SERVICE SESSION COOKIE
      #
      LET setcookie = WS_SAOR_ISSSTEHTTPResp.getHeader("Set-Cookie")
      IF setcookie IS NOT NULL THEN
        LET ISucWebSWISservice_ISucWebSWISPortEndpoint.Binding.Cookie = WSHelper.WSHelper_ExtractServerCookie(setcookie,ISucWebSWISservice_ISucWebSWISPortEndpoint.Address.Uri)
      END IF

      #
      # RETRIEVE HTTP RESPONSE Headers
      #
      CALL WSHelper.WSHelper_SetResponseHeaders(WS_SAOR_ISSSTEHTTPResp, ISucWebSWISservice_ISucWebSWISPortEndpoint.Binding.Response.Headers)
      CASE
        WHEN WS_SAOR_ISSSTEHTTPResp.getStatusCode()==200 OR WS_SAOR_ISSSTEHTTPResp.getStatusCode()==500
          #
          # DOM SOAP RESPONSE OR FAULT
          #
          LET reader = WS_SAOR_ISSSTEHTTPResp.getXmlResponse()
          LET envelope = WSHelper.WSHelper_RetrieveSOAP11Envelope(reader)
          IF envelope IS NULL THEN
            EXIT CASE
          END IF
          LET header = WSHelper.WSHelper_CheckSOAP11Header(envelope)
          LET body = WSHelper.WSHelper_RetrieveSOAP11Body(envelope,header)
          IF body IS NULL THEN
            EXIT CASE
          END IF
          IF WSHelper.WSHelper_IsSOAP11Fault(body.getFirstChildElement()) THEN
            #
            # DOM SOAP FAULT
            #
            # Handle SOAP headers
            IF header IS NOT NULL THEN
              LET node = header.getFirstChildElement()
              WHILE (node IS NOT NULL)
                IF WSHelper.WSHelper_CheckSOAP11HeaderActor(node,uri) THEN
                  LET mustUnderstand = WSHelper.WSHelper_GetSOAP11HeaderMustUnderstand(node)
                  IF mustUnderstand = -1 THEN
                    CALL WSHelper.WSHelper_FillSOAP11WSError("Client","Invalid mustUnderstand value")
                    EXIT CASE
                  END IF
                  IF mustUnderstand THEN
                    CALL WSHelper.WSHelper_FillSOAP11WSError("MustUnderstand","Mandatory header block not understood")
                    EXIT CASE
                  ELSE
                    LET node = node.getNextSiblingElement() # Skip header, not mandatory
                  END IF
                ELSE
                  LET node = node.getNextSiblingElement() # Skip header, not intended to us
                END IF
              END WHILE
            END IF
            CALL WSHelper.WSHelper_CheckSOAP11Fault(body.getFirstChildElement())
          ELSE
            #
            # DOM SOAP RESPONSE
            #
            # Handle SOAP headers
            IF header IS NOT NULL THEN
              LET node = header.getFirstChildElement()
              LET nb = 0
              WHILE (node IS NOT NULL)
                IF WSHelper.WSHelper_CheckSOAP11HeaderActor(node,uri) THEN
                  LET mustUnderstand = WSHelper.WSHelper_GetSOAP11HeaderMustUnderstand(node)
                  IF mustUnderstand = -1 THEN
                    CALL WSHelper.WSHelper_FillSOAP11WSError("Client","Invalid mustUnderstand value")
                    EXIT CASE
                  END IF
                  #
                  # DOM SOAP RESPONSE HEADER DESERIALIZE
                  #
                  IF mustUnderstand THEN
                    CALL WSHelper.WSHelper_FillSOAP11WSError("MustUnderstand","Mandatory header block not understood")
                    EXIT CASE
                  ELSE
                    LET node = node.getNextSiblingElement() # Skip header, not mandatory
                  END IF
                ELSE
                  LET node = node.getNextSiblingElement() # Skip header, not intended to us
                END IF
              END WHILE
              IF nb != 0 THEN
                CALL WSHelper.WSHelper_FillSOAP11WSError("Client","One or more headers are missing")
                EXIT CASE
              END IF
            END IF
            IF body IS NOT NULL THEN
              # Check message
              LET node = WSHelper.WSHelper_RetrieveSOAP11Message(body)
              IF node IS NOT NULL THEN
                #
                # DOM SOAP RESPONSE DESERIALIZE
                #
                CALL xml.Serializer.SoapSection5ToVariable(node,WS_SAOR_ISSSTEResponse)
                LET wsstatus = 0
              END IF
            END IF
          END IF

        OTHERWISE
          CALL WSHelper.WSHelper_FillSOAP11WSError("Server","HTTP Error "||WS_SAOR_ISSSTEHTTPResp.getStatusCode()||" ("||WS_SAOR_ISSSTEHTTPResp.getStatusDescription()||")")

      END CASE
    CATCH
      LET wsstatus = status
      CALL WSHelper.WSHelper_FillSOAP11WSError("Server",sqlca.sqlerrm)
    END TRY

  #
  # RESET VARIABLES
  #
  LET WS_SAOR_ISSSTEHTTPReq = NULL
  LET WS_SAOR_ISSSTEHTTPResp = NULL
  RETURN wsstatus

END FUNCTION


