#-------------------------------------------------------------------------------
# File: ConsultaPorCurpService_ConsultaPorCurpServiceHttpsSoap12Endpoint.4gl
# GENERATED BY fglwsdl 202210171337
#-------------------------------------------------------------------------------
# THIS FILE WAS GENERATED. DO NOT MODIFY.
#-------------------------------------------------------------------------------


IMPORT FGL WSHelper
IMPORT com
IMPORT XML

#
#-------------------------------------------------------------------------------
# XML Type definitions 
#-------------------------------------------------------------------------------
#

#
# TYPE : tns1DatosConsultaCurp
#
PUBLIC TYPE tns1DatosConsultaCurp RECORD ATTRIBUTE(XMLSequence,XSTypeName="DatosConsultaCurp",XSTypeNamespace="http://services.wserv.ecurp.dgti.segob.gob.mx/xsd")
  cveCurp STRING ATTRIBUTE(XMLOptional,XMLNillable),
  cveEntidadEmisora STRING ATTRIBUTE(XMLOptional,XMLNillable),
  direccionIp STRING ATTRIBUTE(XMLOptional,XMLNillable),
  password STRING ATTRIBUTE(XMLOptional,XMLNillable),
  tipoTransaccion INTEGER ATTRIBUTE(XMLOptional),
  usuario STRING ATTRIBUTE(XMLOptional,XMLNillable)
END RECORD
#-------------------------------------------------------------------------------



#-------------------------------------------------------------------------------
# Service: ConsultaPorCurpService
# Port:    ConsultaPorCurpServiceHttpsSoap12Endpoint
# Server:  https://webs.curp.gob.mx:8443/WebServicesConsulta/services/ConsultaPorCurpService.ConsultaPorCurpServiceHttpsSoap12Endpoint/
#-------------------------------------------------------------------------------
#
# Location of the SOAP endpoint.
# You can reassign this value at run-time.
#
PUBLIC DEFINE ConsultaPorCurpService_ConsultaPorCurpServiceHttpsSoap12EndpointEndpoint WSHelper.tGlobalEndpointType


#-------------------------------------------------------------------------------

# VARIABLE : ns2getConfirm
PUBLIC DEFINE ns2getConfirm RECORD ATTRIBUTE(XMLSequence,XMLName="getConfirm",XMLNamespace="http://services.wserv.ecurp.dgti.segob.gob.mx")
         sessionID STRING ATTRIBUTE(XMLOptional,XMLNillable),
         Mssg STRING ATTRIBUTE(XMLOptional,XMLNillable)
       END RECORD


#-------------------------------------------------------------------------------

# VARIABLE : ns2consultarPorCurp
PUBLIC DEFINE ns2consultarPorCurp RECORD ATTRIBUTE(XMLSequence,XMLName="consultarPorCurp",XMLNamespace="http://services.wserv.ecurp.dgti.segob.gob.mx")
         datos tns1DatosConsultaCurp ATTRIBUTE(XMLOptional,XMLNillable)
       END RECORD


#-------------------------------------------------------------------------------

# VARIABLE : ns2consultarPorCurpResponse
PUBLIC DEFINE ns2consultarPorCurpResponse RECORD ATTRIBUTE(XMLSequence,XMLName="consultarPorCurpResponse",XMLNamespace="http://services.wserv.ecurp.dgti.segob.gob.mx")
         return STRING ATTRIBUTE(XMLOptional,XMLNillable)
       END RECORD



# end of service types
#-------------------------------------------------------------------------------

# Start service implementation
#-------------------------------------------------------------------------------
# Service: ConsultaPorCurpService
# Port:    ConsultaPorCurpServiceHttpsSoap12Endpoint
# Server:  https://webs.curp.gob.mx:8443/WebServicesConsulta/services/ConsultaPorCurpService.ConsultaPorCurpServiceHttpsSoap12Endpoint/
#-------------------------------------------------------------------------------

PRIVATE DEFINE getConfirmHTTPReq     com.HttpRequest

PRIVATE DEFINE consultarPorCurpHTTPReq     com.HttpRequest
PRIVATE DEFINE consultarPorCurpHTTPResp    com.HttpResponse

#-------------------------------------------------------------------------------

#
# Operation: getConfirm
#

#
# FUNCTION: getConfirm
#
FUNCTION getConfirm(p_sessionID, p_Mssg)
  DEFINE	p_sessionID		STRING
  DEFINE	p_Mssg		STRING
  DEFINE	soapStatus		INTEGER


  LET ns2getConfirm.sessionID = p_sessionID
  LET ns2getConfirm.Mssg = p_Mssg

  LET soapStatus = getConfirm_g()

  RETURN soapStatus
END FUNCTION

#
# FUNCTION: getConfirm_g
#   RETURNING: soapStatus
#   INPUT:  ns2getConfirm
#   OUTPUT: NONE
#
FUNCTION getConfirm_g()
  DEFINE wsstatus   INTEGER
  DEFINE retryAuth  INTEGER
  DEFINE retryProxy INTEGER
  DEFINE retry      INTEGER
  DEFINE fault      BOOLEAN
  DEFINE nb         INTEGER
  DEFINE uri        STRING
  DEFINE setcookie  STRING
  DEFINE mustUnderstand INTEGER
  DEFINE request    com.HttpRequest
  DEFINE response   com.HttpResponse
  DEFINE writer     xml.StaxWriter

  #
  # INIT VARIABLES
  #
  LET wsstatus = -1
  LET retryAuth = FALSE
  LET retryProxy = FALSE
  LET retry = TRUE
  LET fault = FALSE
  LET uri = com.WebServiceEngine.GetOption("SoapModuleURI")

  #IF ConsultaPorCurpService_ConsultaPorCurpServiceHttpsSoap12EndpointEndpoint.Address.Uri IS NULL THEN
  #  LET ConsultaPorCurpService_ConsultaPorCurpServiceHttpsSoap12EndpointEndpoint.Address.Uri = "https://webs.curp.gob.mx:8443/WebServicesConsulta/services/ConsultaPorCurpService.ConsultaPorCurpServiceHttpsSoap12Endpoint/"
  #END IF

  #
  # CREATE REQUEST
  #
  TRY
    LET request = com.HttpRequest.Create(ConsultaPorCurpService_ConsultaPorCurpServiceHttpsSoap12EndpointEndpoint.Address.Uri)
    CALL request.setMethod("POST")
    CALL request.setCharset("UTF-8")
    CALL request.setHeader("Content-Type","application/soap+xml; action=\"urn:getConfirm\"")
    CALL WSHelper.WSHelper_SetRequestHeaders(request, ConsultaPorCurpService_ConsultaPorCurpServiceHttpsSoap12EndpointEndpoint.Binding.Request.Headers)
    IF ConsultaPorCurpService_ConsultaPorCurpServiceHttpsSoap12EndpointEndpoint.Binding.Version IS NOT NULL THEN
      CALL request.setVersion(ConsultaPorCurpService_ConsultaPorCurpServiceHttpsSoap12EndpointEndpoint.Binding.Version)
    END IF
    IF ConsultaPorCurpService_ConsultaPorCurpServiceHttpsSoap12EndpointEndpoint.Binding.Cookie IS NOT NULL THEN
      CALL request.setHeader("Cookie",ConsultaPorCurpService_ConsultaPorCurpServiceHttpsSoap12EndpointEndpoint.Binding.Cookie)
    END IF
    IF ConsultaPorCurpService_ConsultaPorCurpServiceHttpsSoap12EndpointEndpoint.Binding.ConnectionTimeout <> 0 THEN
      CALL request.setConnectionTimeOut(ConsultaPorCurpService_ConsultaPorCurpServiceHttpsSoap12EndpointEndpoint.Binding.ConnectionTimeout)
    END IF
    IF ConsultaPorCurpService_ConsultaPorCurpServiceHttpsSoap12EndpointEndpoint.Binding.ReadWriteTimeout <> 0 THEN
      CALL request.setTimeOut(ConsultaPorCurpService_ConsultaPorCurpServiceHttpsSoap12EndpointEndpoint.Binding.ReadWriteTimeout)
    END IF
    IF ConsultaPorCurpService_ConsultaPorCurpServiceHttpsSoap12EndpointEndpoint.Binding.CompressRequest IS NOT NULL THEN
      CALL request.setHeader("Content-Encoding",ConsultaPorCurpService_ConsultaPorCurpServiceHttpsSoap12EndpointEndpoint.Binding.CompressRequest)
    END IF
    CALL request.setHeader("Accept-Encoding","gzip, deflate")
  CATCH
    LET wsstatus = status
    CALL WSHelper.WSHelper_FillSOAP12WSError("Sender","Cannot create HTTPRequest")
    RETURN wsstatus
  END TRY

  # START LOOP
  WHILE retry
    LET retry = FALSE

    #
    # Stax request
    #
    TRY
      LET writer = request.beginXmlRequest()
      CALL WSHelper.WSHelper_WriteStaxSOAP12StartEnvelope(writer)
      CALL WSHelper.WSHelper_WriteStaxSOAP12StartBody(writer)
      #
      # STAX SOAP REQUEST SERIALIZE
      #
      CALL xml.Serializer.VariableToStax(ns2getConfirm,writer)
      CALL WSHelper.WSHelper_WriteStaxSOAP12EndBody(writer)
      CALL WSHelper.WSHelper_WriteStaxSOAP12EndEnvelope(writer)
      CALL request.endXmlRequest(writer)
    CATCH
      LET wsstatus = status
      CALL WSHelper.WSHelper_FillSOAP12WSError("Sender",sqlca.sqlerrm)
      RETURN wsstatus
    END TRY

    #
    # PROCESS RESPONSE
    #
    TRY
      LET response = request.getResponse()

      #
      # RETRIEVE SERVICE SESSION COOKIE
      #
      LET setcookie = response.getHeader("Set-Cookie")
      IF setcookie IS NOT NULL THEN
        LET ConsultaPorCurpService_ConsultaPorCurpServiceHttpsSoap12EndpointEndpoint.Binding.Cookie = WSHelper.WSHelper_ExtractServerCookie(setcookie,ConsultaPorCurpService_ConsultaPorCurpServiceHttpsSoap12EndpointEndpoint.Address.Uri)
      END IF

      #
      # RETRIEVE HTTP RESPONSE Headers
      #
      CALL WSHelper.WSHelper_SetResponseHeaders(response, ConsultaPorCurpService_ConsultaPorCurpServiceHttpsSoap12EndpointEndpoint.Binding.Response.Headers)
      CASE response.getStatusCode()

        WHEN 200 # OK
          LET wsstatus = 0

        WHEN 201 # Created
          LET wsstatus = 0

        WHEN 202 # Accepted
          LET wsstatus = 0

        WHEN 203 # Non-Authoritative Information
          LET wsstatus = 0

        WHEN 204 # No Content
          LET wsstatus = 0

        WHEN 401 # HTTP Authentication
          IF retryAuth THEN
            CALL WSHelper.WSHelper_FillSOAP12WSError("Receiver","HTTP Error 401 ("||response.getStatusDescription()||")")
          ELSE
            LET retryAuth = TRUE
            LET retry = TRUE
          END IF

        WHEN 407 # Proxy Authentication
          IF retryProxy THEN
            CALL WSHelper.WSHelper_FillSOAP12WSError("Receiver","HTTP Error 407 ("||response.getStatusDescription()||")")
          ELSE
            LET retryProxy = TRUE
            LET retry = TRUE
          END IF

        OTHERWISE
          CALL WSHelper.WSHelper_FillSOAP12WSError("Receiver","HTTP Error "||response.getStatusCode()||" ("||response.getStatusDescription()||")")

      END CASE
    CATCH
      LET wsstatus = status
      CALL WSHelper.WSHelper_FillSOAP12WSError("Receiver",sqlca.sqlerrm)
      RETURN wsstatus
    END TRY

  # END LOOP
  END WHILE

  RETURN wsstatus

END FUNCTION


FUNCTION getConfirmRequest_g()
  DEFINE wsstatus   INTEGER
  DEFINE writer     xml.StaxWriter

  #
  # CREATE REQUEST
  #
  TRY
    LET getConfirmHTTPReq = com.HttpRequest.Create(ConsultaPorCurpService_ConsultaPorCurpServiceHttpsSoap12EndpointEndpoint.Address.Uri)
    CALL getConfirmHTTPReq.setMethod("POST")
    CALL getConfirmHTTPReq.setCharset("UTF-8")
    CALL getConfirmHTTPReq.setHeader("Content-Type","application/soap+xml; action=\"urn:getConfirm\"")
    CALL WSHelper.WSHelper_SetRequestHeaders(getConfirmHTTPReq, ConsultaPorCurpService_ConsultaPorCurpServiceHttpsSoap12EndpointEndpoint.Binding.Request.Headers)
    IF ConsultaPorCurpService_ConsultaPorCurpServiceHttpsSoap12EndpointEndpoint.Binding.Version IS NOT NULL THEN
      CALL getConfirmHTTPReq.setVersion(ConsultaPorCurpService_ConsultaPorCurpServiceHttpsSoap12EndpointEndpoint.Binding.Version)
    END IF
    IF ConsultaPorCurpService_ConsultaPorCurpServiceHttpsSoap12EndpointEndpoint.Binding.Cookie IS NOT NULL THEN
      CALL getConfirmHTTPReq.setHeader("Cookie",ConsultaPorCurpService_ConsultaPorCurpServiceHttpsSoap12EndpointEndpoint.Binding.Cookie)
    END IF
    IF ConsultaPorCurpService_ConsultaPorCurpServiceHttpsSoap12EndpointEndpoint.Binding.ConnectionTimeout <> 0 THEN
      CALL getConfirmHTTPReq.setConnectionTimeOut(ConsultaPorCurpService_ConsultaPorCurpServiceHttpsSoap12EndpointEndpoint.Binding.ConnectionTimeout)
    END IF
    IF ConsultaPorCurpService_ConsultaPorCurpServiceHttpsSoap12EndpointEndpoint.Binding.ReadWriteTimeout <> 0 THEN
      CALL getConfirmHTTPReq.setTimeOut(ConsultaPorCurpService_ConsultaPorCurpServiceHttpsSoap12EndpointEndpoint.Binding.ReadWriteTimeout)
    END IF
    IF ConsultaPorCurpService_ConsultaPorCurpServiceHttpsSoap12EndpointEndpoint.Binding.CompressRequest IS NOT NULL THEN
      CALL getConfirmHTTPReq.setHeader("Content-Encoding",ConsultaPorCurpService_ConsultaPorCurpServiceHttpsSoap12EndpointEndpoint.Binding.CompressRequest)
    END IF
    CALL getConfirmHTTPReq.setHeader("Accept-Encoding","gzip, deflate")
  CATCH
    LET wsstatus = status
    CALL WSHelper.WSHelper_FillSOAP12WSError("Sender","Cannot create HTTPRequest")
    LET getConfirmHTTPReq = NULL
    RETURN wsstatus
  END TRY

    #
    # Stax request
    #
    TRY
      LET writer = getConfirmHTTPReq.beginXmlRequest()
      CALL WSHelper.WSHelper_WriteStaxSOAP12StartEnvelope(writer)
      CALL WSHelper.WSHelper_WriteStaxSOAP12StartBody(writer)
      #
      # STAX SOAP REQUEST SERIALIZE
      #
      CALL xml.Serializer.VariableToStax(ns2getConfirm,writer)
      CALL WSHelper.WSHelper_WriteStaxSOAP12EndBody(writer)
      CALL WSHelper.WSHelper_WriteStaxSOAP12EndEnvelope(writer)
      CALL getConfirmHTTPReq.endXmlRequest(writer)
    CATCH
      LET wsstatus = status
      CALL WSHelper.WSHelper_FillSOAP12WSError("Sender",sqlca.sqlerrm)
      LET getConfirmHTTPReq = NULL
      RETURN wsstatus
    END TRY

  #
  # SKIP PROCESS RESPONSE
  #
  LET getConfirmHTTPReq = NULL
  RETURN 0 # SUCCESS
END FUNCTION



#
# Operation: consultarPorCurp
#
#
# FUNCTION: consultarPorCurp_g
#   RETURNING: soapStatus
#   INPUT:  ns2consultarPorCurp
#   OUTPUT:  ns2consultarPorCurpResponse
#
FUNCTION consultarPorCurp_g()
  DEFINE wsstatus   INTEGER
  DEFINE retryAuth  INTEGER
  DEFINE retryProxy INTEGER
  DEFINE retry      INTEGER
  DEFINE fault      BOOLEAN
  DEFINE nb         INTEGER
  DEFINE uri        STRING
  DEFINE setcookie  STRING
  DEFINE mustUnderstand INTEGER
  DEFINE request    com.HttpRequest
  DEFINE response   com.HttpResponse
  DEFINE writer     xml.StaxWriter
  DEFINE reader     xml.StaxReader

  #
  # INIT VARIABLES
  #
  LET wsstatus = -1
  LET retryAuth = FALSE
  LET retryProxy = FALSE
  LET retry = TRUE
  LET fault = FALSE
  LET uri = com.WebServiceEngine.GetOption("SoapModuleURI")

  #IF ConsultaPorCurpService_ConsultaPorCurpServiceHttpsSoap12EndpointEndpoint.Address.Uri IS NULL THEN
  #  LET ConsultaPorCurpService_ConsultaPorCurpServiceHttpsSoap12EndpointEndpoint.Address.Uri = "https://webs.curp.gob.mx:8443/WebServicesConsulta/services/ConsultaPorCurpService.ConsultaPorCurpServiceHttpsSoap12Endpoint/"
  #END IF

  #
  # CREATE REQUEST
  #
  TRY
    LET request = com.HttpRequest.Create(ConsultaPorCurpService_ConsultaPorCurpServiceHttpsSoap12EndpointEndpoint.Address.Uri)
    CALL request.setMethod("POST")
    CALL request.setCharset("UTF-8")
    CALL request.setHeader("Content-Type","application/soap+xml; action=\"urn:consultarPorCurp\"")
    CALL WSHelper.WSHelper_SetRequestHeaders(request, ConsultaPorCurpService_ConsultaPorCurpServiceHttpsSoap12EndpointEndpoint.Binding.Request.Headers)
    IF ConsultaPorCurpService_ConsultaPorCurpServiceHttpsSoap12EndpointEndpoint.Binding.Version IS NOT NULL THEN
      CALL request.setVersion(ConsultaPorCurpService_ConsultaPorCurpServiceHttpsSoap12EndpointEndpoint.Binding.Version)
    END IF
    IF ConsultaPorCurpService_ConsultaPorCurpServiceHttpsSoap12EndpointEndpoint.Binding.Cookie IS NOT NULL THEN
      CALL request.setHeader("Cookie",ConsultaPorCurpService_ConsultaPorCurpServiceHttpsSoap12EndpointEndpoint.Binding.Cookie)
    END IF
    IF ConsultaPorCurpService_ConsultaPorCurpServiceHttpsSoap12EndpointEndpoint.Binding.ConnectionTimeout <> 0 THEN
      CALL request.setConnectionTimeOut(ConsultaPorCurpService_ConsultaPorCurpServiceHttpsSoap12EndpointEndpoint.Binding.ConnectionTimeout)
    END IF
    IF ConsultaPorCurpService_ConsultaPorCurpServiceHttpsSoap12EndpointEndpoint.Binding.ReadWriteTimeout <> 0 THEN
      CALL request.setTimeOut(ConsultaPorCurpService_ConsultaPorCurpServiceHttpsSoap12EndpointEndpoint.Binding.ReadWriteTimeout)
    END IF
    IF ConsultaPorCurpService_ConsultaPorCurpServiceHttpsSoap12EndpointEndpoint.Binding.CompressRequest IS NOT NULL THEN
      CALL request.setHeader("Content-Encoding",ConsultaPorCurpService_ConsultaPorCurpServiceHttpsSoap12EndpointEndpoint.Binding.CompressRequest)
    END IF
    CALL request.setHeader("Accept-Encoding","gzip, deflate")
  CATCH
    LET wsstatus = status
    CALL WSHelper.WSHelper_FillSOAP12WSError("Sender","Cannot create HTTPRequest")
    RETURN wsstatus
  END TRY

  # START LOOP
  WHILE retry
    LET retry = FALSE

    #
    # Stax request
    #
    TRY
      LET writer = request.beginXmlRequest()
      CALL WSHelper.WSHelper_WriteStaxSOAP12StartEnvelope(writer)
      CALL WSHelper.WSHelper_WriteStaxSOAP12StartBody(writer)
      #
      # STAX SOAP REQUEST SERIALIZE
      #
      CALL xml.Serializer.VariableToStax(ns2consultarPorCurp,writer)
      CALL WSHelper.WSHelper_WriteStaxSOAP12EndBody(writer)
      CALL WSHelper.WSHelper_WriteStaxSOAP12EndEnvelope(writer)
      CALL request.endXmlRequest(writer)
    CATCH
      LET wsstatus = status
      CALL WSHelper.WSHelper_FillSOAP12WSError("Sender",sqlca.sqlerrm)
      RETURN wsstatus
    END TRY

    #
    # PROCESS RESPONSE
    #
    TRY
      LET response = request.getResponse()

      #
      # RETRIEVE SERVICE SESSION COOKIE
      #
      LET setcookie = response.getHeader("Set-Cookie")
      IF setcookie IS NOT NULL THEN
        LET ConsultaPorCurpService_ConsultaPorCurpServiceHttpsSoap12EndpointEndpoint.Binding.Cookie = WSHelper.WSHelper_ExtractServerCookie(setcookie,ConsultaPorCurpService_ConsultaPorCurpServiceHttpsSoap12EndpointEndpoint.Address.Uri)
      END IF

      #
      # RETRIEVE HTTP RESPONSE Headers
      #
      CALL WSHelper.WSHelper_SetResponseHeaders(response, ConsultaPorCurpService_ConsultaPorCurpServiceHttpsSoap12EndpointEndpoint.Binding.Response.Headers)

      CASE
        WHEN response.getStatusCode()==200 OR response.getStatusCode()==500
          #
          # Check SOAP 1.2 MimeType
          #
          IF NOT WSHelper.WSHelper_CheckSOAP12HttpMimeType(response) THEN
            EXIT CASE
          END IF
          #
          # STAX SOAP RESPONSE OR FAULT
          #
          LET reader = response.beginXmlResponse() # Begin Streaming Response
          IF NOT WSHelper.WSHelper_ReadStaxSOAP12StartEnvelope(reader) THEN
            EXIT CASE
          END IF
          # Process SOAP headers 
          LET nb = 0
          IF WSHelper.WSHelper_CheckStaxSOAP12Header(reader) AND NOT reader.isEmptyElement() THEN
            CALL reader.nextTag()
            WHILE (reader.getEventType()=="START_ELEMENT")
              IF WSHelper.WSHelper_CheckStaxSOAP12HeaderRole(reader,uri) THEN
                LET mustUnderstand = WSHelper.WSHelper_GetStaxSOAP12HeaderMustUnderstand(reader)
                IF mustUnderstand = -1 THEN
                  CALL WSHelper.WSHelper_FillSOAP12WSError("Sender","Invalid mustUnderstand value")
                  EXIT CASE
                END IF
                #
                # STAX SOAP RESPONSE HEADER DESERIALIZE
                #
                IF mustUnderstand THEN
                  CALL WSHelper.WSHelper_FillSOAP12WSError("MustUnderstand","Mandatory header block not understood")
                  EXIT CASE
                ELSE
                  CALL reader.nextSibling() # Skip header, not necessary
                END IF
              ELSE
                CALL reader.nextSibling() # Skip header, not intended to us
              END IF
            END WHILE
            IF NOT WSHelper.WSHelper_CheckStaxSOAP12Header(reader) THEN
              CALL WSHelper.WSHelper_FillSOAP12WSError("Sender","No ending header tag found")
              EXIT CASE
            ELSE
              CALL reader.nextTag()
            END IF
          ELSE
            IF reader.isEmptyElement() THEN
              CALL reader.nextTag()
            END IF
          END IF
          IF NOT WSHelper.WSHelper_ReadStaxSOAP12StartBody(reader) THEN
            EXIT CASE
          END IF
          IF WSHelper.WSHelper_CheckStaxSOAP12StartFault(reader) THEN # Handle SOAP Fault
            LET fault = TRUE
            CALL reader.nextTag()
            IF NOT WSHelper.WSHelper_ReadStaxSOAP12FaultUntilDetail(reader) THEN
              EXIT CASE
            END IF
            IF WSHelper.WSHelper_CheckStaxSOAP12FaultDetail(reader) THEN
              #
              # STAX SOAP FAULT DESERIALIZE
              #
              CALL reader.nextSibling() # Skip SOAP detail
            END IF
            IF NOT WSHelper.WSHelper_ReadStaxSOAP12EndFault(reader) THEN
              EXIT CASE
            END IF
          ELSE # Handle SOAP Response
            IF nb != 0 THEN # Check mandatory headers
              CALL WSHelper.WSHelper_FillSOAP12WSError("Sender","Headers are missing")
              EXIT CASE
            END IF
            IF NOT WSHelper.WSHelper_RetrieveStaxSOAP12Message(reader) THEN
              EXIT CASE
            END IF
            #
            # STAX SOAP RESPONSE DESERIALIZE
            #
            CALL xml.Serializer.StaxToVariable(reader,ns2consultarPorCurpResponse)
          END IF
          IF NOT WSHelper.WSHelper_ReadStaxSOAP12EndBody(reader) THEN
            EXIT CASE
          END IF
          IF NOT WSHelper.WSHelper_ReadStaxSOAP12EndEnvelope(reader) THEN
            EXIT CASE
          END IF
          # End Streaming Response
          CALL response.endXmlResponse(reader)
          IF NOT fault THEN
            LET wsstatus = 0
          END IF

        WHEN response.getStatusCode()==401 # HTTP Authentication
          IF retryAuth THEN
            CALL WSHelper.WSHelper_FillSOAP12WSError("Receiver","HTTP Error 401 ("||response.getStatusDescription()||")")
          ELSE
            LET retryAuth = TRUE
            LET retry = TRUE
          END IF

        WHEN response.getStatusCode()==407 # Proxy Authentication
          IF retryProxy THEN
            CALL WSHelper.WSHelper_FillSOAP12WSError("Receiver","HTTP Error 407 ("||response.getStatusDescription()||")")
          ELSE
            LET retryProxy = TRUE
            LET retry = TRUE
          END IF

        OTHERWISE
          CALL WSHelper.WSHelper_FillSOAP12WSError("Receiver","HTTP Error "||response.getStatusCode()||" ("||response.getStatusDescription()||")")

      END CASE
    CATCH
      LET wsstatus = status
      CALL WSHelper.WSHelper_FillSOAP12WSError("Receiver",sqlca.sqlerrm)
      RETURN wsstatus
    END TRY

  # END LOOP
  END WHILE

  RETURN wsstatus

END FUNCTION


FUNCTION consultarPorCurpRequest_g()
  DEFINE wsstatus   INTEGER
  DEFINE writer     xml.StaxWriter

  #
  # CHECK PREVIOUS CALL  
  #
  IF consultarPorCurpHTTPReq IS NOT NULL AND consultarPorCurpHTTPResp IS NULL THEN
    # Request was sent but there was no response yet
    CALL WSHelper.WSHelper_FillSOAP12WSError("Sender","Cannot issue a new request until previous response was received")
    RETURN -2 # waiting for the response
  ELSE
   # IF ConsultaPorCurpService_ConsultaPorCurpServiceHttpsSoap12EndpointEndpoint.Address.Uri IS NULL THEN
   #   LET ConsultaPorCurpService_ConsultaPorCurpServiceHttpsSoap12EndpointEndpoint.Address.Uri = "https://webs.curp.gob.mx:8443/WebServicesConsulta/services/ConsultaPorCurpService.ConsultaPorCurpServiceHttpsSoap12Endpoint/"
   # END IF
  END IF

  #
  # CREATE REQUEST
  #
  TRY
    LET consultarPorCurpHTTPReq = com.HttpRequest.Create(ConsultaPorCurpService_ConsultaPorCurpServiceHttpsSoap12EndpointEndpoint.Address.Uri)
    CALL consultarPorCurpHTTPReq.setMethod("POST")
    CALL consultarPorCurpHTTPReq.setCharset("UTF-8")
    CALL consultarPorCurpHTTPReq.setHeader("Content-Type","application/soap+xml; action=\"urn:consultarPorCurp\"")
    CALL WSHelper.WSHelper_SetRequestHeaders(consultarPorCurpHTTPReq, ConsultaPorCurpService_ConsultaPorCurpServiceHttpsSoap12EndpointEndpoint.Binding.Request.Headers)
    IF ConsultaPorCurpService_ConsultaPorCurpServiceHttpsSoap12EndpointEndpoint.Binding.Version IS NOT NULL THEN
      CALL consultarPorCurpHTTPReq.setVersion(ConsultaPorCurpService_ConsultaPorCurpServiceHttpsSoap12EndpointEndpoint.Binding.Version)
    END IF
    IF ConsultaPorCurpService_ConsultaPorCurpServiceHttpsSoap12EndpointEndpoint.Binding.Cookie IS NOT NULL THEN
      CALL consultarPorCurpHTTPReq.setHeader("Cookie",ConsultaPorCurpService_ConsultaPorCurpServiceHttpsSoap12EndpointEndpoint.Binding.Cookie)
    END IF
    IF ConsultaPorCurpService_ConsultaPorCurpServiceHttpsSoap12EndpointEndpoint.Binding.ConnectionTimeout <> 0 THEN
      CALL consultarPorCurpHTTPReq.setConnectionTimeOut(ConsultaPorCurpService_ConsultaPorCurpServiceHttpsSoap12EndpointEndpoint.Binding.ConnectionTimeout)
    END IF
    IF ConsultaPorCurpService_ConsultaPorCurpServiceHttpsSoap12EndpointEndpoint.Binding.ReadWriteTimeout <> 0 THEN
      CALL consultarPorCurpHTTPReq.setTimeOut(ConsultaPorCurpService_ConsultaPorCurpServiceHttpsSoap12EndpointEndpoint.Binding.ReadWriteTimeout)
    END IF
    IF ConsultaPorCurpService_ConsultaPorCurpServiceHttpsSoap12EndpointEndpoint.Binding.CompressRequest IS NOT NULL THEN
      CALL consultarPorCurpHTTPReq.setHeader("Content-Encoding",ConsultaPorCurpService_ConsultaPorCurpServiceHttpsSoap12EndpointEndpoint.Binding.CompressRequest)
    END IF
    CALL consultarPorCurpHTTPReq.setHeader("Accept-Encoding","gzip, deflate")
  CATCH
    LET wsstatus = status
    CALL WSHelper.WSHelper_FillSOAP12WSError("Sender","Cannot create HTTPRequest")
    LET consultarPorCurpHTTPReq = NULL
    RETURN wsstatus
  END TRY

    #
    # Stax request
    #
    TRY
      LET writer = consultarPorCurpHTTPReq.beginXmlRequest()
      CALL WSHelper.WSHelper_WriteStaxSOAP12StartEnvelope(writer)
      CALL WSHelper.WSHelper_WriteStaxSOAP12StartBody(writer)
      #
      # STAX SOAP REQUEST SERIALIZE
      #
      CALL xml.Serializer.VariableToStax(ns2consultarPorCurp,writer)
      CALL WSHelper.WSHelper_WriteStaxSOAP12EndBody(writer)
      CALL WSHelper.WSHelper_WriteStaxSOAP12EndEnvelope(writer)
      CALL consultarPorCurpHTTPReq.endXmlRequest(writer)
    CATCH
      LET wsstatus = status
      CALL WSHelper.WSHelper_FillSOAP12WSError("Sender",sqlca.sqlerrm)
      LET consultarPorCurpHTTPReq = NULL
      RETURN wsstatus
    END TRY

  #
  # PROCESS RESPONSE
  #
  TRY
    LET consultarPorCurpHTTPResp = consultarPorCurpHTTPReq.getAsyncResponse()
    RETURN 0 # SUCCESS
  CATCH
    LET wsstatus = status
    CALL WSHelper.WSHelper_FillSOAP12WSError("Receiver",sqlca.sqlerrm)
    LET consultarPorCurpHTTPReq = NULL
    RETURN wsstatus
  END TRY
END FUNCTION


FUNCTION consultarPorCurpResponse_g()
  DEFINE wsstatus        INTEGER
  DEFINE fault           BOOLEAN
  DEFINE nb              INTEGER
  DEFINE uri             STRING
  DEFINE setcookie       STRING
  DEFINE mustUnderstand  INTEGER
  DEFINE reader          xml.StaxReader

  LET fault = FALSE
  LET wsstatus = -1

  LET uri = com.WebServiceEngine.GetOption("SoapModuleURI")
  #
  # CHECK PREVIOUS CALL  
  #
  IF consultarPorCurpHTTPReq IS NULL THEN
    # No request was sent
    CALL WSHelper.WSHelper_FillSOAP12WSError("Sender","No request has been sent")
    RETURN -1
  END IF

  TRY
    #
    # PROCESS RESPONSE
    #
    IF consultarPorCurpHTTPResp IS NULL THEN
      # Still no response, try again
      LET consultarPorCurpHTTPResp = consultarPorCurpHTTPReq.getAsyncResponse()
    END IF

    IF consultarPorCurpHTTPResp IS NULL THEN
      # We got no response, still waiting for
      CALL WSHelper.WSHelper_FillSOAP12WSError("Sender","Response was not yet received")
      RETURN -2
    END IF

      #
      # RETRIEVE SERVICE SESSION COOKIE
      #
      LET setcookie = consultarPorCurpHTTPResp.getHeader("Set-Cookie")
      IF setcookie IS NOT NULL THEN
        LET ConsultaPorCurpService_ConsultaPorCurpServiceHttpsSoap12EndpointEndpoint.Binding.Cookie = WSHelper.WSHelper_ExtractServerCookie(setcookie,ConsultaPorCurpService_ConsultaPorCurpServiceHttpsSoap12EndpointEndpoint.Address.Uri)
      END IF

      #
      # RETRIEVE HTTP RESPONSE Headers
      #
      CALL WSHelper.WSHelper_SetResponseHeaders(consultarPorCurpHTTPResp, ConsultaPorCurpService_ConsultaPorCurpServiceHttpsSoap12EndpointEndpoint.Binding.Response.Headers)
      CASE
        WHEN consultarPorCurpHTTPResp.getStatusCode()==200 OR consultarPorCurpHTTPResp.getStatusCode()==500
          #
          # Check SOAP 1.2 MimeType
          #
          IF NOT WSHelper.WSHelper_CheckSOAP12HttpMimeType(consultarPorCurpHTTPResp) THEN
            EXIT CASE
          END IF
          #
          # STAX SOAP RESPONSE OR FAULT
          #
          LET reader = consultarPorCurpHTTPResp.beginXmlResponse() # Begin Streaming Response
          IF NOT WSHelper.WSHelper_ReadStaxSOAP12StartEnvelope(reader) THEN
            EXIT CASE
          END IF
          # Process SOAP headers 
          LET nb = 0
          IF WSHelper.WSHelper_CheckStaxSOAP12Header(reader) AND NOT reader.isEmptyElement() THEN
            CALL reader.nextTag()
            WHILE (reader.getEventType()=="START_ELEMENT")
              IF WSHelper.WSHelper_CheckStaxSOAP12HeaderRole(reader,uri) THEN
                LET mustUnderstand = WSHelper.WSHelper_GetStaxSOAP12HeaderMustUnderstand(reader)
                IF mustUnderstand = -1 THEN
                  CALL WSHelper.WSHelper_FillSOAP12WSError("Sender","Invalid mustUnderstand value")
                  EXIT CASE
                END IF
                #
                # STAX SOAP RESPONSE HEADER DESERIALIZE
                #
                IF mustUnderstand THEN
                  CALL WSHelper.WSHelper_FillSOAP12WSError("MustUnderstand","Mandatory header block not understood")
                  EXIT CASE
                ELSE
                  CALL reader.nextSibling() # Skip header, not necessary
                END IF
              ELSE
                CALL reader.nextSibling() # Skip header, not intended to us
              END IF
            END WHILE
            IF NOT WSHelper.WSHelper_CheckStaxSOAP12Header(reader) THEN
              CALL WSHelper.WSHelper_FillSOAP12WSError("Sender","No ending header tag found")
              EXIT CASE
            ELSE
              CALL reader.nextTag()
            END IF
          ELSE
            IF reader.isEmptyElement() THEN
              CALL reader.nextTag()
            END IF
          END IF
          IF NOT WSHelper.WSHelper_ReadStaxSOAP12StartBody(reader) THEN
            EXIT CASE
          END IF
          IF WSHelper.WSHelper_CheckStaxSOAP12StartFault(reader) THEN # Handle SOAP Fault
            LET fault = TRUE
            CALL reader.nextTag()
            IF NOT WSHelper.WSHelper_ReadStaxSOAP12FaultUntilDetail(reader) THEN
              EXIT CASE
            END IF
            IF WSHelper.WSHelper_CheckStaxSOAP12FaultDetail(reader) THEN
              #
              # STAX SOAP FAULT DESERIALIZE
              #
              CALL reader.nextSibling() # Skip SOAP detail
            END IF
            IF NOT WSHelper.WSHelper_ReadStaxSOAP12EndFault(reader) THEN
              EXIT CASE
            END IF
          ELSE # Handle SOAP Response
            IF nb != 0 THEN # Check mandatory headers
              CALL WSHelper.WSHelper_FillSOAP12WSError("Sender","Headers are missing")
              EXIT CASE
            END IF
            IF NOT WSHelper.WSHelper_RetrieveStaxSOAP12Message(reader) THEN
              EXIT CASE
            END IF
            #
            # STAX SOAP RESPONSE DESERIALIZE
            #
            CALL xml.Serializer.StaxToVariable(reader,ns2consultarPorCurpResponse)
          END IF
          IF NOT WSHelper.WSHelper_ReadStaxSOAP12EndBody(reader) THEN
            EXIT CASE
          END IF
          IF NOT WSHelper.WSHelper_ReadStaxSOAP12EndEnvelope(reader) THEN
            EXIT CASE
          END IF
          # End Streaming Response
          CALL consultarPorCurpHTTPResp.endXmlResponse(reader)
          IF NOT fault THEN
            LET wsstatus = 0
          END IF

        OTHERWISE
          CALL WSHelper.WSHelper_FillSOAP12WSError("Receiver","HTTP Error "||consultarPorCurpHTTPResp.getStatusCode()||" ("||consultarPorCurpHTTPResp.getStatusDescription()||")")

      END CASE
    CATCH
      LET wsstatus = status
      CALL WSHelper.WSHelper_FillSOAP12WSError("Receiver",sqlca.sqlerrm)
    END TRY

  #
  # RESET VARIABLES
  #
  LET consultarPorCurpHTTPReq = NULL
  LET consultarPorCurpHTTPResp = NULL
  RETURN wsstatus

END FUNCTION


