#-------------------------------------------------------------------------------
# File: ConsultaCurpDetalleService_ConsultaCurpDetalleServiceHttpsSoap12Endpoint.4gl
# GENERATED BY fglwsdl 1454432468
#-------------------------------------------------------------------------------
# THIS FILE WAS GENERATED. DO NOT MODIFY.
#-------------------------------------------------------------------------------


IMPORT FGL WSHelper
IMPORT com
IMPORT XML


GLOBALS "ConsultaCurpDetalleService_ConsultaCurpDetalleServiceHttpsSoap12Endpoint.inc"



#-------------------------------------------------------------------------------
# Service: ConsultaCurpDetalleService
# Port:    ConsultaCurpDetalleServiceHttpsSoap12Endpoint
# Server:  https://websdes.curp.gob.mx:8443/WebServicesConsulta/services/ConsultaCurpDetalleService.ConsultaCurpDetalleServiceHttpsSoap12Endpoint/
#-------------------------------------------------------------------------------

PRIVATE DEFINE consultarCurpDetalleHTTPReq     com.HttpRequest
PRIVATE DEFINE consultarCurpDetalleHTTPResp    com.HttpResponse

PRIVATE DEFINE getConfirmHTTPReq     com.HttpRequest

#-------------------------------------------------------------------------------

#
# Operation: consultarCurpDetalle
#
#
# FUNCTION: consultarCurpDetalle_g
#   RETURNING: soapStatus
#   INPUT: GLOBAL ns2consultarCurpDetalle
#   OUTPUT: GLOBAL ns2consultarCurpDetalleResponse
#
FUNCTION consultarCurpDetalle_g()
  DEFINE wsstatus   INTEGER
  DEFINE retryAuth  INTEGER
  DEFINE retryProxy INTEGER
  DEFINE retry      INTEGER
  DEFINE nb         INTEGER
  DEFINE uri        STRING
  DEFINE setcookie  STRING
  DEFINE mustUnderstand INTEGER
  DEFINE request    com.HttpRequest
  DEFINE response   com.HttpResponse
  DEFINE writer     xml.StaxWriter
  DEFINE reader     xml.StaxReader

  #
  # INIT VARIABLES
  #
  LET wsstatus = -1
  LET retryAuth = FALSE
  LET retryProxy = FALSE
  LET retry = TRUE
  LET uri = com.WebServiceEngine.GetOption("SoapModuleURI")

  IF ConsultaCurpDetalleService_ConsultaCurpDetalleServiceHttpsSoap12EndpointEndpoint.Address.Uri IS NULL THEN
    LET ConsultaCurpDetalleService_ConsultaCurpDetalleServiceHttpsSoap12EndpointEndpoint.Address.Uri = "https://websdes.curp.gob.mx:8443/WebServicesConsulta/services/ConsultaCurpDetalleService.ConsultaCurpDetalleServiceHttpsSoap12Endpoint/"
  END IF

  #
  # CREATE REQUEST
  #
  TRY
    LET request = com.HttpRequest.Create(ConsultaCurpDetalleService_ConsultaCurpDetalleServiceHttpsSoap12EndpointEndpoint.Address.Uri)
    CALL request.setMethod("POST")
    CALL request.setCharset("UTF-8")
    CALL request.setHeader("Content-Type","application/soap+xml; action=\"urn:consultarCurpDetalle\"")
    CALL WSHelper_SetRequestHeaders(request, ConsultaCurpDetalleService_ConsultaCurpDetalleServiceHttpsSoap12EndpointEndpoint.Binding.Request.Headers)
    IF ConsultaCurpDetalleService_ConsultaCurpDetalleServiceHttpsSoap12EndpointEndpoint.Binding.Version IS NOT NULL THEN
      CALL request.setVersion(ConsultaCurpDetalleService_ConsultaCurpDetalleServiceHttpsSoap12EndpointEndpoint.Binding.Version)
    END IF
    IF ConsultaCurpDetalleService_ConsultaCurpDetalleServiceHttpsSoap12EndpointEndpoint.Binding.Cookie IS NOT NULL THEN
      CALL request.setHeader("Cookie",ConsultaCurpDetalleService_ConsultaCurpDetalleServiceHttpsSoap12EndpointEndpoint.Binding.Cookie)
    END IF
    IF ConsultaCurpDetalleService_ConsultaCurpDetalleServiceHttpsSoap12EndpointEndpoint.Binding.ConnectionTimeout <> 0 THEN
      CALL request.setConnectionTimeOut(ConsultaCurpDetalleService_ConsultaCurpDetalleServiceHttpsSoap12EndpointEndpoint.Binding.ConnectionTimeout)
    END IF
    IF ConsultaCurpDetalleService_ConsultaCurpDetalleServiceHttpsSoap12EndpointEndpoint.Binding.ReadWriteTimeout <> 0 THEN
      CALL request.setTimeOut(ConsultaCurpDetalleService_ConsultaCurpDetalleServiceHttpsSoap12EndpointEndpoint.Binding.ReadWriteTimeout)
    END IF
    IF ConsultaCurpDetalleService_ConsultaCurpDetalleServiceHttpsSoap12EndpointEndpoint.Binding.CompressRequest IS NOT NULL THEN
      CALL request.setHeader("Content-Encoding",ConsultaCurpDetalleService_ConsultaCurpDetalleServiceHttpsSoap12EndpointEndpoint.Binding.CompressRequest)
    END IF
    CALL request.setHeader("Accept-Encoding","gzip, deflate")
  CATCH
    LET wsstatus = status
    CALL WSHelper_FillSOAP12WSError("Sender","Cannot create HttpRequest")
    RETURN wsstatus    
  END TRY

  # START LOOP
  WHILE retry
    LET retry = FALSE

    #
    # Stax request
    #
    TRY
      LET writer = request.beginXmlRequest()
      CALL WSHelper_WriteStaxSOAP12StartEnvelope(writer)
      CALL WSHelper_WriteStaxSOAP12StartBody(writer)
      #
      # STAX SOAP REQUEST SERIALIZE
      #
      CALL xml.Serializer.VariableToStax(ns2consultarCurpDetalle,writer)
      CALL WSHelper_WriteStaxSOAP12EndBody(writer)
      CALL WSHelper_WriteStaxSOAP12EndEnvelope(writer)
      CALL request.endXmlRequest(writer)
    CATCH
      LET wsstatus = status
      CALL WSHelper_FillSOAP12WSError("Sender",sqlca.sqlerrm)
      RETURN wsstatus    
    END TRY

    #
    # PROCESS RESPONSE
    #
    TRY
      LET response = request.getResponse()

      #
      # RETRIEVE SERVICE SESSION COOKIE
      #
      LET setcookie = response.getHeader("Set-Cookie")
      IF setcookie IS NOT NULL THEN
        LET ConsultaCurpDetalleService_ConsultaCurpDetalleServiceHttpsSoap12EndpointEndpoint.Binding.Cookie = WSHelper_ExtractServerCookie(setcookie,ConsultaCurpDetalleService_ConsultaCurpDetalleServiceHttpsSoap12EndpointEndpoint.Address.Uri)
      END IF

      #
      # RETRIEVE HTTP RESPONSE Headers
      #
      CALL WSHelper_SetResponseHeaders(response, ConsultaCurpDetalleService_ConsultaCurpDetalleServiceHttpsSoap12EndpointEndpoint.Binding.Response.Headers)
      CASE response.getStatusCode()

        WHEN 500 # SOAP Fault
          #
          # Check SOAP 1.2 MimeType
          #
          IF NOT WSHelper_CheckSOAP12HttpMimeType(response) THEN
            EXIT CASE
          END IF
          #
          # STAX SOAP FAULT
          #
          LET reader = response.beginXmlResponse() # Begin Streaming Response
          IF NOT WSHelper_ReadStaxSOAP12StartEnvelope(reader) THEN
            EXIT CASE
          END IF
          # Process SOAP headers 
          IF WSHelper_CheckStaxSOAP12Header(reader) AND NOT reader.isEmptyElement() THEN
            CALL reader.nextTag()
            WHILE (reader.getEventType()=="START_ELEMENT")
              IF WSHelper_CheckStaxSOAP12HeaderRole(reader,uri) THEN
                LET mustUnderstand = WSHelper_GetStaxSOAP12HeaderMustUnderstand(reader)
                IF mustUnderstand = -1 THEN
                  CALL WSHelper_FillSOAP11WSError("Sender","Invalid mustUnderstand value")
                  EXIT CASE
                END IF
                IF mustUnderstand THEN
                  CALL WSHelper_FillSOAP12WSError("MustUnderstand","Mandatory header block not understood")
                  EXIT CASE
                ELSE
                  CALL reader.nextSibling() # Skip header, not necessary
                END IF
              ELSE
                CALL reader.nextSibling() # Skip header, not intended to us
              END IF
            END WHILE
            IF NOT WSHelper_CheckStaxSOAP12Header(reader) THEN
              CALL WSHelper_FillSOAP11WSError("Sender","No ending header tag found")
              EXIT CASE
            ELSE
              CALL reader.nextTag()
            END IF
          ELSE
            IF WSHelper_CheckStaxSOAP12Header(reader) THEN
              CALL reader.nextSibling() # Skip SOAP headers
            END IF
          END IF
          IF NOT WSHelper_ReadStaxSOAP12StartBody(reader) THEN
            EXIT CASE
          END IF
          IF NOT WSHelper_ReadStaxSOAP12StartFault(reader) THEN
            EXIT CASE
          END IF
          IF NOT WSHelper_ReadStaxSOAP12FaultUntilDetail(reader) THEN
            EXIT CASE
          END IF
          IF WSHelper_CheckStaxSOAP12FaultDetail(reader) THEN
            #
            # STAX SOAP FAULT DESERIALIZE
            #
            CALL reader.nextSibling() # Skip SOAP detail
          END IF
          IF NOT WSHelper_ReadStaxSOAP12EndFault(reader) THEN
            EXIT CASE
          END IF
          IF NOT WSHelper_ReadStaxSOAP12EndBody(reader) THEN
            EXIT CASE
          END IF
          IF NOT WSHelper_ReadStaxSOAP12EndEnvelope(reader) THEN
            EXIT CASE
          END IF
          # End Streaming Response
          CALL response.endXmlResponse(reader)

        WHEN 200 # SOAP Result
          #
          # Check SOAP 1.2 MimeType
          #
          IF NOT WSHelper_CheckSOAP12HttpMimeType(response) THEN
            EXIT CASE
          END IF
          #
          # STAX SOAP RESPONSE
          #
          LET reader = response.beginXmlResponse() # Begin Streaming Response
          IF NOT WSHelper_ReadStaxSOAP12StartEnvelope(reader) THEN
            EXIT CASE
          END IF
          # Process SOAP headers 
          IF WSHelper_CheckStaxSOAP12Header(reader) AND NOT reader.isEmptyElement() THEN
            LET nb = 0
            CALL reader.nextTag()
            WHILE (reader.getEventType()=="START_ELEMENT")
              IF WSHelper_CheckStaxSOAP12HeaderRole(reader,uri) THEN
                LET mustUnderstand = WSHelper_GetStaxSOAP12HeaderMustUnderstand(reader)
                IF mustUnderstand = -1 THEN
                  CALL WSHelper_FillSOAP12WSError("Sender","Invalid mustUnderstand value")
                  EXIT CASE
                END IF
                #
                # STAX SOAP RESPONSE HEADER DESERIALIZE
                #
                IF mustUnderstand THEN
                  CALL WSHelper_FillSOAP12WSError("MustUnderstand","Mandatory header block not understood")
                  EXIT CASE
                ELSE
                  CALL reader.nextSibling() # Skip header, not necessary
                END IF
              ELSE
                CALL reader.nextSibling() # Skip header, not intended to us
              END IF
            END WHILE
            IF NOT WSHelper_CheckStaxSOAP12Header(reader) THEN
              CALL WSHelper_FillSOAP12WSError("Sender","No ending header tag found")
              EXIT CASE
            ELSE
              IF nb != 0 THEN
                CALL WSHelper_FillSOAP12WSError("Sender","One or more headers are missing")
                EXIT CASE
              ELSE
                CALL reader.nextTag()
              END IF
            END IF
          ELSE
           IF reader.isEmptyElement() THEN
             CALL reader.nextTag()
           END IF
          END IF
          IF NOT WSHelper_ReadStaxSOAP12StartBody(reader) THEN
            EXIT CASE
          END IF
          IF NOT WSHelper_RetrieveStaxSOAP12Message(reader) THEN
            EXIT CASE
          END IF
          #
          # STAX SOAP RESPONSE DESERIALIZE
          #
          CALL xml.Serializer.StaxToVariable(reader,ns2consultarCurpDetalleResponse)
          IF NOT WSHelper_ReadStaxSOAP12EndBody(reader) THEN
            EXIT CASE
          END IF
          IF NOT WSHelper_ReadStaxSOAP12EndEnvelope(reader) THEN
            EXIT CASE
          END IF
          # End Streaming Response
          CALL response.endXmlResponse(reader)
          LET wsstatus = 0

        WHEN 401 # HTTP Authentication
          IF retryAuth THEN
            CALL WSHelper_FillSOAP12WSError("Receiver","HTTP Error 401 ("||response.getStatusDescription()||")")
          ELSE
            LET retryAuth = TRUE
            LET retry = TRUE
          END IF

        WHEN 407 # Proxy Authentication
          IF retryProxy THEN
            CALL WSHelper_FillSOAP12WSError("Receiver","HTTP Error 407 ("||response.getStatusDescription()||")")
          ELSE
            LET retryProxy = TRUE
            LET retry = TRUE
          END IF

        OTHERWISE
          CALL WSHelper_FillSOAP12WSError("Receiver","HTTP Error "||response.getStatusCode()||" ("||response.getStatusDescription()||")")

      END CASE
    CATCH
      LET wsstatus = status
      CALL WSHelper_FillSOAP12WSError("Receiver",sqlca.sqlerrm)
      RETURN wsstatus    
    END TRY

  # END LOOP
  END WHILE

  RETURN wsstatus

END FUNCTION


FUNCTION consultarCurpDetalleRequest_g()
  DEFINE wsstatus   INTEGER
  DEFINE writer     xml.StaxWriter

  #
  # CHECK PREVIOUS CALL  
  #
  IF consultarCurpDetalleHTTPReq IS NOT NULL AND consultarCurpDetalleHTTPResp IS NULL THEN
    # Request was sent but there was no response yet
    CALL WSHelper_FillSOAP12WSError("Sender","Cannot issue a new request until previous response was received")
    RETURN -2 # waiting for the response
  ELSE
    IF ConsultaCurpDetalleService_ConsultaCurpDetalleServiceHttpsSoap12EndpointEndpoint.Address.Uri IS NULL THEN
      LET ConsultaCurpDetalleService_ConsultaCurpDetalleServiceHttpsSoap12EndpointEndpoint.Address.Uri = "https://websdes.curp.gob.mx:8443/WebServicesConsulta/services/ConsultaCurpDetalleService.ConsultaCurpDetalleServiceHttpsSoap12Endpoint/"
    END IF
  END IF

  #
  # CREATE REQUEST
  #
  TRY
    LET consultarCurpDetalleHTTPReq = com.HttpRequest.Create(ConsultaCurpDetalleService_ConsultaCurpDetalleServiceHttpsSoap12EndpointEndpoint.Address.Uri)
    CALL consultarCurpDetalleHTTPReq.setMethod("POST")
    CALL consultarCurpDetalleHTTPReq.setCharset("UTF-8")
    CALL consultarCurpDetalleHTTPReq.setHeader("Content-Type","application/soap+xml; action=\"urn:consultarCurpDetalle\"")
    CALL WSHelper_SetRequestHeaders(consultarCurpDetalleHTTPReq, ConsultaCurpDetalleService_ConsultaCurpDetalleServiceHttpsSoap12EndpointEndpoint.Binding.Request.Headers)
    IF ConsultaCurpDetalleService_ConsultaCurpDetalleServiceHttpsSoap12EndpointEndpoint.Binding.Version IS NOT NULL THEN
      CALL consultarCurpDetalleHTTPReq.setVersion(ConsultaCurpDetalleService_ConsultaCurpDetalleServiceHttpsSoap12EndpointEndpoint.Binding.Version)
    END IF
    IF ConsultaCurpDetalleService_ConsultaCurpDetalleServiceHttpsSoap12EndpointEndpoint.Binding.Cookie IS NOT NULL THEN
      CALL consultarCurpDetalleHTTPReq.setHeader("Cookie",ConsultaCurpDetalleService_ConsultaCurpDetalleServiceHttpsSoap12EndpointEndpoint.Binding.Cookie)
    END IF
    IF ConsultaCurpDetalleService_ConsultaCurpDetalleServiceHttpsSoap12EndpointEndpoint.Binding.ConnectionTimeout <> 0 THEN
      CALL consultarCurpDetalleHTTPReq.setConnectionTimeOut(ConsultaCurpDetalleService_ConsultaCurpDetalleServiceHttpsSoap12EndpointEndpoint.Binding.ConnectionTimeout)
    END IF
    IF ConsultaCurpDetalleService_ConsultaCurpDetalleServiceHttpsSoap12EndpointEndpoint.Binding.ReadWriteTimeout <> 0 THEN
      CALL consultarCurpDetalleHTTPReq.setTimeOut(ConsultaCurpDetalleService_ConsultaCurpDetalleServiceHttpsSoap12EndpointEndpoint.Binding.ReadWriteTimeout)
    END IF
    IF ConsultaCurpDetalleService_ConsultaCurpDetalleServiceHttpsSoap12EndpointEndpoint.Binding.CompressRequest IS NOT NULL THEN
      CALL consultarCurpDetalleHTTPReq.setHeader("Content-Encoding",ConsultaCurpDetalleService_ConsultaCurpDetalleServiceHttpsSoap12EndpointEndpoint.Binding.CompressRequest)
    END IF
    CALL consultarCurpDetalleHTTPReq.setHeader("Accept-Encoding","gzip, deflate")
  CATCH
    LET wsstatus = status
    CALL WSHelper_FillSOAP12WSError("Sender","Cannot create HttpRequest")
    LET consultarCurpDetalleHTTPReq = NULL
    RETURN wsstatus    
  END TRY

    #
    # Stax request
    #
    TRY
      LET writer = consultarCurpDetalleHTTPReq.beginXmlRequest()
      CALL WSHelper_WriteStaxSOAP12StartEnvelope(writer)
      CALL WSHelper_WriteStaxSOAP12StartBody(writer)
      #
      # STAX SOAP REQUEST SERIALIZE
      #
      CALL xml.Serializer.VariableToStax(ns2consultarCurpDetalle,writer)
      CALL WSHelper_WriteStaxSOAP12EndBody(writer)
      CALL WSHelper_WriteStaxSOAP12EndEnvelope(writer)
      CALL consultarCurpDetalleHTTPReq.endXmlRequest(writer)
    CATCH
      LET wsstatus = status
      CALL WSHelper_FillSOAP12WSError("Sender",sqlca.sqlerrm)
      LET consultarCurpDetalleHTTPReq = NULL
      RETURN wsstatus    
    END TRY

  #
  # PROCESS RESPONSE
  #
  TRY
    LET consultarCurpDetalleHTTPResp = consultarCurpDetalleHTTPReq.getAsyncResponse()
    RETURN 0 # SUCCESS
  CATCH
    LET wsstatus = status
    CALL WSHelper_FillSOAP12WSError("Receiver",sqlca.sqlerrm)
    LET consultarCurpDetalleHTTPReq = NULL
    RETURN wsstatus
  END TRY
END FUNCTION


FUNCTION consultarCurpDetalleResponse_g()
  DEFINE wsstatus        INTEGER
  DEFINE nb              INTEGER
  DEFINE uri             STRING
  DEFINE setcookie       STRING
  DEFINE mustUnderstand  INTEGER
  DEFINE reader          xml.StaxReader

  LET wsstatus = -1

  LET uri = com.WebServiceEngine.GetOption("SoapModuleURI")
  #
  # CHECK PREVIOUS CALL  
  #
  IF consultarCurpDetalleHTTPReq IS NULL THEN
    # No request was sent
    CALL WSHelper_FillSOAP12WSError("Sender","No request has been sent")
    RETURN -1    
  END IF

  TRY
    #
    # PROCESS RESPONSE
    #
    IF consultarCurpDetalleHTTPResp IS NULL THEN
      # Still no response, try again
      LET consultarCurpDetalleHTTPResp = consultarCurpDetalleHTTPReq.getAsyncResponse()
    END IF

    IF consultarCurpDetalleHTTPResp IS NULL THEN
      # We got no response, still waiting for
      CALL WSHelper_FillSOAP12WSError("Sender","Response was not yet received")
      RETURN -2      
    END IF

      #
      # RETRIEVE SERVICE SESSION COOKIE
      #
      LET setcookie = consultarCurpDetalleHTTPResp.getHeader("Set-Cookie")
      IF setcookie IS NOT NULL THEN
        LET ConsultaCurpDetalleService_ConsultaCurpDetalleServiceHttpsSoap12EndpointEndpoint.Binding.Cookie = WSHelper_ExtractServerCookie(setcookie,ConsultaCurpDetalleService_ConsultaCurpDetalleServiceHttpsSoap12EndpointEndpoint.Address.Uri)
      END IF

      #
      # RETRIEVE HTTP RESPONSE Headers
      #
      CALL WSHelper_SetResponseHeaders(consultarCurpDetalleHTTPResp, ConsultaCurpDetalleService_ConsultaCurpDetalleServiceHttpsSoap12EndpointEndpoint.Binding.Response.Headers)
      CASE consultarCurpDetalleHTTPResp.getStatusCode()

        WHEN 500 # SOAP Fault
          #
          # Check SOAP 1.2 MimeType
          #
          IF NOT WSHelper_CheckSOAP12HttpMimeType(consultarCurpDetalleHTTPResp) THEN
            EXIT CASE
          END IF
          #
          # STAX SOAP FAULT
          #
          LET reader = consultarCurpDetalleHTTPResp.beginXmlResponse() # Begin Streaming Response
          IF NOT WSHelper_ReadStaxSOAP12StartEnvelope(reader) THEN
            EXIT CASE
          END IF
          # Process SOAP headers 
          IF WSHelper_CheckStaxSOAP12Header(reader) AND NOT reader.isEmptyElement() THEN
            CALL reader.nextTag()
            WHILE (reader.getEventType()=="START_ELEMENT")
              IF WSHelper_CheckStaxSOAP12HeaderRole(reader,uri) THEN
                LET mustUnderstand = WSHelper_GetStaxSOAP12HeaderMustUnderstand(reader)
                IF mustUnderstand = -1 THEN
                  CALL WSHelper_FillSOAP11WSError("Sender","Invalid mustUnderstand value")
                  EXIT CASE
                END IF
                IF mustUnderstand THEN
                  CALL WSHelper_FillSOAP12WSError("MustUnderstand","Mandatory header block not understood")
                  EXIT CASE
                ELSE
                  CALL reader.nextSibling() # Skip header, not necessary
                END IF
              ELSE
                CALL reader.nextSibling() # Skip header, not intended to us
              END IF
            END WHILE
            IF NOT WSHelper_CheckStaxSOAP12Header(reader) THEN
              CALL WSHelper_FillSOAP11WSError("Sender","No ending header tag found")
              EXIT CASE
            ELSE
              CALL reader.nextTag()
            END IF
          ELSE
            IF WSHelper_CheckStaxSOAP12Header(reader) THEN
              CALL reader.nextSibling() # Skip SOAP headers
            END IF
          END IF
          IF NOT WSHelper_ReadStaxSOAP12StartBody(reader) THEN
            EXIT CASE
          END IF
          IF NOT WSHelper_ReadStaxSOAP12StartFault(reader) THEN
            EXIT CASE
          END IF
          IF NOT WSHelper_ReadStaxSOAP12FaultUntilDetail(reader) THEN
            EXIT CASE
          END IF
          IF WSHelper_CheckStaxSOAP12FaultDetail(reader) THEN
            #
            # STAX SOAP FAULT DESERIALIZE
            #
            CALL reader.nextSibling() # Skip SOAP detail
          END IF
          IF NOT WSHelper_ReadStaxSOAP12EndFault(reader) THEN
            EXIT CASE
          END IF
          IF NOT WSHelper_ReadStaxSOAP12EndBody(reader) THEN
            EXIT CASE
          END IF
          IF NOT WSHelper_ReadStaxSOAP12EndEnvelope(reader) THEN
            EXIT CASE
          END IF
          # End Streaming Response
          CALL consultarCurpDetalleHTTPResp.endXmlResponse(reader)

        WHEN 200 # SOAP Result
          #
          # Check SOAP 1.2 MimeType
          #
          IF NOT WSHelper_CheckSOAP12HttpMimeType(consultarCurpDetalleHTTPResp) THEN
            EXIT CASE
          END IF
          #
          # STAX SOAP RESPONSE
          #
          LET reader = consultarCurpDetalleHTTPResp.beginXmlResponse() # Begin Streaming Response
          IF NOT WSHelper_ReadStaxSOAP12StartEnvelope(reader) THEN
            EXIT CASE
          END IF
          # Process SOAP headers 
          IF WSHelper_CheckStaxSOAP12Header(reader) AND NOT reader.isEmptyElement() THEN
            LET nb = 0
            CALL reader.nextTag()
            WHILE (reader.getEventType()=="START_ELEMENT")
              IF WSHelper_CheckStaxSOAP12HeaderRole(reader,uri) THEN
                LET mustUnderstand = WSHelper_GetStaxSOAP12HeaderMustUnderstand(reader)
                IF mustUnderstand = -1 THEN
                  CALL WSHelper_FillSOAP12WSError("Sender","Invalid mustUnderstand value")
                  EXIT CASE
                END IF
                #
                # STAX SOAP RESPONSE HEADER DESERIALIZE
                #
                IF mustUnderstand THEN
                  CALL WSHelper_FillSOAP12WSError("MustUnderstand","Mandatory header block not understood")
                  EXIT CASE
                ELSE
                  CALL reader.nextSibling() # Skip header, not necessary
                END IF
              ELSE
                CALL reader.nextSibling() # Skip header, not intended to us
              END IF
            END WHILE
            IF NOT WSHelper_CheckStaxSOAP12Header(reader) THEN
              CALL WSHelper_FillSOAP12WSError("Sender","No ending header tag found")
              EXIT CASE
            ELSE
              IF nb != 0 THEN
                CALL WSHelper_FillSOAP12WSError("Sender","One or more headers are missing")
                EXIT CASE
              ELSE
                CALL reader.nextTag()
              END IF
            END IF
          ELSE
           IF reader.isEmptyElement() THEN
             CALL reader.nextTag()
           END IF
          END IF
          IF NOT WSHelper_ReadStaxSOAP12StartBody(reader) THEN
            EXIT CASE
          END IF
          IF NOT WSHelper_RetrieveStaxSOAP12Message(reader) THEN
            EXIT CASE
          END IF
          #
          # STAX SOAP RESPONSE DESERIALIZE
          #
          CALL xml.Serializer.StaxToVariable(reader,ns2consultarCurpDetalleResponse)
          IF NOT WSHelper_ReadStaxSOAP12EndBody(reader) THEN
            EXIT CASE
          END IF
          IF NOT WSHelper_ReadStaxSOAP12EndEnvelope(reader) THEN
            EXIT CASE
          END IF
          # End Streaming Response
          CALL consultarCurpDetalleHTTPResp.endXmlResponse(reader)
          LET wsstatus = 0

        OTHERWISE
          CALL WSHelper_FillSOAP12WSError("Receiver","HTTP Error "||consultarCurpDetalleHTTPResp.getStatusCode()||" ("||consultarCurpDetalleHTTPResp.getStatusDescription()||")")

      END CASE
    CATCH
      LET wsstatus = status
      CALL WSHelper_FillSOAP12WSError("Receiver",sqlca.sqlerrm)
    END TRY

  #
  # RESET VARIABLES
  #
  LET consultarCurpDetalleHTTPReq = NULL
  LET consultarCurpDetalleHTTPResp = NULL
  RETURN wsstatus

END FUNCTION



#
# Operation: getConfirm
#

#
# FUNCTION: getConfirm
#
FUNCTION getConfirm(p_sessionID, p_Mssg)
  DEFINE	p_sessionID		STRING
  DEFINE	p_Mssg		STRING
  DEFINE	soapStatus		INTEGER


  LET ns2getConfirm.sessionID = p_sessionID
  LET ns2getConfirm.Mssg = p_Mssg

  LET soapStatus = getConfirm_g()

  RETURN soapStatus
END FUNCTION

#
# FUNCTION: getConfirm_g
#   RETURNING: soapStatus
#   INPUT: GLOBAL ns2getConfirm
#   OUTPUT: NONE
#
FUNCTION getConfirm_g()
  DEFINE wsstatus   INTEGER
  DEFINE retryAuth  INTEGER
  DEFINE retryProxy INTEGER
  DEFINE retry      INTEGER
  DEFINE uri        STRING
  DEFINE setcookie  STRING
  DEFINE request    com.HttpRequest
  DEFINE response   com.HttpResponse
  DEFINE writer     xml.StaxWriter

  #
  # INIT VARIABLES
  #
  LET wsstatus = -1
  LET retryAuth = FALSE
  LET retryProxy = FALSE
  LET retry = TRUE
  LET uri = com.WebServiceEngine.GetOption("SoapModuleURI")

  IF ConsultaCurpDetalleService_ConsultaCurpDetalleServiceHttpsSoap12EndpointEndpoint.Address.Uri IS NULL THEN
    LET ConsultaCurpDetalleService_ConsultaCurpDetalleServiceHttpsSoap12EndpointEndpoint.Address.Uri = "https://websdes.curp.gob.mx:8443/WebServicesConsulta/services/ConsultaCurpDetalleService.ConsultaCurpDetalleServiceHttpsSoap12Endpoint/"
  END IF

  #
  # CREATE REQUEST
  #
  TRY
    LET request = com.HttpRequest.Create(ConsultaCurpDetalleService_ConsultaCurpDetalleServiceHttpsSoap12EndpointEndpoint.Address.Uri)
    CALL request.setMethod("POST")
    CALL request.setCharset("UTF-8")
    CALL request.setHeader("Content-Type","application/soap+xml; action=\"urn:getConfirm\"")
    CALL WSHelper_SetRequestHeaders(request, ConsultaCurpDetalleService_ConsultaCurpDetalleServiceHttpsSoap12EndpointEndpoint.Binding.Request.Headers)
    IF ConsultaCurpDetalleService_ConsultaCurpDetalleServiceHttpsSoap12EndpointEndpoint.Binding.Version IS NOT NULL THEN
      CALL request.setVersion(ConsultaCurpDetalleService_ConsultaCurpDetalleServiceHttpsSoap12EndpointEndpoint.Binding.Version)
    END IF
    IF ConsultaCurpDetalleService_ConsultaCurpDetalleServiceHttpsSoap12EndpointEndpoint.Binding.Cookie IS NOT NULL THEN
      CALL request.setHeader("Cookie",ConsultaCurpDetalleService_ConsultaCurpDetalleServiceHttpsSoap12EndpointEndpoint.Binding.Cookie)
    END IF
    IF ConsultaCurpDetalleService_ConsultaCurpDetalleServiceHttpsSoap12EndpointEndpoint.Binding.ConnectionTimeout <> 0 THEN
      CALL request.setConnectionTimeOut(ConsultaCurpDetalleService_ConsultaCurpDetalleServiceHttpsSoap12EndpointEndpoint.Binding.ConnectionTimeout)
    END IF
    IF ConsultaCurpDetalleService_ConsultaCurpDetalleServiceHttpsSoap12EndpointEndpoint.Binding.ReadWriteTimeout <> 0 THEN
      CALL request.setTimeOut(ConsultaCurpDetalleService_ConsultaCurpDetalleServiceHttpsSoap12EndpointEndpoint.Binding.ReadWriteTimeout)
    END IF
    IF ConsultaCurpDetalleService_ConsultaCurpDetalleServiceHttpsSoap12EndpointEndpoint.Binding.CompressRequest IS NOT NULL THEN
      CALL request.setHeader("Content-Encoding",ConsultaCurpDetalleService_ConsultaCurpDetalleServiceHttpsSoap12EndpointEndpoint.Binding.CompressRequest)
    END IF
    CALL request.setHeader("Accept-Encoding","gzip, deflate")
  CATCH
    LET wsstatus = status
    CALL WSHelper_FillSOAP12WSError("Sender","Cannot create HttpRequest")
    RETURN wsstatus    
  END TRY

  # START LOOP
  WHILE retry
    LET retry = FALSE

    #
    # Stax request
    #
    TRY
      LET writer = request.beginXmlRequest()
      CALL WSHelper_WriteStaxSOAP12StartEnvelope(writer)
      CALL WSHelper_WriteStaxSOAP12StartBody(writer)
      #
      # STAX SOAP REQUEST SERIALIZE
      #
      CALL xml.Serializer.VariableToStax(ns2getConfirm,writer)
      CALL WSHelper_WriteStaxSOAP12EndBody(writer)
      CALL WSHelper_WriteStaxSOAP12EndEnvelope(writer)
      CALL request.endXmlRequest(writer)
    CATCH
      LET wsstatus = status
      CALL WSHelper_FillSOAP12WSError("Sender",sqlca.sqlerrm)
      RETURN wsstatus    
    END TRY

    #
    # PROCESS RESPONSE
    #
    TRY
      LET response = request.getResponse()

      #
      # RETRIEVE SERVICE SESSION COOKIE
      #
      LET setcookie = response.getHeader("Set-Cookie")
      IF setcookie IS NOT NULL THEN
        LET ConsultaCurpDetalleService_ConsultaCurpDetalleServiceHttpsSoap12EndpointEndpoint.Binding.Cookie = WSHelper_ExtractServerCookie(setcookie,ConsultaCurpDetalleService_ConsultaCurpDetalleServiceHttpsSoap12EndpointEndpoint.Address.Uri)
      END IF

      #
      # RETRIEVE HTTP RESPONSE Headers
      #
      CALL WSHelper_SetResponseHeaders(response, ConsultaCurpDetalleService_ConsultaCurpDetalleServiceHttpsSoap12EndpointEndpoint.Binding.Response.Headers)
      CASE response.getStatusCode()

        WHEN 200 # OK
          LET wsstatus = 0

        WHEN 201 # Created
          LET wsstatus = 0

        WHEN 202 # Accepted
          LET wsstatus = 0

        WHEN 203 # Non-Authoritative Information
          LET wsstatus = 0

        WHEN 204 # No Content
          LET wsstatus = 0

        WHEN 401 # HTTP Authentication
          IF retryAuth THEN
            CALL WSHelper_FillSOAP12WSError("Receiver","HTTP Error 401 ("||response.getStatusDescription()||")")
          ELSE
            LET retryAuth = TRUE
            LET retry = TRUE
          END IF

        WHEN 407 # Proxy Authentication
          IF retryProxy THEN
            CALL WSHelper_FillSOAP12WSError("Receiver","HTTP Error 407 ("||response.getStatusDescription()||")")
          ELSE
            LET retryProxy = TRUE
            LET retry = TRUE
          END IF

        OTHERWISE
          CALL WSHelper_FillSOAP12WSError("Receiver","HTTP Error "||response.getStatusCode()||" ("||response.getStatusDescription()||")")

      END CASE
    CATCH
      LET wsstatus = status
      CALL WSHelper_FillSOAP12WSError("Receiver",sqlca.sqlerrm)
      RETURN wsstatus      
    END TRY

  # END LOOP
  END WHILE

  RETURN wsstatus

END FUNCTION


FUNCTION getConfirmRequest_g()
  DEFINE wsstatus   INTEGER
  DEFINE writer     xml.StaxWriter

  #
  # CREATE REQUEST
  #
  TRY
    LET getConfirmHTTPReq = com.HttpRequest.Create(ConsultaCurpDetalleService_ConsultaCurpDetalleServiceHttpsSoap12EndpointEndpoint.Address.Uri)
    CALL getConfirmHTTPReq.setMethod("POST")
    CALL getConfirmHTTPReq.setCharset("UTF-8")
    CALL getConfirmHTTPReq.setHeader("Content-Type","application/soap+xml; action=\"urn:getConfirm\"")
    CALL WSHelper_SetRequestHeaders(getConfirmHTTPReq, ConsultaCurpDetalleService_ConsultaCurpDetalleServiceHttpsSoap12EndpointEndpoint.Binding.Request.Headers)
    IF ConsultaCurpDetalleService_ConsultaCurpDetalleServiceHttpsSoap12EndpointEndpoint.Binding.Version IS NOT NULL THEN
      CALL getConfirmHTTPReq.setVersion(ConsultaCurpDetalleService_ConsultaCurpDetalleServiceHttpsSoap12EndpointEndpoint.Binding.Version)
    END IF
    IF ConsultaCurpDetalleService_ConsultaCurpDetalleServiceHttpsSoap12EndpointEndpoint.Binding.Cookie IS NOT NULL THEN
      CALL getConfirmHTTPReq.setHeader("Cookie",ConsultaCurpDetalleService_ConsultaCurpDetalleServiceHttpsSoap12EndpointEndpoint.Binding.Cookie)
    END IF
    IF ConsultaCurpDetalleService_ConsultaCurpDetalleServiceHttpsSoap12EndpointEndpoint.Binding.ConnectionTimeout <> 0 THEN
      CALL getConfirmHTTPReq.setConnectionTimeOut(ConsultaCurpDetalleService_ConsultaCurpDetalleServiceHttpsSoap12EndpointEndpoint.Binding.ConnectionTimeout)
    END IF
    IF ConsultaCurpDetalleService_ConsultaCurpDetalleServiceHttpsSoap12EndpointEndpoint.Binding.ReadWriteTimeout <> 0 THEN
      CALL getConfirmHTTPReq.setTimeOut(ConsultaCurpDetalleService_ConsultaCurpDetalleServiceHttpsSoap12EndpointEndpoint.Binding.ReadWriteTimeout)
    END IF
    IF ConsultaCurpDetalleService_ConsultaCurpDetalleServiceHttpsSoap12EndpointEndpoint.Binding.CompressRequest IS NOT NULL THEN
      CALL getConfirmHTTPReq.setHeader("Content-Encoding",ConsultaCurpDetalleService_ConsultaCurpDetalleServiceHttpsSoap12EndpointEndpoint.Binding.CompressRequest)
    END IF
    CALL getConfirmHTTPReq.setHeader("Accept-Encoding","gzip, deflate")
  CATCH
    LET wsstatus = status
    CALL WSHelper_FillSOAP12WSError("Sender","Cannot create HttpRequest")
    LET getConfirmHTTPReq = NULL
    RETURN wsstatus    
  END TRY

    #
    # Stax request
    #
    TRY
      LET writer = getConfirmHTTPReq.beginXmlRequest()
      CALL WSHelper_WriteStaxSOAP12StartEnvelope(writer)
      CALL WSHelper_WriteStaxSOAP12StartBody(writer)
      #
      # STAX SOAP REQUEST SERIALIZE
      #
      CALL xml.Serializer.VariableToStax(ns2getConfirm,writer)
      CALL WSHelper_WriteStaxSOAP12EndBody(writer)
      CALL WSHelper_WriteStaxSOAP12EndEnvelope(writer)
      CALL getConfirmHTTPReq.endXmlRequest(writer)
    CATCH
      LET wsstatus = status
      CALL WSHelper_FillSOAP12WSError("Sender",sqlca.sqlerrm)
      LET getConfirmHTTPReq = NULL
      RETURN wsstatus    
    END TRY

  #
  # SKIP PROCESS RESPONSE
  #
  LET getConfirmHTTPReq = NULL
  RETURN 0 # SUCCESS
END FUNCTION


